### ISSUE TITLE
Sektör Değiştirme için en güzel tavsiyeniz nedir?

### ISSUE THREAD

**Issue by celalanak** [VB10/vboverflow#1]
Hocam merhaba,

Ben 10 senedir sistemciyim (MCP, MCSA) :) yazılıma yönelmek istiyorum, kafamda efsane projeler var, ama işin işinden bir türlü çıkamıyorum, sizin ağzınızdan çıkacak söz benim için çok önemli, Celal buraya yoğunlaş başka bir şeyle uğraşma, gibi.

Zaman ayırıp cevaladığınız için şimdiden çok teşekkür ederim.

**Comment by VB10** [comment]
Selamlar
Sistem tarafında benim arkadaşlarım var ve genel olarak algoritmik yapı oluyor sizlerde benim bildiğim gördüğüm. Burada çok yöntem var ama benim önereceğim ve safe olan önce bir front end başlamak. Neden

- Bir ön yüz işi almak her zaman içi kolaydır misal bir websitesi bir mobil uygulama olur ve front enddeki kalite bir nebze gözden gelibenbilir
- Backend tarfına geçmek yani database vs yapmak hem zor hemde ciddi  tecrübe ister bunun yerine firebase gibi hazır çözümlerle front end birleşitrip kısa vadede yazılıma geçiş çok daha rahat olur.

Tabi hayatta neler çıkartır bakmak lazım ama yazılım kısmında para odaklı gitmek olarak düşünecek olursak çünkü hayat şartları front end iyi bir giriş sonrasından backend vs devam edecektir.

Kolay gelsin iyi çalışmalar şimdiden

**Comment by VB10** [comment]
dil olarak da js,dart bunların onune dart react öğrenebilir çok hızlı işler için @celalanak

**Comment by celalanak** [comment]
Hocam, çok teşekkür ederim. 🙏 🙏 🙏
