### ISSUE TITLE
Çocuklar için nasıl bir yol izlenmeli

### ISSUE THREAD

**Issue by tunahanugrasir** [VB10/vboverflow#10]
Hocam merhabalar,

Benim 2 küçük kardeşim var. Biri 7. sınıfa geçecek diğeri liseye geçecek. İkiside benim gibi bilgisayar mühendisliği okumak istediklerini söylüyorlar ama sadece lafta böyle. Ben abileri olarak onlarında yazılıma ilgi duymalarını istiyorum. Gün boyunca hep bilgisayar başındalar ama hep boş şeylerle uğraşıyorlar. Onları nasıl yönlendirebilirim ne gibi kitaplar videolar sağlayabilirim? İnternette oyun üzerine kurulu yazılım eğitimlerini pek sevmiyorlar. Birkaç gün önce C derslerini göstereyim dedim yaparken zevk aldılar ama iki gün sonra hiç bakmadılar bile. Tam olarak ne yapmam gerektiğini bilmiyorum.

Yardımcı olursanız sevinirim hocam, iyi günler dilerim.

**Comment by ibrahimcss** [comment]
basit olarak console uygulamalari ile baslamalari daha uygun olur, ekrana bir helloworld yazmalari bile ufuklarini acar basit algoritmalar ile bazi problemleri cozmeleri iclerinde sorgulama ve merak duygusunu uyandirir. low level dillerden birini secerek devam etmelisiniz.

**Comment by ozkanozcan** [comment]
Benim oğlum 14 yaşında liseye bu sene başlayacak. Biz programlamaya şu adımlarla başladık.

Önce ingilizce.
[English Central](https://tinyurl.com/batuhan-ingilizce) ile 1 sene boyunca her gün yaptığı birebir pratik sayesinde şu anda  C1 seviyesinde konuşabiliyor. 

İngilizceyi halledince de programlamaya geçtik. 

[1- Herkes İçin Temel Dersler - Patika.dev ](https://app.patika.dev/courses/herkes-icin-temel-dersler)
[2-Git, git komutları, versiyon kontrol sistemi, git bash, markdown,repo hosting - Patika.dev](https://app.patika.dev/courses/git)
[3-Visual Studio Code Kullanımı](https://app.patika.dev/courses/visual-studio-code-kullanimi)
[4-Veri Yapıları ve Algoritmalar - Patika.dev](https://app.patika.dev/courses/veri-yapilari-ve-algoritmalar)
[5-10 Derste Algoritma - Murat Yücedağ-Youtube](https://www.youtube.com/playlist?list=PLKnjBHu2xXNNiJdlhiEl_RMkK0PbJ1_DB)

Şu anda da birebir özel dersle Yazılım müh. öğrencisinden Python dersleri alıyor ve Python öğreniyor. 

Java ve C başlangıç için gençlere ağır gelebilir. Go veya Python ilk başlangıç için bence yeterli. 

Zaten algoritme kurma ve object oriented programlama mantığını öğrendikten sonra başka dile geçmek için sadece sentax öğrenmesi yeterli olacak. Başlangıçta araştırmayı, sorun algılama ve çözüm yolunu keşfetmeyi, algoritma kurmayı öğrenmesi bence daha önemli.

**Comment by VB10** [comment]
@ozkanozcan muthis ancak bence bir tik fazla bu kadar size tek tavsiyem tr de tutmayin yurt disinda calissin.

Benim kardesim 15 yasinda suan appstore da kendi uygulamasini yazdi projesi var kendi algortimasini uretiyor calisiyor.

- Bu yolda giderken 9 yasinda baslayan bir seruvende oncelikle strach microsft kodu ile basladik proje yazmayi ogrettim
- Her ilerledikce oyun oynadik oyunlara asina ettik
- Ilk etapta C# ile baslayip bastice bir kac kod yazip gectik bunun icin sefer alganin kitabini alip buunu islettim
- Uzerine Html ile bir kac guzellik yapip ekran goruntusu almayi ogrettik bunlari herhangi bir portaldan alip yapaiblrisiniz
- En son olarak swift dart ile ilerleyip cozduk.

Bunlari yaparken spor saglik ingilzce konularinda basit bir kac calisma yapip projesini de gecirttk hayata hicbir zaman 1-1 to yapmadim cani sikilmamasi adina egitim setlerini verip bir kac defa review ettim destekledim
- Algoritma konusunda ise hayat bir algoritma diyip hep buradan referans ediyorum kod kodda degil hayatta. cozuluyor bir daha bu yasa gelmeyecegi icinde onun hayattan zevk almasini saglayarak basardim.

Burada en buyuk done mutlu olmak bunu bilrikte goturmek hicbir ekstra egitimede gerek oldugunu dusunmuyorum sektor youtube hepsi yeterli.
Ing. vs zaten bunlar bu donemin en olmazsa olmaz noktasi cocuklari skmak onlari ilerde kaybettiren bir yol acabilir

Guzel ve basarili bir hayati olur umarim

**Comment by tunahanugrasir** [comment]
Tavsiyeleriniz için çok teşekkür ederim.
