### ISSUE TITLE
Telefon dönmesine rağmen sabit kalan nesne uygulaması

### ISSUE THREAD

**Issue by urazalkis** [VB10/vboverflow#100]
Arkadaşlar merhaba.Bu konu nasıl adlandırılır bilmiyorum onun için bir video içerik ile anlatmak istedim.Tam da bu videodaki gibi telefon ekranı döndüğü halde sabit duran nesne örneğin pusula gibi ama tam da değil aslında.Bunu nasıl gerçekleştirebilirim ya da herhangi bir flutter paketi mevcut mudur bu işlemleri yapabileceğim? Teşekkürler
https://user-images.githubusercontent.com/43914441/183417922-f7c1e161-7bd9-474e-8e33-3e516fa53708.mp4

**Comment by abdullahkaraboga** [comment]
"Ben olsam" pub.dev'de sensors_plus eklentisinden gyroscope özelliğini kullanıp gelen değeler ile  sarmaladığım widget'a dönme açısı verebileceğim bir widget(RotationTransition, RotatedBox vb) kullanarak angle değerlerini dynamic olarak güncellerdim. Böylelikle harekete göre ters değerler vererek widget'ı sabit tutardım.

**Comment by urazalkis** [comment]
> "Ben olsam" pub.dev'de sensors_plus eklentisinden gyroscope özelliğini kullanıp gelen değeler ile sarmaladığım widget'a dönme açısı verebileceğim bir widget(RotationTransition, RotatedBox vb) kullanarak angle değerlerini dynamic olarak güncellerdim. Böylelikle harekete göre ters değerler vererek widget'ı sabit tutardım.

gyroscope özelliği sanırım kilit nokta.sensor_plus da bunu sağlıyor bu ekletiyi araştıracağım teşekkürler.
