### ISSUE TITLE
Orientation animasyonu olmadan yeni sayfa geçiş yapma

### ISSUE THREAD

**Issue by faithtnuc** [VB10/vboverflow#101]
Selamlar, 

Ben Netflix tarzı bir video izleme uygulaması yapıyorum. Uygulama portrait modda çalışıyor ancak içeriğe tıklandığında video player'ı farklı bir sayfada açıp o sayfayı landscape yapıyorum ki full ekran izlensin. Bu olurken de dolayısıyla önce ekranda bir dönme animasyonu oluyor ve öyle açılıyor. Videodan geri çıktığımda da önce geri çıkıyor ve sonra bir dönme animasyonu oluyor. Bunu Flutter ile Netflix, Prime Video veya Disney+'ta yaptıkları gibi animasyonsuz bir şekilde yapabilme şansım var mı? Yani portrait olan sayfadan landscape olan sayfaya geçiş yapacağım ama sayfa animasyonsuz şekilde açılacak.

Teşekkürler

**Comment by abdullahkaraboga** [comment]
Benzer bir [soru](https://stackoverflow.com/questions/72898577/how-to-turn-off-screen-rotation-animation-while-switching-from-landscape-to-port), faydası olabilir.

**Comment by faithtnuc** [comment]
> Benzer bir [soru](https://stackoverflow.com/questions/72898577/how-to-turn-off-screen-rotation-animation-while-switching-from-landscape-to-port), faydası olabilir.

Bir kişi native tarafta bir şeyler önermiş ama tam anlayamadım. Diğer kişiler ve başka konularda da genelde yanlış anlayıp orientation'ı kitlemeyi anlatmışlar. Ben araştırmaya devam edeyim bulamazsam da o şekilde kalacak yapacak bir şey yok. Teşekkürler

**Comment by aydemiromer** [comment]
shimmer effect ile video açılıyormuş hissiyatı verebilirsin circularprogressten daha iyi görünebilir
