### ISSUE TITLE
Navigator.push ile data aktarımı

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#102]
Merhabalar. 
Sayfalar arası geçişte bir formdan diğerine navigator.push ile data aktarımı yapıyorum. DocumentSnapshot dan bir data çekip diğer forma çekiyorum. Benim amacım çekmiş olduğum datayı bir kayıt fonksiyonu içinde göstererek otomatik kayıt yapmak.
Kodlarımı alt kısımda göstereceğim. Yardımcı olabilecek fikir sunabilecek olursa şimdiden çok teşekkür ederim.
--Data çektiğim Form 
floatingActionButton: FloatingActionButton(child:Icon(Icons.add),
      onPressed: (){
        Navigator.push(context, MaterialPageRoute(builder: (_)=>Faaliyet(faaliyetKullaniciBilgisi: adsoyad)));
      }),

--Datanın geldiği form
faaliyetEkle(){
    firestore.collection('faaliyet')
        .doc(faaliyetAdi.text)
        .set({'faaliyetAdi':faaliyetAdi.text,
              'faaliyetKullanici':?????????????????????????
              'faaliyetTarihi':faaliyetTarihi.text,
              'faaliyetYeri':faaliyetYeri.text,
              'faaliyetDerece':faaliyetDerece.text,
              'faaliyetBasari':faaliyetBasari.text});
    }

*2. formda Constructar tanımlama işlemlerini hallettim. Yardım almak istediğim kısım ????????? olan kısma ne gibi bir satır yazmalıyım.

**Comment by Barismano** [comment]
hocam datanın pass edildiği sayfada datayı "widget.data" gibi bi ifade ile kullanılması lazım yanlış hatırlamıyorsam

istersen flutter döküman > https://docs.flutter.dev/cookbook/navigation/passing-data
