### ISSUE TITLE
Custom widget'dan value dönme işlemi

### ISSUE THREAD

**Issue by osmancan23** [VB10/vboverflow#103]
Örneğin bir ekranımız var ekranda bir tane custom expansion tile widget ve buton var. Ve biz buraya bir kullanıcı listesi gönderiyoruz . Bu widget bu listede değişiklikler yapıyor ekleme çıkarma gibi ardından ben ana sayfamdaki butona tıkladığımda o expansion tile a gönderdiğim listenin değişiklik yapılmış haline nasıl erişebilirim. Tabi ki state management yöntemleri kullanılarak listeyi güncelledigimde provider ile listeyi kaydedip diğer sayfada okuyabilirim ama daha basit bir yöntemi var mı ?

**Comment by sinanhaci** [comment]
Biraz daha örnekleyerek anlatabilir misin? Kod veya yapmak istediğin şeyin görselini paylaşmak sana yardım etmemizi kolaylaştırır.

**Comment by osmancan23** [comment]
![Ekran görüntüsü 2022-08-16 140924](https://user-images.githubusercontent.com/83430594/184865455-a1c9aa27-1946-4ef2-8dac-70820d0f7732.png)

Şu şekilde bir custom expansion widgetım var . Buna bir kullanıcı listesi gönderiyorum o da o kullanıcı listesindeki kullanıcıları listeliyor. Ardından ben birkaç kullanıcı seçiyorum ve bu seçtiğim kullanıcıları bir liste içerisine atıyorum. Ardından ben bu sayfamdaki butona bastığımda bu seçtiğim kullanıcı listesine state management yöntemleri kullanmadan erişmem mümkün mü  , yani değer dönen bir custom widget yapılabilir mi ?

**Comment by osmancan23** [comment]
`class RawScrollableUsers extends StatefulWidget {
  final List<UserModel> userList;
  final Color? expansionTileWidgetColor;
  final bool? isLimitUserCount;
  final List<UserModel>? initialUser;
  final String? hintText;
  final Function(List<UserModel> userList)? onCompletedChose;`

**Comment by osmancan23** [comment]
_Bu issue!yi açalı bayağı zaman geçti eskiden böyle bir işlem için provider gibi state manegement yöntemleri kullanıyordum ama bu bayağı karışık bir sistem oluyordu . Yakın zamanda bunun bir çözümünü buldum . Sizlerle de paylaşmak istiyorum. 
Örneğin benim bir userler'i seçebileceğim bir expansion tile widget'ım var. Bu yapı custom şeklinde kullanmak istediğim sayfada bir user list vererek sayfamda görüyorum . Benim istediğim sayfamda bulunan butona bastığımda ben seçtiğim kullanıcıları alabileyim ._


**Bunun için  1 numaralı kodda göründüğü üzere custom widgetım onCompletedChose adında bir parametre alıyor. Bu parametre UserModel List alan bir Function. Ardından da 2 numaralı kodda göründüğü üzere ben her kullanıcı seçtiğimde widget.onCompletedChose?.call(choosenUserList) ile bana sayfamdan gelen fonksiyonu cağırıyorum ve listemi bu fonksiyona gönderiyorum. Ardında da sayfamda 3 numaralı kodda göründüğü üzere listeme erişebiliyorum.**

**1**
```
class RawScrollableUsers extends StatefulWidget {

  final Function(List<UserModel> userList)? onCompletedChose;

```

**2**

` widget.onCompletedChose?.call(choosenUserList);
`

**3**
```
 RawScrollableUsers(
                        userList: state.userList,
                        onCompletedChose: (userList) {
                          members = userList;
                        },
                      )
```
