### ISSUE TITLE
Flutter firebase Authentication 

### ISSUE THREAD

**Issue by memin745** [VB10/vboverflow#104]
Firebase ile kurulumu yaptık fakat uygulamadan her cıktığında tekrar giriş istiyor ne yapabilirz ?

**Comment by aydemiromer** [comment]
Selamlar, landing screen yaparak firebase ile giriş yapan kullanıcı olmuş mu olmamış mı bunu dinleyebilirsin, initial sayfanı landing sayfası yapıp bu sayfada kullanıcı varsa anasayfana yoksa login sayfana yönlendirmen gerek

**Comment by aydemiromer** [comment]
class LandingPage extends StatelessWidget {
  const LandingPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    IAuthenticationService authenticationService =
        AuthenticationService(FirebaseAuth.instance, GoogleLogin(), AppleSocialLogin());
    final auth = authenticationService.authStateChanges();
    return StreamBuilder<User?>(
      stream: auth,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final User? user = snapshot.data;
          if (user == null) {
            return const LoginView();
          }
          return const Navbar();
        }
        return const Scaffold(
          body: Center(
            child: CircularProgressIndicator(),
          ),
        );
      },
    );
  }
}

**Comment by aydemiromer** [comment]
```
class LandingPage extends StatelessWidget {
  const LandingPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    IAuthenticationService authenticationService =
        AuthenticationService(FirebaseAuth.instance, GoogleLogin(), AppleSocialLogin());
    final auth = authenticationService.authStateChanges();
    return StreamBuilder<User?>(
      stream: auth,
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.active) {
          final User? user = snapshot.data;
          if (user == null) {
            return const LoginView();
          }
          return const Navbar();
        }
        return const Scaffold(
          body: Center(
            child: CircularProgressIndicator(),
          ),
        );
      },
    );
  }
}

```

**Comment by aydemiromer** [comment]
Şu şekilde bir örnek kullanımım mevcut sen kendi servisini dinleyebilir veya provider ile func. dinleyip yönlendirmeni yapabilirsin

**Comment by aydemiromer** [comment]
@override
  Stream<User?>? authStateChanges() => firebaseAuth.authStateChanges();
 

Servisimde bu şekilde dinliyor
