### ISSUE TITLE
html editor

### ISSUE THREAD

**Issue by mehmetshakar** [VB10/vboverflow#106]
Merhaba,

flutter da sorunsuz çalışan html editör arıyorum fakat henüz bulamadım.

https://pub.dev/packages/html_editor_enhanced paketini denedim ancak bazen henüz yüklenemedi hatası, bazen donuyor, bazen de işlemciyi çok yoruyor, ayrıca da türkçe dil desteği de yok.

acaba html editör önerisi var mı?

çok teşekkürler.

**Comment by aydemiromer** [comment]
editör olarak değilde html vs css dosyalarını run edebildiğimiz flutter_html paketi var belki o da işine yarayabilir

**Comment by mehmetshakar** [comment]
Teşekkür ederim Ömer Bey,

editör olarak lazım.

**Comment by abdullahkaraboga** [comment]
https://pub.dev/packages/code_editor böyle bir package var belki işinize yarayabilir.

**Comment by mehmetshakar** [comment]
bu daha çok dosya düzenleme, benim istediğim zengin metin editörü.. 

çok teşekkür ederim Abdullah bey.
