### ISSUE TITLE
DataTableiçinde veri yok ise Hata mesajı döndürme

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#107]
Merhabalar. Bir projemde verilerimi firebase den çekerek tabloya yazdırma işlemi yapıyorum. DataTable içerisine çektiğim kullanıcı bilgilerinde Eğer kullanıcıda bilgi yok ise ekran ortasında uyarı mesajı döndürmek istiyorum. Kodlarımı aşağıda paylaşacağım fikri olan olursa şimdiden teşekkür ederim.
                      child: DataTable(
                            columnSpacing: 30,
                            horizontalMargin: 10,
                            showCheckboxColumn: false,
                            dataRowHeight: 50,
                            
                          columns: <DataColumn>[
                            
                          const DataColumn(
                          label: Text('Kullanıcı',style:TextStyle(fontWeight:FontWeight.w600,fontSize:15,color:Colors.black)),
                          ),
                          const DataColumn(
                            label: Text('Tarih',style:TextStyle(fontWeight:FontWeight.w600,fontSize:15,color:Colors.black)),
                          ),
                        ],
                          rows: _createRows(snapshot.data!,context),
                          
                        ),

--------------------------------------------------------------------------------------------------

List<DataRow> _createRows(QuerySnapshot snapshot,context){
  List<DataRow> newList = snapshot.docs.map((DocumentSnapshot documentSnapshot)
  {
    return DataRow(
      cells:[
      DataCell(Text(documentSnapshot['Kullanici'].toString())),
      DataCell(Text(documentSnapshot['Tarih'].toString())),
      ...........................
    ]);
  }).toList();
  return newList;
}

**Comment by abdullahtas0** [comment]
Gelen verileri atadığınız listenin uzunluğunu kontrol edebilirsiniz mesela. 
userList.length>0 ? DataTable.. : showDialog gibi..

**Comment by mdizman** [comment]
Hocam bu yapı içinde nerde bu kontrol işlemini yapacağımı bulamadım. üst kısımda çekemiyorum newlist.length yapısını. Liste uzunluğunu üstteki kod satırında nerde kontrol etmem lazım.
