### ISSUE TITLE
Listview.builder remove 

### ISSUE THREAD

**Issue by Mustyy61** [VB10/vboverflow#108]
Merhabalar eşleştirme mantığına dayanan bir uygulama üzerinde çalışıyorum. Ekranımın üst kısmında eşleştirme yapacağım görseller  alt kısmında da listview.builder içindede eşleşecek görsellerin  isimleri yazmakta. Kullanıcı önce görsel ismine daha sonra görsele tıklıyor eşleşme sağlanırsa görsel ve alt kısımdaki görsel ismi kırmızıya dönüyor. Bu adımdan sonra görsel ismini bandıran  container içinde ki textin kaybolmasını istiyorum. Eşleşme olduğu taktirde  Setstate içinde eşleşme sağlanan liste elemanını remove ile silmeye çalışıyorum fakat ekranda direkt olarak yansımıyor bu durum. Bir sonraki tıklamada güncelleniyor. Araştırmalarım key kullanımını öneriyor fakat  listview.builder ile nasıl kullanacağım konusunda fikir sahibi değilim. Cevaplarınız için şimdiden çok teşekkür ederim.

**Comment by skyturkish** [comment]
kodu da paylaşır mısın

**Comment by Mustyy61** [comment]
onTap: () {
          setState(() {
            if (platoNameIndeks == widget.imageId) {
              platoNameList.remove('Bozok');
            }
});

**Comment by sinanhaci** [comment]
Yardımcı olabilmemiz için daha detaylı kod paylaşmanız gerekiyor, bu şekilde size yardımcı olmamız pek mümkün değil :)

**Comment by Mustyy61** [comment]
YENİ ÖĞRENMEYE ÇALIŞIYORUM KODUM KÖTÜ GÖZLERİNİZ KANAYA BİLİR KUSURA BAKMAYIN :)
  

@override
  Widget build(BuildContext context) {
    return SafeArea(
        child: Scaffold(
      backgroundColor: Color.fromARGB(255, 57, 185, 232),
      body: Column(children: [
        
        Stack(children: [
          Image.asset(
            "assets/gri.png",
            fit: BoxFit.cover,
            height: context.dynamicHeight(1.30),
            width: context.dynamicWidth(0.70),
          ),
          PlatoImage(
            0,
            'Bozok',
            platoImageList[0],
            context.dynamicHeight(4.8),
            context.dynamicWidth(2.86),
            context.dynamicHeight(5.5),
            context.dynamicWidth(4.9),
            bozok ? Colors.red : Colors.transparent,
          ),
          PlatoImage(
            1,
            'Catalca',
            platoImageList[1],
            context.dynamicHeight(20),
            context.dynamicWidth(9),
            context.dynamicHeight(5),
            context.dynamicWidth(4.5),
            catalca ? Colors.red : Colors.transparent,
          ),
        Padding(
          padding: EdgeInsets.only(top: context.dynamicHeight(30)),
          child: Container(
            color: Colors.transparent,
            height: context.dynamicHeight(10),
            width: context.dynamicWidth(1.5),
            child: ListView.builder(
                 shrinkWrap: true,
                scrollDirection: Axis.horizontal,
                itemCount: platoNameList.length,
                itemBuilder: (context, index) {
                 return InkWell(
                    onTap: () {
                      setState(() {
                        clickedItemPosition = index;
                        platoNameIndeks = platoNameList[index];
                      });
                    },
                    child: Container(
                      alignment: Alignment.center,
                      padding: EdgeInsets.symmetric(
                        horizontal: 20,
                      ),
                      margin: EdgeInsets.symmetric(horizontal: 10),

                      decoration: BoxDecoration(
                        borderRadius: BorderRadius.circular(15),
                        color: isChecked(index)
                            ? Colors.red
                            : Colors.deepPurpleAccent,
                        child: Text(
                        platoNameList[index],
                        style: TextStyle(
                          fontSize: 20,
                          color: Colors.white,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  );
                }),
          ),
        ),
      ]),
    ));
  }
}




class PlatoImage extends StatefulWidget {
  int number;
  String imageId;
  String imagePath;
  double top;
  double left;
  double heigth;
  double width;
  Color color;

  PlatoImage(
    this.number,
    this.imageId,
    this.imagePath,
    this.top,
    this.left,
    this.heigth,
    this.width,
    this.color,
  );

  @override
  State<PlatoImage> createState() => _PlatoImageState();
}

bool bozok = false;
bool catalca = false;


List<String> platoNameList = [
  'Bozok',
  'Catalca',
  'Cihanbeyli',
  'Erzurum',
  'Gaziantep',
  'Haymana',
  'Obruk',
  'Sanliurfa',
  'Taseli',
  'Teke',
  'Uzunyayla',
  'Yazilikaya',
];

class _PlatoImageState extends State<PlatoImage> {
  @override
  Widget build(BuildContext context) {
    return Positioned(
      top: widget.top,
      left: widget.left,
      child: InkResponse(
        splashColor: Colors.red,
        onTap: () {
          setState(() {
            if (platoNameIndeks == widget.imageId && widget.number == 0) {
              bozok = true;
              widget.color = Colors.red;
              platoNameList.remove('Bozok');
            }
            if (platoNameIndeks == widget.imageId && widget.number == 1) {
              catalca = true;
              widget.color = Colors.red;
              platoNameList.remove('Catalca');
            }           
          });
        },
        child: Image.asset(
          widget.imagePath,
          color: widget.color,
          height: widget.heigth,
          width: widget.width,
        ),
      ),
    );
  }
}
