### ISSUE TITLE
Web app hakkında görüşleriniz

### ISSUE THREAD

**Issue by ozkurtomer** [VB10/vboverflow#11]
İstanbul ve diğer şehirlerde yaşanan taksi olaylarının bir arada toplanıp bir ortak havuz oluşturma amacıyla yapmış olduğum projem mevcut. Bu proje hakkında görüş ve önerilerinize beklerim. Şimdiden teşekkürler. 
Link : www.taksipuanla.com

**Comment by VB10** [comment]
eline saglik sitede material bir kac component gordum ama 
- daha tatli bir ui tasarimi yapilabilir bunun icin upplabs tarzi siteler referans alinabilir
- sosyal medya loginler muhakkak olmali
- plaka girilen yerde bir regex olmali misal 34 numara olamak zorunda sonrasi karakter vs gibi
eline emegine saglik
