### ISSUE TITLE
Google maps custom marker

### ISSUE THREAD

**Issue by yusufkecer** [VB10/vboverflow#110]
Merhaba arkadaşlar, google mapste kişiselleştirilmiş marker göstermeye çalışıyorum kısaca amacımdan bahsedeyim;
` List<Map<String, dynamic>> userLocations = [
{"id": 0, "address_lat": 15, "address_lng": 30, "type": "home"},
{"id": 1, "address_lat": 23, "address_lng": 30, "type": "home"},
{"id": 2, "address_lat": 21, "address_lng": 30, "type": "market"},
{"id": 3, "address_lat": 16, "address_lng": 30, "type": "pharmacy"},
{"id": 4, "address_lat": 18, "address_lng": 31, "type": "market"},
{"id": 5, "address_lat": 19, "address_lng": 31.5, "type": "school"},
{"id": 6, "address_lat": 12, "address_lng": 32, "type": "school"},];

 Future createMarkerImageFromAsset() async {
if (bitmapDescriptor == null) {
  final ImageConfiguration imageConfiguration =
      createLocalImageConfiguration(context);
  final BitmapDescriptor bitmap = await BitmapDescriptor.fromAssetImage(
      imageConfiguration, "assets/home.png");//assets/school.png, assets/pharmacy.png
  setState(() {
    bitmapDescriptor = bitmap;
  });
}}`

Oluşturduğum fake datadaki enlem boylam bilgilerine göre markerın resminin değişmesini istiyorum. Bunu nasıl yapabilirim?
Teşekkürler.

**Comment by sinanhaci** [comment]
Selam,
Öncelikle asset dosyasındaki resmi BitmapDescriptor tipine dönüştürmen gerekiyor , bunun için : 
`
    var customMarker = await BitmapDescriptor.fromAssetImage(
        const ImageConfiguration(
          size: Size(100, 100),
        ),
        AssetsConstants.directionMarker);
`
Sonrasında bunu marker'ın icon kısmına set etmen gerekiyor: 
`
    marker.add(
      Marker(
          onTap: () {},
          markerId: MarkerId('i$d'),
          position: LatLng('$lat','$long'),
          icon: adsMarker),
`

Bu şekilde resimleri marker'a çevirebilirsin.
