### ISSUE TITLE
Flutter: workmanager, flutter_local_notification!

### ISSUE THREAD

**Issue by Eldar2021** [VB10/vboverflow#114]
Selamlar, uygulamamda her gün 2 kez database request gönderip, gelen response göre bildirim(notification) çıkartmam gerekir.
Sorun uygulama kapalıyken de yazdığım dart kodları çalışması gerek. Ben [workmanager](https://pub.dev/packages/workmanager) background service için ve [flutter_local_notifications](https://pub.dev/packages/flutter_local_notifications) kullandım.  Android sisteminde sıkıntısız çalışıyor İOS sisteminde sürekli problem çıkartıyor. İstediğimi Android ve İOS ikisi için de nasıl yapa bilirim?

**Comment by aea91** [comment]
Tam da burada Native katmanı devreye giriyor. IOS Native ile servis yazmanız gerek. Flutter ın bu konuda eli kolu bağlı.
