### ISSUE TITLE
Flutter AppLifeCyle Backend Servis Connection

### ISSUE THREAD

**Issue by kasapiniz** [VB10/vboverflow#116]
Merhabalar, Uygulama kapatıldığı zaman bir olay tetiklendiğinde ilgili backend servisine ulaşım nasıl yapılır. yoksa arka planda da backend hizmetlerimizi acık tutmamız mı gerekiyor.
(benim seneryom bildirim geldiğinde servisi tetiklemek istiyorum.)
Kolay gelsin.

**Comment by sinanhaci** [comment]
Selamlar yapacağın işleme göre uygulayacağın senaryo epey değişir. Bildirimlerde firebase kullanıyorsan eğer https://firebase.flutter.dev/docs/messaging/usage Buradaki "Background Messages" kısmına göz atabilirsin. Ancak dediğim gibi yapmak istediğin işlem, uygulayacağın yöntemi belirler.

**Comment by kasapiniz** [comment]
> Selamlar yapacağın işleme göre uygulayacağın senaryo epey değişir. Bildirimlerde firebase kullanıyorsan eğer https://firebase.flutter.dev/docs/messaging/usage Buradaki "Background Messages" kısmına göz atabilirsin. Ancak dediğim gibi yapmak istediğin işlem, uygulayacağın yöntemi belirler.

Yapmak istediğim işlem uygulama kapalıyken gelen bildirim üzerinden karşı kullanıcıya mesaj atmak.ben burada socket kullanıyorum. Firebasede bacground işlerimi hallediyordum ama uygulama kapalıyken connection olamıyorum. Bunu restful api ile mi iletmem gerekiyor tam anlayamadım.
