### ISSUE TITLE
Flutter için html,CSS, jsden temel gerekli mi?

### ISSUE THREAD

**Issue by pinarmusa** [VB10/vboverflow#117]
Veli hocam, ben html ve CSS çalıştım hatta JavaScript bile birazcık ilerledim ama anlamakta güçlük çekiyorum direk sizin videolarinizla yazılıma başlasam anlayabilir miyim yoksa js ve CSS de biraz daha gayret edip temelini oturtup mu başlayayım. Rahatsızlık için özür dilerim. İyi akşamlar.
@VB10 

> ``

**Comment by VB10** [comment]
selam pınar şimdi durum şöyle bence ilk başta en iyi hissetiğin yerden devam et js sardı ise oradan devam edip basit yaızılım prensiplerini çöz. bu çözümden sonra flutter tarafına geçmen çok daha hlzlı ve anlamlı gelecektir  ve bunu okuyaıblrısın
https://docs.flutter.dev/get-started/flutter-for/web-devs
