### ISSUE TITLE
Flutter projesini mac cihaz olmadan ios da debug yapma

### ISSUE THREAD

**Issue by bahadirdal** [VB10/vboverflow#12]
Windows ta Visual studio da yazdığımız uygulamayı, app store'a yüklemeden, ios ta nasıl açabiliriz, bir yolu var mıdır?

**Comment by VB10** [comment]
selamlar soyle yapiyoruz app'i bitirdik diyelim ios da debug etmek icin dogrudan macstadium tarzi bir cloud platform satin alinarak burada app indirili buraya flutter entegrasyonlari yapilarak proje run edilip cikti gorulebilir.

Ios device bu konuda sart.

**Comment by mdikcinar** [comment]
@bahadirdal Cihazına hackintosh kurabilirsin.
