### ISSUE TITLE
Database önerisi

### ISSUE THREAD

**Issue by Mustyy61** [VB10/vboverflow#120]
Merhabalar Flutterda mobil uygulama  geliştirmeye çalışıyorum. Fakat  veritabanı hakkında bilgim yok. Uygulamanın genel mantığı çoktan seçmeli test soruları ve sorulara ait görsellerden oluşacak bu verileri tutabileceğim sabit ücretli bir veritabanı öneriniz var mı ?
Konu ile ilgili araştırma yaptım fakat tatmin edici sonuçlara ulaşamadım.  Firabase ücretlerinin pahalı olacağı söyleniyor. alternatifleride bilmiyorum. Cevaplarınız için şimdiden teşekkür ederim

**Comment by abdullahkaraboga** [comment]
Uygulamadaki birim zamanda genel okuma, yazma, silme ve güncelleme rakamlarını tahmin edebilirseniz Firebase kolay, hızlı ve mantıklı olabilir.  [Buradaki](https://firebase.google.com/pricing ) sayfanın en altından hesaplama yapıp ortalama maliyeti görebilirsiniz.
