### ISSUE TITLE
DropDownField multiSelect value 

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#121]
Merhabalar. Projemde kullandığım DropDownField içinden çoklu veri seçmek istiyorum. Biraz araştırma yaptım ama çözüm bulamadım. Yardımcı olursanız sevinirim.
child: DropDownField(
                                controller: yapabilecegiSporDal,
                                    labelText: "Yapabileceği Spor Dalları",
                                    labelStyle:TextStyle(fontWeight: FontWeight.normal,fontSize: 16),
                                    itemsVisibleInDropdown: 3,
                                    enabled:true,
                                    items:sporDal,
                                    onValueChanged: (value){
                                      secilenSporDal= value;
                                      }
                                    ),
Alt kısımda oluşturduğum küçük bir listeden verilerimi dropdowndan seçip textime yazdırıyorum. Fakat amacım örneğin "Futbol","Voleybol" datalarını seçerek çekmek. 

String secilenSporDal ="";
final yapabilecegiSporDal = TextEditingController(); 
List<String> sporDal = [
  "Futbol",
  "Voleybol",
  "Basketbol",
  "Hentbol",
  "Atletizm"
];

**Comment by yagizdo** [comment]
https://youtu.be/NKIISO7mDiI Su video isinizi gorebilir diye dusunuyorum.
