### ISSUE TITLE
TextEditingController validator kontrolü

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#122]
Merhaba TextEditingController dan aldığım datayı validator ile kontrol ettirerek firebase e kaydetmek istiyorum ama hata alıyorum. Type hatası olduğunu söylüyor program ama yardımcı olabilir misiniz?

import 'package:flutter/material.dart';
class SporcuKayit extends StatefulWidget {

  @override
  _SporcuKayitState createState() => _SporcuKayitState();
}
class _SporcuKayitState extends State<SporcuKayit> {
  final _firestore = FirebaseFirestore.instance;
  TextEditingController tc = TextEditingController();
  final _formKey = GlobalKey<FormState>();
@override
  Widget build(BuildContext context) {
    CollectionReference sporcu = _firestore.collection('kullanici');
    //var ad = sporcu.doc('Futbol');
    return Scaffold(
      appBar: AppBar(
        title:const Text('Sporcu Kayıt Ekranı',
              style: TextStyle(fontSize: 14.0)),
      ),
      body: Form(
        key: _formKey,
        child: Container(
          height: MediaQuery.of(context).size.height,
          width: MediaQuery.of(context).size.width,
          child: SingleChildScrollView(
            child: Column(
              children: [
                    Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 20,vertical:20),
                      child: Form(
                        child: Card(
                          color:const Color(0xffe3f2fd),
                          ),
                          child: Container(
                            width: double.infinity,
                            margin: EdgeInsets.only(top:15),
                            child: Column(
                              children: [
                                Padding(
                                  padding: const EdgeInsets.all(7),
                                  child: TextFormField(controller:tc,decoration:const InputDecoration(
                                                                   labelText: 'Tc No:',border:OutlineInputBorder()),
                                  keyboardType: TextInputType.number,
                                  validator: (value){
                                    if(value!.isEmpty){
                                      return "Tc kimlik numarası boş bırakılamaz";
                                    }
                                    else if(value.length !=11){
                                      return "Geçerli bir Tc kimlik numarası giriniz";
                                    }
                                    else{
                                      return null;
                                    }
                                  },
                                ),
                                ),
                              ],
                            ),
                          ),
                        )
                      ),
                    ),
              ],
            ),
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child:const Text('Ekle'),
        onPressed: ()async{
          if(_formKey.currentState!.validate()){
          Map<String, dynamic> sporcuBilgileri ={
            'a_brans':brans.text,
            'b_adsoyad':adsoyad.text,
            'c_tc':tc.text,
            };
            
            await sporcu.doc(tc.text).set(sporcuBilgileri);
            
            Navigator.push(context, MaterialPageRoute(builder: (_)=>SporcuBilgi()));    
            }
          

        },),
    );
  }
}

**Comment by Barismano** [comment]
Hocam bence Column un içindeki formlara gerek yok zaten body i form ile sarmışsın birde öyle dene istersen
