### ISSUE TITLE
MultiSelectDialogField data güncelleme

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#125]
Herkese merhaba. Fikir almak istediğim bir konu var.
Projemde MultiSelectDialogField ile çoklu seçim yaparak datalarımı firebase e liste olarak kaydediyorum. Bu dataların güncelleme işlemini yapmak istiyorum. Güncelleme ekranına geldiğimde seçim yapacağımda önceden eklemiş olduğum dataları tikli olarak gösteremiyorum. Kodlarımı aşağıda paylaşacağım. Fikri olan varsa şimdiden çok teşekkür ederim.

static List<Spor> _sporlar=[
    Spor(id:1,name:"Futbol"),
    Spor(id:2,name:"Voleybol"),
    Spor(id:3,name:"Basketbol"),
    Spor(id:4,name:"Yüzme"),
    Spor(id:5,name:"Atletizm"),
    Spor(id:6,name:"Uzun mesafe koşusu"),
    Spor(id:7,name:"Uzun atlama"),
    Spor(id:8,name:"Tenis"),
  ];
  final _items = _sporlar.map((spor) => MultiSelectItem(spor, spor.name)).toList();
  List<Spor> _secilenSpor = [];
  var secilenElemanlar=[];
.
.
child:MultiSelectDialogField<Spor>(
                                items: _items,
                                title: Text("Spor Dalları"),
                                selectedColor: Colors.blue,
                                decoration: BoxDecoration(
                                  color: Colors.transparent,
                                  borderRadius: BorderRadius.all(Radius.circular(5)),
                                  border: Border.all(
                                    color: Colors.black38,
                                    width: 1,
                                  ),
                                ),
                                buttonText: Text(
                                  "Yapabileceği Spor Dalları",
                                  style: TextStyle(
                                    color: Colors.black54,
                                    fontSize: 15,
                                  ),
                                ),
                                onConfirm: (results){
                                    _secilenSpor = results ;
                                    if(results.isNotEmpty){
                                      for(int i=0;i<results.length;i++){
                                        secilenElemanlar.add(results[i].name);
                                      }
                                    }
                                },
                              )
Bu kodlar ile ekleme işlemi yapıyorum. Güncelleme ekranında da kullanacağım ama önceden seçmiş olduğum dataları da görmem lazım.

**Comment by mdizman** [comment]
initialValue kullanarak kaydettiğim dataları çekebiliyorum fakat üstüne seçim yaptığımda yada seçili elemanın seçimini kaldırdığımda ana liste üzerine aynı seçili elemanları ekliyor buna nasıl bir çözüm üretebilirim

**Comment by VB10** [comment]
bu şekilde hem kodu okumak zor hemde genel olarak ne çözüm üretmeyi burada basit kod paylaşıp komplexi muhakkak giste koymanı tavisye ederim. bu yapıda sayfada kaydettiklerini local dbde or provider gibi üst bir contexte saklayıp açıldığında sayfayı bun işlemleri çekerke yapabilrsin kolay gelsin
