### ISSUE TITLE
Android 12 Splash Screen Sorunu

### ISSUE THREAD

**Issue by sinanhaci** [VB10/vboverflow#126]
Selamlar, 

Android 12 de ayarladığım splash screenin background color'ı gözüküyor ancak icon gözükmüyor.  

Denediklerim:
build.gradle'a => implementation 'androidx.core:core-splashscreen:1.0.0-beta02' ekledim.
style.xml dosyama => windowSplashScreenAnimatedIcon alanını ekledim.

Teşekkürler

**Comment by VB10** [comment]
@sinanhaci bu konuda ben suan bir problem yaşamadım ama icon coloru xml de düzelmiştim bende bir bakayım o tarafa belki başkası görüp destek atar

**Comment by sinanhaci** [comment]
@VB10  Eğer benim gibi yapıyorsanız sizde farketmemiş olabilirsiniz ancak bazı android cihazlarda gözükmüyor koyulan icon.  Hem kodları görmeniz hemde check etmeniz için anlaşılabilir olması adına görselleri ekliyorum.

---color.xml---
![Screen Shot 2022-09-21 at 15 04 41](https://user-images.githubusercontent.com/77547319/191499204-ffd4be40-d525-454b-b233-32fa4bd7a06c.png)

---styles.xml---
![Screen Shot 2022-09-21 at 15 05 26](https://user-images.githubusercontent.com/77547319/191499333-fd513cd0-1e4d-4c20-9262-90688491c4cd.png)

---launch_background.xml---
![Screen Shot 2022-09-21 at 15 05 49](https://user-images.githubusercontent.com/77547319/191499417-a3ced91d-33f0-49e6-9172-bdd40aa6f793.png)

---AndroidManifest.xml---
![Screen Shot 2022-09-21 at 15 06 29](https://user-images.githubusercontent.com/77547319/191499544-12c2194e-6452-4cc2-89b8-20b09594f6f7.png)

**Comment by VB10** [comment]
bunu stackoverflowa flutter etiketyle carsan daha hizli cevap alirsin bende bir sorun yakalymadim
