### ISSUE TITLE
CS bölümleri dışından gelen birileri için öneri

### ISSUE THREAD

**Issue by ufuklc** [VB10/vboverflow#127]
Veli abi merhaba, ben yeni mezun inşaat mühendisiyim. Mesleğimi yapmak istemediğim için 1 yıl önce kadar veri analizine yöneldim. Python vs. çalışırken yazılımdan keyif aldığımı farkedip bilgimi ilerletmeye başladım. Geçmişten c# ve biraz java temelim var. Şimdi de hem frontend hem de backend alanında ilerlemek için js,react,angular,dotnet,c#,java tarafında kendimi geliştirmek istiyorum. Bu yola ben ve harita mühendisi bir arkadaşımla başlayacağız. Onun pek temeli yok o yüzden ben ona da yardımcı olacağım OOP ve algoritma yazma konusunda. Artık gerçek bir proje yapabilecek seviyeye gelip(bir veritabanıyla çalışan gerçek bir web sitesi tasarlamak gibi), sonrasında da mobil development'a yöneleceğiz. Bu yönde bize ne önerebilirsin abi? Sektörün içerisinden biri olarak senin yönlendirmen bizim için çok değerli olacaktır.

**Comment by VB10** [comment]
selamlar burada önemli olan noktalar şunllar

- bir çok alana hakim olmaya çalışmak güzel fakat yeni başlarken yorabilir .net or java gibi backend dillerini üstünede sql nosql gibi db yaklşaımlarını katmak güzel olabilir
- front dersen react seçerek popülertisinden ötürü ilerleyebilirsin ama yine burada önemli olan js mantığına hkaim olmak
- kuurumsalda daha native diller seçileceği içinde android öğrenmek faydalı olacaktır java backend ile bilrikte götürülebilir.
- illk nokta yine genel projelerle ama crud yada basit tododan ziyade bir business ile bağlantılı auth iç sayfalarıyla bir kaç app yapıp projelerin genel akışını öğrenmek olabilir.
kolay gelsinn

**Comment by ufuklc** [comment]
Cevapladığın için çok teşekkür ederim abi :)
