### ISSUE TITLE
https://pub.dev/packages harici referans ekleme

### ISSUE THREAD

**Issue by mehmetshakar** [VB10/vboverflow#128]
Merhabalar,

flutter projesine https://pub.dev/packages aracığıyla pubspec.yaml dosyasına referans eklemeden, mevcut başka proje klasöründen referans eklemek istiyorum. Nasıl yapabilirim? mümkün mü acaba?

teşekkürler

**Comment by sinanhaci** [comment]
Mümkün tabiki, oluşturduğun paketi public olarak kendi github hesabından da çekebilirsin veya file olarak proje içerisine atıp o şekilde de kullanabilirsin.

File olarak kullanmak için, kütüphaneyi projenin ana dosyasına at ve pubspec kısmına:
`
  paket_adi:
    path: ./paketin_pathi
`
Eğer kendi github'ından veya bir başkasının github'ından çekmek istiyorsanda:
`
  custom_image_viewer:
    git:
      url: https://github.com/sinanhaci/custom_image_viewer.git
      ref: main
`

Bu şekilde kullanabilirsin.

Örnek image: 
![Screen Shot 2022-09-26 at 16 29 55](https://user-images.githubusercontent.com/77547319/192289369-8510be1a-2a9f-4d68-a32a-b06b69de8c09.png)

**Comment by mehmetshakar** [comment]
çok teşekkür ederim, Sinan Bey.
