### ISSUE TITLE
Deep link, Universal link IOS

### ISSUE THREAD

**Issue by Eldar2021** [VB10/vboverflow#129]
Merhaba. Ben [uni_links](https://pub.dev/packages/uni_links) paketi ile çalışıyorum. Android'de iyi çalışıyor, ancak sorun IOS'ta ortaya çıktı. IOS unversal link scheme _https_ ve _http_ olduğu zaman hep safaride açılır. Documanlara baktım [doc](https://developer.apple.com/library/archive/documentation/General/Conceptual/AppSearch/UniversalLinks.html) ve documana göre **_apple-app-site-association_** dosyayı nerede oluşturup ve nereye yükleyeceğimi bilmiyorum.

**Comment by VB10** [comment]
bunu websitene yuklemen gerekiyor index rootuna. bu dosyayi elle olusturup  https://gist.github.com/mat/e35393e9dfd9d7fb0972 buradaki ornekteki gibi yapabilirsin

**Comment by Eldar2021** [comment]
Teşekkür ederim aradığım tam buydu.
