### ISSUE TITLE
(Swift) Firebase+Github yetkilendirmede fonksiyonunu nasıl çağırabiliriz. Webview

### ISSUE THREAD

**Issue by MehmetKaranlik** [VB10/vboverflow#13]
Firebase üzerinden github login eklemeye çalışıyorum side projeme.
Github logini WKWebView ile açıyorum. Fakat firebase'in fonksiyonunu nasıl handle edebilirim ? 

<img width="1110" alt="Ekran Resmi 2022-06-15 17 26 44" src="https://user-images.githubusercontent.com/89414084/173852539-bdc16d0e-5063-4c0b-a444-14c2a405d1d8.png">

Ekran yukarıda ki gibi. Firebase dökümanına göre;

````swift
    var provider = OAuthProvider(providerID: "github.com")

    provider.getCredentialWith(nil) { credential, error in
      if error != nil {
        // Handle error.
      }
      if credential != nil {
        Auth().signIn(with: credential) { authResult, error in
          if error != nil {
            // Handle error.
          }
          // User is signed in.
          // IdP data available in authResult.additionalUserInfo.profile.

          guard let oauthCredential = authResult.credential as? OAuthCredential else { return }
          // GitHub OAuth access token can also be retrieved by:
          // oauthCredential.accessToken
          // GitHub OAuth ID token can be retrieved by calling:
          // oauthCredential.idToken
        }
      }
    }
    

````
Bu fonksiyonu hangi eventte handle edebilirim.

**Comment by VB10** [comment]
bu soruyu  glitch firebase repolarina acsan daha iyi cevaplar alirsin ben sorunu anlamadim burada ama yine soylemis olayim firebase vs degil webview uzeirnde script atarak webview cookie vs okuma yapman lazim ardindan dogru cevabi gorunce webview kapatip yapaiblrisn
