### ISSUE TITLE
ListView.builder [index]

### ISSUE THREAD

**Issue by hakandl** [VB10/vboverflow#130]
merhaba, listview.builder içinde API'den gelen veriler listeleniyor, gelen veri birden fazlaysa [index] verildiginde normal sekilde sorunsuz calisiyor. ama gelen veri tek elemanli veriyse RangeError hatası veriyor. birkac yol denedim fakat tam olarak istedigim sonucu vermedi, bu konuyla ilgili fikriniz varsa paylasabilir misiniz?
<img width="528" alt="listview" src="https://user-images.githubusercontent.com/76874178/192615716-8200bc10-7c8e-4e01-ba05-81de50cef0bd.png">

**Comment by VB10** [comment]
tek elemanli ise index tektir zaten burada baska bir lsite degeri set edilmis gozden kacan basit bir hata var duruyor gelen cevaba bakmak debug etmek lazim
