### ISSUE TITLE
Singleton - Static Methods

### ISSUE THREAD

**Issue by themumy10** [VB10/vboverflow#131]
Hocam merhaba. Örnek vererek sorumu açıklamak istiyorum. Örneğin bir hesap makinesi yapmak istiyorum ve hesaplama işlemleri ile ilgili tüm fonksiyonları(çarpma, bölme vs) bir sınıfta tutmak istiyorum. Bu sınıfı singleton patern ile hazırlayarak abstract olarak bir üst sınıf yazmak mı daha doğru yoksa sınıfı yine abstract olarak yaparak fonksiyonları statik yazıp singleton yapmamak mı daha doğru olur? Yani memory ve kod yapısı olarak hangisi daha sağlıklıdır? Çok teşekkürler şimdiden.

**Comment by VB10** [comment]
singleton yapmak diye bir esy yok aslinda projelerde bu kullanim her zaman sorun cikartaiblir 
https://www.oreilly.com/library/view/essential-actionscript-30/0596526946/ch04.html

Burada yapman gereken bir soyut sinifla methodalrini tanitipp uzerinden bundan tureyen classlar yapmak singleton yapmana gerek yok ihtiyaci olan sinifi kullanir ve isi bitince dispose eder buda performasn saglar.

**Comment by themumy10** [comment]
Teşekkürler hocam
