### ISSUE TITLE
Seçili ve seçili olmayan RadioButtonListTile durumuna göre Renk Değişimi

### ISSUE THREAD

**Issue by abdullahtas0** [VB10/vboverflow#133]
Herkese selamlar. Card widgetine child olarak radiobuttonlisttile verdim. Bu radioyu değiştirebiliyorum seçili hale getirebiliyorum ancak bir sorunum var. 
Verilerini Sqlite ile aldığım yapımda istediğim şey; Seçtiğim radiobuttona göre card widgetinin rengini değiştirmek. Yani 5 card widgetim varsa bunlardan seçili olan radionun card rengi turuncu seçili olmayanların ise beyaz olmasını istiyorum. Umarım sorunumu anlatabilmişimdir.

KODLARIM;

```
  FutureBuilder(
            future: controller.dbHelper!.getCreditCards(),
            builder: (BuildContext context,
                AsyncSnapshot<List<CreditCard>> snapshot) {
              if (!snapshot.hasData) return const CircularProgressIndicator();
              if (snapshot.data!.isEmpty) {
                return const Text("Your contact list empty");
              }
              return ListView.builder(
                  shrinkWrap: true,
                  padding: EdgeInsets.zero,
                  itemCount: snapshot.data!.length,
                  itemBuilder: (BuildContext context, int index) {
                    CreditCard cards = snapshot.data![index];
                    return Card(
                      color: Colors.orange,
                      child: Theme(
                        data: ThemeData(unselectedWidgetColor: Colors.grey),
                        child: RadioListTile<int>(
                          value: index,
                          groupValue: controller.selectedValue,
                          activeColor: Colors.orange,
                          title: Text(cards.cardNumber!
                              .replaceAll(RegExp(r'[^\s](?=.{4})'), '*')),
                          onChanged: (value) {
                            controller.selectedRadio(value);
                          },
                        ),
                      ),
                    );
                  });
            },
          ),
```

MODELİM;

```
class CreditCard {
  int? id;
  String? cardHolder;
  String? cardNumber;
  String? cardExpriyDate;
  String? cardCvv;

  CreditCard({
    this.cardHolder,
    this.cardNumber,
    this.cardExpriyDate,
    this.cardCvv,
  });

  Map<String, dynamic> toMap() {
    var map = Map<String, dynamic>();
    map["cardHolder"] = cardHolder;
    map["cardNumber"] = cardNumber;
    map["cardExpriyDate"] = cardExpriyDate;
    map["cardCvv"] = cardCvv;
    return map;
  }

  CreditCard.fromMap(Map<String, dynamic> map) {
    id = map["id"];
    cardHolder = map["cardHolder"];
    cardNumber = map["cardNumber"];
    cardExpriyDate = map["cardExpriyDate"];
  }
}
```

**Comment by MuhammedKpln** [comment]
Öncelikle radio degerini(veya o rengi verebilecek herhangi bir seyi) databaseden saklaman lazim. Bir enum olusturmani öneririm, enum icerisinde color degerlerini saklayip veriyi cektikten sonra bunu parselayip card activeColor degerine atayabilirsin. Daha temiz bir kod elde edebilirsin bu sekilde.


```
enum RadioColors{
  color(Color(0xFF)),
  anotherColor(Color(0xFF));

  final Color color;

  const RadioColors(this.color);
}
```

Modelinizi bu enuma göre olusturursaniz parse ettikten sonra yapmaniz gereken sey ```model.radio.color``` olarak kullanmaniz. Umarim sorunuzu yanlis anlamamisimdir :)

Gelen veriyi ``` value is RadioColors ? value.color : Colors.white``` olarak kullanabilirsin, null gelirse beyaz gösterirsin.

**Comment by abdullahtas0** [comment]
> Öncelikle radio degerini(veya o rengi verebilecek herhangi bir seyi) databaseden saklaman lazim. Bir enum olusturmani öneririm, enum icerisinde color degerlerini saklayip veriyi cektikten sonra bunu parselayip card activeColor degerine atayabilirsin. Daha temiz bir kod elde edebilirsin bu sekilde.
> 
> ```
> enum RadioColors{
>   color(Color(0xFF)),
>   anotherColor(Color(0xFF));
> 
>   final Color color;
> 
>   const RadioColors(this.color);
> }
> ```
> 
> Modelinizi bu enuma göre olusturursaniz parse ettikten sonra yapmaniz gereken sey `model.radio.color` olarak kullanmaniz. Umarim sorunuzu yanlis anlamamisimdir :)
> 
> Gelen veriyi ` value is RadioColors ? value.color : Colors.white` olarak kullanabilirsin, null gelirse beyaz gösterirsin.

Öncelikle çok teşekkür ederim kıymetli vaktinizi ayırıp yanıtladınız için. Esasında ben bool değer tutabilseydi selected parametresini db'de tutup ona göre işlem yaptıracaktım. Bu yazdığınız cevap mantıklı bir hareket olabilir ama ben biraz garip ve belkide bir mantığı olmayan bir yolla çözmeye çalışıyorum :) şöyleki seçilen index ile value eşit değil ise yani şöyle;
```

  controller.selectedValue == index
                                    ? Colors.white
                                    : Colors.orange,
```
bunu izah edemem ama çalışıyor :D seçtiğim turuncu seçmediğim beyaz oluyor :D 
Adam etmeye çalışacağım ama kodlarımı. Tekrardan teşekkür ederim :D

**Comment by MuhammedKpln** [comment]
> > Öncelikle radio degerini(veya o rengi verebilecek herhangi bir seyi) databaseden saklaman lazim. Bir enum olusturmani öneririm, enum icerisinde color degerlerini saklayip veriyi cektikten sonra bunu parselayip card activeColor degerine atayabilirsin. Daha temiz bir kod elde edebilirsin bu sekilde.
> > ```
> > enum RadioColors{
> >   color(Color(0xFF)),
> >   anotherColor(Color(0xFF));
> > 
> >   final Color color;
> > 
> >   const RadioColors(this.color);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Modelinizi bu enuma göre olusturursaniz parse ettikten sonra yapmaniz gereken sey `model.radio.color` olarak kullanmaniz. Umarim sorunuzu yanlis anlamamisimdir :)
> > Gelen veriyi ` value is RadioColors ? value.color : Colors.white` olarak kullanabilirsin, null gelirse beyaz gösterirsin.
> 
> Öncelikle çok teşekkür ederim kıymetli vaktinizi ayırıp yanıtladınız için. Esasında ben bool değer tutabilseydi selected parametresini db'de tutup ona göre işlem yaptıracaktım. Bu yazdığınız cevap mantıklı bir hareket olabilir ama ben biraz garip ve belkide bir mantığı olmayan bir yolla çözmeye çalışıyorum :) şöyleki seçilen index ile value eşit değil ise yani şöyle;
> 
> ```
> 
>   controller.selectedValue == index
>                                     ? Colors.white
>                                     : Colors.orange,
> ```
> 
> bunu izah edemem ama çalışıyor :D seçtiğim turuncu seçmediğim beyaz oluyor :D Adam etmeye çalışacağım ama kodlarımı. Tekrardan teşekkür ederim :D

Önemli olan çalışması, it's not a bug it's a feature! :D Tabiki önemli olan sonraında şuan ki yaptığınız çözümün üzerine koyarak devam etmek.

**Comment by abdullahtas0** [comment]
> > > Öncelikle radio degerini(veya o rengi verebilecek herhangi bir seyi) databaseden saklaman lazim. Bir enum olusturmani öneririm, enum icerisinde color degerlerini saklayip veriyi cektikten sonra bunu parselayip card activeColor degerine atayabilirsin. Daha temiz bir kod elde edebilirsin bu sekilde.
> > > ```
> > > enum RadioColors{
> > >   color(Color(0xFF)),
> > >   anotherColor(Color(0xFF));
> > > 
> > >   final Color color;
> > > 
> > >   const RadioColors(this.color);
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Modelinizi bu enuma göre olusturursaniz parse ettikten sonra yapmaniz gereken sey `model.radio.color` olarak kullanmaniz. Umarim sorunuzu yanlis anlamamisimdir :)
> > > Gelen veriyi ` value is RadioColors ? value.color : Colors.white` olarak kullanabilirsin, null gelirse beyaz gösterirsin.
> > 
> > 
> > Öncelikle çok teşekkür ederim kıymetli vaktinizi ayırıp yanıtladınız için. Esasında ben bool değer tutabilseydi selected parametresini db'de tutup ona göre işlem yaptıracaktım. Bu yazdığınız cevap mantıklı bir hareket olabilir ama ben biraz garip ve belkide bir mantığı olmayan bir yolla çözmeye çalışıyorum :) şöyleki seçilen index ile value eşit değil ise yani şöyle;
> > ```
> > 
> >   controller.selectedValue == index
> >                                     ? Colors.white
> >                                     : Colors.orange,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > bunu izah edemem ama çalışıyor :D seçtiğim turuncu seçmediğim beyaz oluyor :D Adam etmeye çalışacağım ama kodlarımı. Tekrardan teşekkür ederim :D
> 
> Önemli olan çalışması, it's not a bug it's a feature! :D Tabiki önemli olan sonraında şuan ki yaptığınız çözümün üzerine koyarak devam etmek.

Hocam nazar değdi :D Sorun şu; 3 adet kart listeleniyor ekranda. İlki seçili olarak geliyor ancak ikinci kartı seçtiğimde artık ilk kartı bir daha seçemiyorum 2. ve 3. kartların arasında geçiş yapabiliyorum seçebiliyorum ancak ilk kartı seçemiyorum onchange vs içerisine girmiyor tepki vermiyor :S bunu anlayamadım kodun son hali;

```
 FutureBuilder(
            future: controller.dbHelper!.getCreditCards(),
            builder: (BuildContext context,
                AsyncSnapshot<List<CreditCard>> snapshot) {
              if (!snapshot.hasData) return const CircularProgressIndicator();
              if (snapshot.data!.isEmpty) {
                return const Text("Your contact list empty");
              }
              return ListView.builder(
                  shrinkWrap: true,
                  padding: EdgeInsets.zero,
                  itemCount: snapshot.data!.length,
                  itemBuilder: (BuildContext context, int index) {
                    CreditCard creditCard = snapshot.data![index];
                    return Padding(
                      padding: AppPadding.guideLine,
                      child: Card(
                        color: controller.selectedCardValue.value == index
                            ? Colors.orange
                            : Colors.white,
                        child: Theme(
                          data: ThemeData(
                            unselectedWidgetColor:
                                controller.selectedCardValue.value == index
                                    ? Colors.white
                                    : Colors.orange,
                          ),
                          child: RadioListTile<int>(
                            toggleable: true,
                            value: index,
                            groupValue: controller.selectedCardValue.value,
                            activeColor: Colors.white,
                            title: Text(
                              snapshot.data![index].cardNumber!
                                  .replaceAll(RegExp(r'[^\s](?=.{4})'), '*'),
                              style: appTextStyle.getCreditCardFont_Size16(
                                controller.selectedCardValue.value == index
                                    ? Colors.white
                                    : Colors.grey,
                              ),
                            ),
                            onChanged: (value) {
                              try {
                                if (value != null) {
                                  controller.selectedCardValue.value = value!;
                                  controller.update();
                                  print(controller.selectedCardValue.value);
                                  print(value);
                                  print(controller.selectedCardValue.value);
                                }
                              } catch (e) {
                                print(e);
                              }
                            },
                          ),
                        ),
                      ),
                    );
                  });
            },
          ),
```

**Comment by MuhammedKpln** [comment]
Controller'i ve state yapisini gorebilir miyim

**Comment by abdullahtas0** [comment]
> Controller'i ve state yapisini gorebilir miyim

Hocam ios emülatörde çalışmıyor bilmiyorum emülatörün sorunu ama gerçek bir android cihazda mükemmel şekilde çalışıyor. Çok teşekkür ederim sizide yordum yardımlarınız ve tavsiyeleriniz için çok teşekkür ederim
