### ISSUE TITLE
maps ve list hakkında bir soru

### ISSUE THREAD

**Issue by ysmltr** [VB10/vboverflow#134]
veli abi selam rahatsiz ettigim icin ozur dilerim ama bir problemim var
void main(List<String> args) {
  Map<String, String> foodCalories = {
    'americano': '15kj',
    'cookie': '125kj',
  };

  foodCalories['latte'] = '223kj';
  foodCalories['fresh-filter-coffee'] = '12kj';
  print(foodCalories);

  /*print(students[0]+',your calorie is,'+foodCalories.keys.elementAt(0)+': '+ foodCalories.values.elementAt(0));
  print(students[1]+',your calorie is,'+foodCalories.keys.elementAt(1)+': '+ foodCalories.values.elementAt(1));
  print(students[2]+',your calorie is,'+foodCalories.keys.elementAt(2)+': '+ foodCalories.values.elementAt(2));
  print(students[3]+',your calorie is,'+foodCalories.keys.elementAt(3)+': '+ foodCalories.values.elementAt(3));*/

   List students = ['alicia', 'kenan', 'dennis', 'theo'];   
  for (var i in students) {
    print('hi! $i'+' your calorie of food or drinks: '); foodCalories.forEach((key, value)=> print("$key and $value")); 
    
    }
  }
 

mesela liste icindeki her bir kullaniciya karsilik icctigi icecegin kalorisini gosteren bir kod yazmak istedim ama bir turlu maps icinde birebir eslesme yapamadim

amacim soyle bir cikti almakti

alicia  your calorie is americano,15
gibi bir cikti almak istedim 

eger yardimci olabilirsen cok sevinecegim

**Comment by MuhammedKpln** [comment]
Students bir liste olarak vermissin dolayisiyla hangi kullanici tam olarak ne ictigini belirtmemissin. Onun yerine map kullanarak kullanicinin ictigi yemegi veya icecegi yaziyosun, dolayisiyla kullanicinin ne ictigini biliyoruz geriye kalan tek sey onun kalori karsiligini almak. Allttaki kodun cikintisina göz atabilirsin. 

```
Hi 15kj your calorie of food or drinks
Hi 125kj your calorie of food or drinks
```

```dart

void main(List<String> args) {
  Map<String, String> foodCalories = {
    'americano': '15kj',
    'cookie': '125kj',
  };

  Map<String, String> students = {
    'ahmet': 'americano',
    'mehmet': 'cookie',
  };

  students.forEach((key, value) {
    // Kullanicinin icecegi foodCalories'te varmi yok mu kontrol ediyoruz
    if (foodCalories.containsKey(value)) {
      // Mevcut ise value degerini kullanarak kalori karsiligini aliyourz
      final calorie = foodCalories[value];

      // En sonunda da yazdiriyoruz.
      print('Hi $key! $calorie is your calorie of food or drinks');
    }
  });
}
 ```

**Comment by ysmltr** [comment]
teşekkür ederim

**Comment by VB10** [comment]
@MuhammedKpln supersin
