### ISSUE TITLE
Dosya çok uzadıysa "part, part of" ile ayırmak mantıklı mı ?  

### ISSUE THREAD

**Issue by skyturkish** [VB10/vboverflow#135]
https://stackoverflow.com/questions/73972393/what-we-should-do-when-the-file-gets-so-long

**Comment by MuhammedKpln** [comment]
Kullanilabilir tabiki fakat sahsen ben önermiyorum. Onun yerine dosya cok uzadiysa MVC/MVC-S  yapisina gecis yapmaniz daha mantikli olucaktir, bu sayede servisleriniz, kontrolleriniz, ve ui elementleriniz kendilerine has bir class'ta olduklarindan dolayi kod hem cok okunakli hem de her dosya/class kendi islevini görur dolayisiyla gelistirmesini daha kolaylastirir.

**Comment by skyturkish** [comment]
her sayfayı viewmodel ve view diye ayırıp parçalıyorum, servislerim genel oldukları için ayrı bir servis klasörünün altında, modellerimde bir çok sayfada kullanıldığı için onlarda ayrı bir models/ altında, Buna rağmen deneme_view.dart klasöründe, daha iyi okunabilmesi extract widget yaptığım zaman sayfa büyüyor, buna çözüm olarak dediğiniz şeylerin bağlantısını kuramadım. Attığım linkteki kodda initstate,,dispose,function ve değerler viewmodele alındı. Okunmasında da problem yok sadece dosya biraz uzun geliyor gibi, pek doğru hissetmiyor. view dosyasında sadece view elemanları olduğu halde, Theme'den falan okuyorum, gereksiz kod yok 150 satır çok değil ama vardır daha iyi yolu diye soruyorum.

**Comment by MuhammedKpln** [comment]
Aslinda kodda gördugum uzere o kadarda fazla bir kod satiri yok, dosyalama islemleri ile beraber cok temiz ve okunakli bir kod var önumde.

- ProductState enum'unu kendine has bir dosyaya veya enumlari tuttugun bir dosyada sakliyabilirsin
- Tum widgetlari parcalamissiniz, bu widgetlari kendine özel bir dosyada tutabilirsiniz, ha derseniz ki bunlar bu sayfaya özel widget o zaman sayfa altinda components adli bir klasör olusturup bunlari orada tek tek tutabilirsiniz
- MVC önermemin sebebi View ve diger bussines logic birbirinden ayri tutmaniz, yani controller adi altinda bir class olusturup tum filtreleme, servisten okuma vs vs orda yapip bunu state yardimi ile view widgetine aktarmak.


- Bu tarzda callbackleri controllerida yapabilirsiniz veya ayni class icerisinde parcalarsaniz daha okunakli bir view elde etmis olursunuz.
```dart

 items: ProductState.values
  .map<DropdownMenuItem<ProductState>>(
    (value) => DropdownMenuItem<ProductState>(
      value: value,
      child: Text(value.name),
    ),
  )
  .toList(),
```


```dart
     onPressed: () {
        if (formKey.currentState!.validate()) {
          context.read<ProductNotifier>().setProduct(
                title: titleController.text,
                state: stateController.text,
                description: describeController.text,
              );
          NavigationService.instance.navigateToPage(path: NavigationConstants.UPLOAD_PHOTOS);
        }
      },
```

**Comment by skyturkish** [comment]
Tamam şimdi anladım tam olarak controller mantığını, teşekkürler. bunları da controller'a alırsak, kod muck oluyor tadından yenmiyor.

**Comment by VB10** [comment]
supersiniz
