### ISSUE TITLE
REQUEST_INSTALL_PACKAGES permission sorunu

### ISSUE THREAD

**Issue by safauludogan** [VB10/vboverflow#136]
"Uygulamanızın, REQUEST_INSTALL_PACKAGES izninin meşru kullanım alanlarına uygun olmadığı tespit edildi. Daha açık belirtecek olursak iznin kullanımı, uygulamanın temel amacı ile doğrudan ilişkili değil." Güncelleme yayınladığım zaman play_console'dan bu uyarıyı alıyorum ve güncelleme yayınlayamıyorum. İnternetten araştırma yaptığımda open_file paketinin bu izni otomatik kullandığını fark ettim fakat bu paketi silmeme rağmen ve bu izni hiçbir yerde kullanmama rağmen hâlâ güncelleme attığım zaman yukarıdaki uyarıyı alıyorum. Bu konuda yardımcı olabilir misiniz?

Play store uyarısı ve manifest dosyam:
![1](https://user-images.githubusercontent.com/57045839/194512616-492aecd0-5ad3-44b3-a0dd-9436d508e443.jpg)
![2](https://user-images.githubusercontent.com/57045839/194512637-66f6af2e-2540-4ab3-b233-714d36f59f9e.jpg)

**Comment by MuhammedKpln** [comment]
`flutter clean` be gradlew cachelerini sifirlamayi yaptiktan sonra tekrar build etmeyi denediniz mi?

**Comment by safauludogan** [comment]
> `flutter clean` be gradlew cachelerini sifirlamayi yaptiktan sonra tekrar build etmeyi denediniz mi?

Evet hepsini denedim. Kütüphaneyi komple sildim ama yine aynı reddi yiyorum.

**Comment by safauludogan** [comment]
Kapalı testteki uygulamaları da güncelleyerek sorunu çözdüm.
