### ISSUE TITLE
Routing Hakkında

### ISSUE THREAD

**Issue by mysCod3r** [VB10/vboverflow#137]
Herkese merhaba,
Bir app üzerinde çalışıyorum. Navigation bar da 4 sekme mevcut. Her sekmede başka sayfalara geçiş var. 
Örneğin twitter üzerinden anlatmam gerekirse;
Home sekmesinden birinin profiline girdiğimiz zaman bildirim sekmesine geçip tekrar home ekranına dönünce kaldığımız yerden devam ediyor. Benim app de ise profilden çıkıp tekrar anasayfaya dönüyor. Uygulamanın kaldığı state i nasıl koruyabilirim?

**Comment by skyturkish** [comment]
https://api.flutter.dev/flutter/widgets/IndexedStack-class.html     => bu bottomnavigation bar için 

AutomaticKeepAliveClientMixin  => bu da herhangi bir sayfanın state'ini saklaman için

**Comment by MehmetKaranlik** [comment]
Ben pek indexed stacki tercih etmiyorum, tabdeki bütün sayfalrı table beraber initialize ediyor. Onun yerine tabi pageview.builder ile kurup childları da AutomaticKeepAliveClientMixin ile  inherit edip, statelerini korumak daha tatlı benim için. Tab barı da korumak istiyorsan nested navigasyon yöntemlerini inceleyebilirsin. Bkz: auto_router

**Comment by skyturkish** [comment]
bu daha mantıklıymış, ben de benimkini böyle yapayım bundan sonra.
