### ISSUE TITLE
auto_route paketi ile bottom navigation bar

### ISSUE THREAD

**Issue by mysCod3r** [VB10/vboverflow#138]
#137 burdan yola çıkarak projeyi auto_route ile yapmaya başladım.

Twitterda bildirimler sekmesinden tweet detaylarına ordan kullanıcı profillerine rahatça gezinebiliyoruz. Ve bu gezinmeleri yaparken bottom nav bar değişmiyor. Bildirimler sekmesinde kalmaya devam ediyor.

Benim denemelerimde ise bunu başaramadım. bildirimler sekmesinden tweet detaya geçince, bottom nav bar da tweet_detay hangi sekme için tanımlanmışsa o sekmeye geçiyor. Bottom nav bar itemlerinin dışında yeni bir AutoRoot ekleyince de tab bar kayboluyor.

Stackoverflow:
https://stackoverflow.com/questions/74009952/how-to-do-navigating-without-doing-not-change-tab-bar-using-auto-router

**Comment by VB10** [comment]
@mysCod3r kanalda analatimstim bu videonun son kisminda ona bakarsin
https://www.youtube.com/watch?v=QGzVuzjXw2k
