### ISSUE TITLE
Flutter işler hakkında ve muhendislik

### ISSUE THREAD

**Issue by teomankaratas** [VB10/vboverflow#14]
Veli hocam merhaba , sizin yayınladığınız işlere üniversite terk olarak başvuru yapılabilir mi ? Bitiremeyeceğim gibi duruyor bölümümden hiç memnun değilim (çevre mühendisliği)her sınav zamanı yaklaştığında  açıp daha azimli şekilde flutter çalışıyorum dersler yerine . B2 ingilizce var erasmus yaptım 4 ay portekizde yabancı kaynaklardan çoğu zaman çalışıyorum sizin videolarınız dışında .Bu arada flutter beta sürümünden beri uğraşıyorum aralıklı olarak ama motivasyonum düşüyor hep işler yarım kalıyor bu konuda öneriniz var mı ?

**Comment by VB10** [comment]
Benim ek olarak yaptığım işler genelde freelance kafasında oluyor orada bir mezuniyet vs aranmıyor ama sektorde kurumsal firmalarda mühendislik şartı var.

Burada bir çok arkadaş upworks tarzı sitelerde kendini yönlendiriyor motviasyon düşmesi çok normal iş bulmadığın için ama o zamana kadar public yazılar makeleler yapıp linkedinde güncel bir profille savaşına devam edebilirsin

Unutma ronaldo bugünlere gelmek için kaç bin mekik çekti biz sadece golleri görüyoruz ondan çalışmaya doğru ana kadar devam.
