### ISSUE TITLE
List [ index ] sorunu.

### ISSUE THREAD

**Issue by Mustyy61** [VB10/vboverflow#142]
Merhalar Listemteki verileri Text widgetine çekmek istiyorum. Listname[index] kullanımında index'i alamıyorum hata veriyor . Ne yapmam gerekiyor ?

**Comment by tolgasozbir** [comment]
Yazdığınız kodu paylaşabilir misiniz

**Comment by VB10** [comment]
burada bir sorun yok gibi listviewbuilder ile yaparsan sorun kalmaz
