### ISSUE TITLE
Textfield klavye kapatma

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#143]
Merhabalar. Yapmış olduğum projede textfield a başlangıçta autoFocus özelliği veriyorum. Ama bu textfield için klavyeye ihtiyacım yok dataları kameradan çekiyorum zaten. Acaba Textfield ın klavyesini nasıl kapatabilirim ?

**Comment by mdizman** [comment]
Sorumu şu şekilde düzenlemek istiyorum. keyboardType: TextInputType.none ile klavyeyi kapatabiliyorum ama bu sefer textfield işlevini kaybediyor. Kameradan aldığım datayı da içine yazamıyorum. Klavyeyi tamamen kapatmak yerine gizlemek gibi bir fonksiyonumuz var mı acaba?

**Comment by tolgasozbir** [comment]
Merhaba. Öncelikle umarım doğru anlamışımdır, TextField'inize TextEditingController verip kameradan okuğunuz değeri controller.text'e atama yapabilirsiniz, bu sayede aldığınız data TextField'in içine girilmiş olacak. Başlangıçta autoFocus vermek zorunda mısınız bilmiyorum fakat TextField'in onTap parametresini kullanarak bu işlemi yapabilirsiniz.

Örnek kod.

```dart

final TextEditingController _controller = TextEditingController();

TextField(
  controller: _controller,
  onTap: (){
    //...
    //Kamera açma değer okuma kodları
    //...
    setState(() {
      _controller.text = kameradanGelenValue;
    });
  },
),
```

**Comment by VB10** [comment]
bu konuda bir bilgim yok native taraf bakmak lazim
