### ISSUE TITLE
Firebase iOS verifying you're not a robot ekranı kaldırma

### ISSUE THREAD

**Issue by burakJs** [VB10/vboverflow#145]
Flutter Firebase telefon numarası ile giriş yapmaya çalışıyorum fakat verifying you're not a robot ekranına zorunlu yönlendirme oluyor her zaman. Bunu nasıl kaldırabilirim ? 

<img src=https://user-images.githubusercontent.com/70351342/197723915-2f3d8acb-6e82-4841-8dd7-9c0276d9e92c.png width=200>

**Comment by burakJs** [comment]
`await auth.setSettings(forceRecaptchaFlow: false);`
Bu kod sayesinde sorun çözüldü

**Comment by burakJs** [comment]
Uygulamayı silip tekrar yükleyince aynı sayfa gelmeye devam etti

**Comment by VB10** [comment]
@burakJs bunu stackoverlowa acmani tavsiy ederim
