### ISSUE TITLE
Extension ve Basescreen

### ISSUE THREAD

**Issue by kadirozenn** [VB10/vboverflow#146]
<img width="703" alt="Screen Shot 2022-10-28 at 15 12 43" src="https://user-images.githubusercontent.com/50986996/198586223-dd5bfe90-2303-48d4-83c4-0e37a517c5f4.png">

Resimdeki yuvarlak içine aldığım SizedBox kullanım şekline göre bir farklılığı var mı, varsa hangi yöntemi kullansam daha sağlıklı olur ?

**Comment by tolgasozbir** [comment]
extension olarak kullanman daha doğru olur bence. Her seferinde sizedbox tanımlamak yerine extension'da tanımlayıp diğer sayfalarına da oradan çağırırsın.

**Comment by kadirozenn** [comment]
Cevabın için teşekkür ederim. Ama ben SizedBox BaseScreen classında  bi kere tanımlayıp hep ordan çağırıyorum

**Comment by VB10** [comment]
@kadirozenn burada yapman gerek en dogursu kendi sizedbox clasini olsuturup bunlari const isareletemek

class x extends sizedbox{
	x.super(height:10)
	}

**Comment by kadirozenn** [comment]
Teşekkür ederim hocam
