### ISSUE TITLE
Background task IOS platform

### ISSUE THREAD

**Issue by Eldar2021** [VB10/vboverflow#147]
Uygulama arka planda çalışmıyorsa bile her gün iki kez servere request gönderip gelen responsu notification olarak göstermesi gerekir. [Workmanager](https://pub.dev/packages/workmanager) paketi ile Android sisteminde çalıştı. Sorun Bu paket IOS sisteminde `registerPeriodicTask` methodunu desteklenmemesidir. Bu sorunu Flutter ile yada Swift ile nasıl çöze bilirim? Swift ile hiç tecrübem olmadığı için yardıma ve yönlendirmeye ihtiyacım var. Herkese şimdiden teşekkürler.

**Comment by VB10** [comment]
@Eldar2021 bu workmanager ios tarafinda zaten net olarak 3h de bir tetiklenir gibi bir seeyden bahsetmiyor aslinda dokumanini okursan da gorursun. burada bu workmanagerin verdigi disinda native dahil etsen ayni seyi yasayaiblrisin burada yapilabiecek cozum slient notifcation atip belirli araliklara telefonun icinde kod calistirmak buna deneyelbirsin

**Comment by aea91** [comment]
> @Eldar2021 bu workmanager ios tarafinda zaten net olarak 3h de bir tetiklenir gibi bir seeyden bahsetmiyor aslinda dokumanini okursan da gorursun. burada bu workmanagerin verdigi disinda native dahil etsen ayni seyi yasayaiblrisin burada yapilabiecek cozum slient notifcation atip belirli araliklara telefonun icinde kod calistirmak buna deneyelbirsin

IOS bilgisi az olanlar için Silence notification handle etmek için kod parçacığını nereye yazacağız örnek varsa paylaşabilir misiniz?
