### ISSUE TITLE
Xcode upgrade sonrası eski iOS version simulator'de nasıl çalıştırırım?

### ISSUE THREAD

**Issue by hendeseicode** [VB10/vboverflow#148]
Xcode 14.1 yükseltmemle birlikte oluşturabileceğim min simulator OS version 13.7 oldu, uygulamamı OS version 11de kullanan cihazlar var, nasıl OS Version 11 bir cihaz oluşturabilirim Xcode'da?

**Comment by VB10** [comment]
xcode sag uste prefences oradana platforma basip + tusuyla eski versyonlar yukleyip kullanabilirsin
<img width="942" alt="image" src="https://user-images.githubusercontent.com/17102578/200661113-4516e182-29e5-4ebf-bef3-8a95d81fc77d.png">

**Comment by hendeseicode** [comment]
iOS Version 13.7'den başlıyor ve iOS version 11'de test etmem gerekiyor. Örneğin iOS Version 11'de bir iPphone 8 plus simulator nasıl çalıştırabilirim?

**Comment by VB10** [comment]
+ butotuna basinca gelecek o eskiler 
<img width="816" alt="image" src="https://user-images.githubusercontent.com/17102578/200667857-baa4bb68-28a3-4519-99ed-5c639bf767bf.png">

**Comment by hendeseicode** [comment]
<img width="409" alt="image" src="https://user-images.githubusercontent.com/29240246/200745876-5c3bd2e6-3c1a-438c-a465-b71420c08049.png">

En düşük 13.7 izin veriyor
Ventura 13
XCode 14.1
