### ISSUE TITLE
Sertifika veren online eğitimler hakkında

### ISSUE THREAD

**Issue by erenkali** [VB10/vboverflow#15]
Makine Mühendisliği öğrencisiyim ama kendimi yazılım sektöründe geliştirmek, ekmeğini yemek istiyorum bunun için de https://www.kampus365.com sitesindeki eğitimler ve karşılığında verilen sertifikaların olduğu programlarla karşılaştım. Bu tarz sertifika veren eğitimleri önerir misiniz ne düşünüyorsunuz.

**Comment by ozkanozcan** [comment]
Bir işveren olarak şunu söyleyebilirim ki personel işe alırken bu güne kadar eğitimine, yaşına veya aldığı sertifikalarına hiç bakmadım.  Sadece github hesabına, referanslarına, yaptığı işlere, geliştirdiği uygulamalara, yazdığı kodun kalitesine önem verdim. Sektördeki pek çok yer de böyle yapar.  

Ülkemizde malesef ücretli eğitimde sertifika vermek çok karlı bir sektör haline gelmiş. Para tuzağından başka bişey değil. Çok geliyor böyle kursların mezunları ama malesef sektör ihtiyaçlarından çok uzaklar. 

Unutmayın işi sertifika değil, insan yapıyor. İşverenler sertifikanıza değil bildiklerinize ve yaptıklarınıza para öder.

Bence paranızı ve zamanınızı sertifikaya harcayacağınıza o parayla aynı alanda birebir özel ders alarak mentorünüzle birlikte githubda yer alacak birkaç sağlam projeyi geliştirmeye harcayın. 100 kat daha faydalı olur. 

Mesela web için bir e-ticaret sitesi, bir kurumsal site, bir haber sitesi geliştirmiş adam her zaman benden onay alır.  

İstanbuldaysanız ve mutlaka kurs almam lazım diyorsanız da [C ve Sistem Programcıları Derneği](https://csystem.org/) kurslarına gönül rahatlığıyla katılabilirsiniz. Bunun dışında hiçbir yere para ödemeyin. Youtube üzerinde onlarca kaliteli içerik yer alıyor onları değerlendirin.

**Comment by VB10** [comment]
Selamlar @ozkanozcan hocama çok katılıyorum.

Türkiyedki bir çok program yeni başlayan kişilerin cebindeki paraya göz dikmiş adeta ondan dolayı en büyük ve en kolay tavsiyem sürekli ingilizce içerikleri takip etmek bu konuda yotubuda da çok güzel içerikler var.
Ben hayatımda daha sertifikaya bakan bir şirket görmedim yazılım konusunda yurt dışında bir kaç agile sertifiklarına bakıyorlar onlarda paarası ver al gibi.

Senin en büyük sertifikan githubun yaptığın projelerin veya  teknik yeteneğin ondan hiçbir site hiçbir kuruma ihityacın yok eu da olursa global onlar candır ama hiç girme derim ful lfocus çalışmak.

Parayı da git yemek ye ailenle harca onlarla para kaptırma boşver.
