### ISSUE TITLE
ios notification permisson

### ISSUE THREAD

**Issue by hendeseicode** [VB10/vboverflow#150]
merhaba hocam
iOS emulatorde uygulamam açıldığında **bildirim gönderme izni** istiyor ve **izin veriyorum**, ayarlara baktığımda da şöyle gözüküyor.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/29240246/201493771-bb332215-0e3e-4c31-b8aa-7305c30957dc.png">
ancak kod içerisinde `Permission.notification.isGranted` dediğimde ise `false` dönüyor.
iOS emulator bildirim almadığı için mi böyle gözüküyor ya da yanlış bir şey mi yapıyorum?

Selamlar

**Comment by hendeseicode** [comment]
Firebase messaging authorizationStatus ile granted aldım. 
Şimdiki problemim ise şu
uygulama ilk açıldığında messaging.requestPermission ile default izin isteme pop up'ı alabiliyorum, uygulama çalışırken bir t anında tekrar requestPermission dediğimde pop up çıkarmıyor..
ve zaten init anında istenen request permission uygulama ilk çalışması sonrasında diğer ayağa kaldırmalarda da çıkmıyor. Yani bir kez evet ya da hayır dendikten sonra kod o satırı sorunsuz geçse de pop up çıkmıyor.. Bu neden olabilir?

Uygulama yüklendikten sonra ilk açılışta değil de ilerleyen safhalarda permission istersem ne yapmam gerekir?

**Comment by VB10** [comment]
@hendeseicode bunu anlattım buradakinin aynısı olacak network bakılacak 
https://www.youtube.com/watch?v=MDAEOmZg8fc&t=2911s
