### ISSUE TITLE
flutter yeni proje hatasi

### ISSUE THREAD

**Issue by ysmltr** [VB10/vboverflow#151]
Launching lib\main.dart on Windows in debug mode...
lib\main.dart:1
C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(247,5): error MSB8066: Custom build for 'C:\Users\yesim\OneDrive\Masaüstü\development\flutter_full_learn\build\windows\CMakeFiles\44a008bd473b9d10464244e74bf3c435\flutter_windows.dll.rule;C:\Users\yesim\OneDrive\Masaüstü\development\flutter_full_learn\build\windows\CMakeFiles\57f77cc8f4b05cca68df2e52ad23f23d\flutter_assemble.rule' exited with code 1. [C:\Users\yesim\OneDrive\Masaüstü\development\flutter_full_learn\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)

selamlar flutterda yeni proje yaparken projeyi calistir dedigimde debug console da bu hatayi goruntuluyorum stackoverflow ve cesitli sitelere baktim ancak pek iyi sonuclar vermedi yardimci olabilecek var midir

**Comment by VB10** [comment]
@yesimltr1 bu konuda bilgim yok ya windows tarafında ama sanki andorid ile lakalı bir durum gibi android studio indirip orada new project diyip run yap bir projeyi açılırsa bence çözülür

**Comment by ysmltr** [comment]
veli abi selam android studio tarafında herhangi bir hata almadan çalıştırabiliyor ve emülatörü görüntüleyebiliyorum vscode tarafında ise chrome da çalıştırınca emülatör yine açılıyor ancak windows tarafında bu hatayı alıyorum

**Comment by emirhalici** [comment]
Selam @yesimltr1, Windows destegi yeni geldi ne kadar stabil bilmiyorum ama anlattigin kadariyla olay tamamen Windows build ile alakali. 

https://docs.flutter.dev/development/platform-integration/windows/building
Bu kaynakta **Compiling with Visual Studio** basliginda biraz aciklama var. Eger build klasoru olusuyorsa Visual Studio (VS Code degil yalniz dikkat) ile acip anlatildigi gibi build almayi deneyebilirsin. Windows build icin Windows API'larina gidildigi icin belki SDK kisminda hata olabilir. Tekrar kurulabilen bir sey ise tekrar kurmayi deneyebilirsin. 

https://stackoverflow.com/questions/67031371/flutter-windows-cannot-build-app-error-msb8066
Alternatif olarak bir de su StackOverflow basligi var, anlasilan bu hata bir cok sebepten olusabiliyor. Yazilan cozumlerden sana uyani varsa onlari denemeni de tavsiye ederim. 

Hala hic bir sey cozmediyse daha iyi anlasilmasi icin su alttaki komutlarin sonucunu paylasabilirsin, belki daha bilge birisi buradan hatayi yakalayabilir.

`flutter doctor -v`
Flutter surum bilgilerini vs verecek
`flutter run -d windows -v`
Projeyi verbose modda calistiracak bir miktar daha aciklayici olabilir

**Comment by ysmltr** [comment]
@emirhalici oncelikle oneri icin tesekkur ederim yaptigim  seyleri yazacagim
 C:\ klasoru icindeki src dosyasina flutterSDK zip dosyasini 'dosyayi ayikla' yaparak herhangi bir buyuk harf sayi ozel semboller (/_ vb. )gibi olmadan cikarttirdim

uygulama adi buyuk harf sayi ozel sembol kabul etmedi ayni sekilde onu da tekrar duzelttim

eksik olan eklentileri-vscode zaten bu eklentilere seni yonlendiriyor- ekledim

app klasoru icindeki gradle.properties icine android.overridePathCheck=true yazmak -bunu stackoverflowda gordum

ve son olarak anlamakta zorlandigim kisim ise benim dosya dizinim turkce karakter iceriyor appin oldugu dosyayi baska bi klasoru tasidim ve orda calisti   

benim hatalar dizinim boyleydi 
 tekrardan oneri icin tesekkurler iyi aksamlar
