### ISSUE TITLE
flutter 3.0 listview reverse refresh

### ISSUE THREAD

**Issue by hendeseicode** [VB10/vboverflow#152]
merhabalar
Flutter 3.0'a yükselttikten sonra projemdeki reverse list view üzerinde pull from down bozuldu ve yukarıdan aşağı doğru çekince refresh ediyor, aşağıdan yukarı çekince etmiyor. Bu da uzun listeler için uygun bi davranış değil.
Eskiden ListView reverse ise refresh işlemini aşağıdan yukarı çekerek yapıyordu otomatik olarak, Flutter 3.0'de bunu değiştirmişler anladığım kadarıyla, ListView pull from down refresh'i reverse haricinde nasıl yapabilirim?

**Comment by VB10** [comment]
Sorularını önce stackoverflow a açıp sonra buraya sorarsan daha iyi olacak @hendeseicode
