### ISSUE TITLE
Search with delayed 

### ISSUE THREAD

**Issue by isshort** [VB10/vboverflow#154]
Merhabalar Herkese
Search icin delay yapmak mantikli mi?
Textfield icinde onChange fonksiyonda her onChange'da servere istek atmasin biraz beklesin bunun icin Future.delayed yapmak gerek yoksa Timer ile kontrol etmek mi gerek yahem baska bir oneriniz varsa

**Comment by sinanhaci** [comment]
Timer ile yapabilirsin, her değişiklikte timer.cancel(); sonrasında ise timer'i tekrardan set edersin. Bu şekilde sağlıklı çalışır.

**Comment by emirhalici** [comment]
Cok guzel bir soru ++
Best practice acisindan, surekli server'a gitmemek icin araya delay koymak mantikli mi?  Mantikli ise @sinanhaci'nin onerisi guzel geldi, cok yerde kullaniliyorsa atomic component yapilip icine gomulebilir. Developer'a acik API'da sadece onChange callback'i alinir iceride timer boilerplate'i gizlice calisir. 
Asil soru icin sektorde ne tur cozum kullaniliyor, geneli delay koyuyor mu bu konuda fikri olan varsa yesillendirebilir.

**Comment by sinanhaci** [comment]
Veli'nin bununla ilgili bir videosu var yanlış hatırlamıyorsam. Ben dediğim gibi yapıyorum, search enumları hazırlayıp (start,loading,error,success...) gibi her bir durum için de widget hazırlıyorum. Sonra tüm projede onu ilgili parametreleri geçerek kullanıyorum. Bir çok proje yaptım ve bir sorunla karşılaşmadım.

**Comment by VB10** [comment]
Debounce olarak da bu kavram karşımıza çıkar. klavyeden her geleni yollamak yerine 100ms fark ile son basılanı yollamak bir avantaj sağlayacaktır yani kullanıcının elini kaldırdığı yeri anlamak gibi düşünebilirisin. kanalda var içerik @isshort
