### ISSUE TITLE
Flutter BlocBuilder Widget'i Tekrardan Oluşturmuyor

### ISSUE THREAD

**Issue by urazalkis** [VB10/vboverflow#155]
Herkese merhaba,2 adet listview builder kullandığım listem var.Bu iki liste arasındaki itemleri sürükle bırak şeklinde değiştirmek istiyorum.Bunun için widget'ı draggable ile sarmalıyorum.Problem şurada başlıyor.onDragEnd methodunda cubit ile her işlemde listeden eleman çıkarıp emit ediyorum.State durumunda listedeki eleman sayısı doğru sayıyı verse de ui kısmında listeden eleman eksilmiyor.Ui kısmında bloc selector kullandım.Normalde state her tetiklendiğinde builder'ın da tetiklenmesi gerekmiyor mu?Bu ui model bottom sheet içinde açılıyor.Bottom sheet'i her açayıp kapadığımda eleman eksiliyor fakat normalde blocselector ile widget yenilenmesini tetikleyemiyorum.

Cubit bölümünde emit ettiğim methodlar;
```
 void removeMissingItem(int cardIndex, int missingItemIndex) {
    likeRecipeItems[cardIndex].missingItems!.removeAt(missingItemIndex);
    emit(MissingItemListLoad(likeRecipeItems[cardIndex].missingItems!));
  }
  void addItemToMyFrize(IngredientModel itemModelToBeDeleted) {
    myFrizeItems.add(itemModelToBeDeleted);
    emit(MyFrizeListLoad(myFrizeItems));
  }
```
View sayfasındaki BlocSelector kullanımım;
```
                BlocSelector<LikesCubit, ILikesState, List<IngredientModel>>(
              selector: (state) {
                if (state is MissingItemListLoad) {
                  return state.missingItemList;
                } else {
                  return cubitRead.likeRecipeItems[cardIndex].missingItems ??
                      [];
                }
              },
              builder: (BuildContext context, state) {
                return Flexible(
                  flex: 4,
                  child: ListView.builder(
                    scrollDirection: Axis.horizontal,
                    itemCount: state.length,
                    itemBuilder: (BuildContext context, int missingItemIndex) {
                      return Padding(
                        padding: EdgeInsets.only(right: context.lowValue),
                        child: DraggableIngredientCircleAvatar<int>(
                          data: missingItemIndex,
                          onDragEnd: (DraggableDetails draggableDetails) {
                            if (draggableDetails.wasAccepted == true) {
                               cubitRead
                                  .addItemToMyFrize(state[missingItemIndex]);
                              cubitRead.removeMissingItem(
                                  cardIndex, missingItemIndex);
            
                            }
                          },
                          iconBottomWidget: BoldText(
                            text: state[missingItemIndex].quantity.toString(),
                            style: const TextStyle(color: Colors.white),
                          ),
                          color: ColorConstants.instance.oriolesOrange
                              .withOpacity(0.4),
                          model: state[missingItemIndex],
                        ),
                      );
                    },
                  ),
                );
              },
            ),
```
istediğim şey tam olarak missing item bölümünden your frize bölümüne sürükle bırak şeklinde item transferi.Sürükle bırak kısmında Draggable kullandım ve düzgün şekilde çalışıyor fakat ben sürükleme işlemi tamamlandıktan sonra sürüklenen widget'ın visible durumunu değiştirsem de widget aslında silinmiyor.Bottom sheet'i kapatıp açtığımda silinen item gerçekten silinmiş oluyor fakat bunu bloc builder ile sağlayamadım.Problem burada nedir?Teşekkürler
<img width="302" alt="Ekran Resmi 2022-11-23 17 12 06" src="https://user-images.githubusercontent.com/43914441/203568198-ddb954b5-85b3-40e6-a8a5-8485ca601aa5.png">

```

**Comment by VB10** [comment]
burada temel sorun o yenilenen listenin referansı aynı olduğu için emit öncesinde update oluyor liste güncellesende uida bu değişmiyor yapılabilecek hareketler
- list içinde tuttuğun modeli equaltiy ile sarmalayıp bunu immutable hale getirieceğiz
- değişen listeyi tolist gibi methodlar ile yeni referansı tutacağız 
- ( final x = state.oldlist.tolist; x.remove or any business then emit(x))
