### ISSUE TITLE
Flutter App Badge ozelligi

### ISSUE THREAD

**Issue by emirhalici** [VB10/vboverflow#156]
Selamlar. Bir cok uygulama application badge count ozelligine sahip. Android/iOS'te app'i acmadan once gozuken kirmizi bildirim sayisindan bahsediyorum. Mesela Gmail uygulamasinda muhtemelen 30-40 bildirim var. Bu ozellik icin yaygin olarak [flutter_app_badger](https://pub.dev/packages/flutter_app_badger) kullaniliyor. Plugin sistemini ve ic logic'i dogru sekilde yazdim, iOS tarafinda fiziksel cihazda beklenen gibi calisiyor. Ancak Android tarafinda birden cok fiziksel cihazda denememe ragmen bir turlu calistiramadim. Bu konuda daha once calismis bilgisi olan veya fikri olan var midir? Kodlar benim olmadigi icin paylasamiyor malesef. 

Dipnot: Plugin aciklamalarina gore Native App Badge destegi Android'de yok. App native bir plugin uzerinden bor cok launcher'a destek verdigini soyluyor. Samsung ve Xiaomi cihazlarda testlerime gore calismiyor. 
<img width="72" alt="Screen Shot 2022-11-25 at 20 40 57" src="https://user-images.githubusercontent.com/81600010/204034579-72d99c02-fabd-40d4-96be-ef0ae834c592.png">

**Comment by VB10** [comment]
emir bu pakette bende sorunlar yaşadım android tarafında burada şu şekilde yolladığın fcm rest isteğinde bodye badge propertysi ekleyerek yaparsan daha iyi sonuca ulaşıyorsun veya firebase scopeda app baslamadan önce gelen mesajları dinlemek için olan yere kod yazmıştık android için.

paket belirli bir sdkdan sonra destekliyor aslında o paketin prlarında bir kaç arkadaş başka yerlere kod yazmıştı ama onlarda çok tutarlı değil.
