### ISSUE TITLE
[Method] Flutter hatalarını nasıl yakalıyorsunuz?

### ISSUE THREAD

**Issue by azaderdogan** [VB10/vboverflow#157]
Merhabalar, error'ları yakalamak için firebase crashlytic kullanıyoruz. Fakat son zamanlardan hataları yakalayamıyoruz. Öğrenmek istediğim aktif olarak en güncel şekilde nasıl hata yakalayıp Crashlytic'e event yolluyorsunuz. 
Aktif olarak bu şekilde yakalıyoruz ama dediğim gibi crashlytic kendisi hata veriyor. 
https://firebase.flutter.dev/docs/crashlytics/usage#zoned-errors

``` 
await runZonedGuarded(() async {
    WidgetsFlutterBinding.ensureInitialized();
    await Firebase.initializeApp();

    try {
  
      if (kDebugMode) {
        await FirebaseCrashlytics.instance
            .setCrashlyticsCollectionEnabled(false);
      }
 
      FirebaseMessaging.onBackgroundMessage(
          _firebaseMessagingBackgroundHandler);
      FlutterError.onError =
          FirebaseCrashlytics.instance.recordFlutterFatalError;

      await AnalyticsService().init();
      await RemoteConfigService().initializeRemoteConfig();

      HydratedBlocOverrides.runZoned(
        () => runApp(MyApp()),
        storage: storage,
        blocObserver: AppBlocObserver(),
      );
    } catch (e) {
      debugPrint("Locator setup has failed : $e");
    }
  }, (error, stackTrace) {
    if (error is DioError &&
        (error.type == DioErrorType.connectTimeout ||
            error.type == DioErrorType.receiveTimeout)) {
      return;
    }
    debugPrint("runZonedGuarded: Caught error in my root zone: $error");
    FirebaseCrashlytics.instance.recordError(error, stackTrace, fatal: true);
  });
```

**Comment by sinanhaci** [comment]
Ben son bir kaç aydır sentry kullanıyorum ve iyi olduğunu düşünüyorum, dökümanları da gayet açıklayıcı. 
Göz atmak istersen : https://docs.sentry.io/platforms/flutter/

**Comment by VB10** [comment]
@sinanhaci dedigi gibi sentry guzel firebase kendisi bunu zaten yakiliyor ama asil nokta hatalarin oldugu yerde kendin bunu firebase loglamak, ikicnisi sayfalara anlyitc datalari atarak bu loglari duzenlemek. fatal errorlarin hepsi dusecektir dokumandakini yaparsan
