### ISSUE TITLE
[Security] This method should not be called on the main thread as it may lead to UI unresponsiveness.

### ISSUE THREAD

**Issue by udanaDbb** [VB10/vboverflow#158]
Merhabalar üzerinde çalıştığım uygulamamda webview içeriklerini açarken ios 16 sürümü ve üstündeki sürüme sahip cihazlarda 1 sn önce siyah bir ekran geliyor ardından webview içeriği açılıyor. Ancak ios 16 sürümü altında ki cihazlarda webview içeriği sorunsuz açılıyor. Araştırdığımda ios güncellemesi ve xcode sürümü ile alakalı olduğunu gördüm lakin henüz bir çözüme ulaşamadım. Bu sorunla karşılaşan var mı acaba daha önce varsa nasıl çözüldü belli ki güncel bir sorun yardımcı olabilirseniz sevinirim.

**Comment by sinanhaci** [comment]
Kod paylaşabilir misin?

**Comment by udanaDbb** [comment]
WebView kodu ama hatayı xcode tarafında alıyorum 
```
class LinkWebViewPages extends StatefulWidget {
  const LinkWebViewPages({
    Key? key,
    required this.path,
  }) : super(key: key);

  final String path;

  @override
  State<LinkWebViewPages> createState() => _LinkWebViewPagesState();
}

class _LinkWebViewPagesState extends State<LinkWebViewPages> {
  FlutterWebviewPlugin flutterWebviewPlugin = FlutterWebviewPlugin();

  @override
  void initState() {
    super.initState();

    //if (Platform.isAndroid) WebView.platform = AndroidWebView();
  }

  @override
  void dispose() {
    // TODO: implement dispose
    super.dispose();
    flutterWebviewPlugin.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async {
        await flutterWebviewPlugin.close();
        return true;
      },
      child: WebviewScaffold(
        url: widget.path,
      ),
    );
  }
}
```
Xcode tarafında aldığım warning
<img width="1148" alt="Ekran Resmi 2022-11-28 11 28 07" src="https://user-images.githubusercontent.com/113332940/204972456-e8c38a0a-ec2e-4d1c-b355-d1ae964bf474.png">

**Comment by VB10** [comment]
@udanaDbb bu konuda net bir bilgim yok ancak bizim webveiwlarda suan bir sorun goremedim son pakete guncellersen gecmis olabilir
