### ISSUE TITLE
Gesturededector 

### ISSUE THREAD

**Issue by Mustyy61** [VB10/vboverflow#159]
Farklı sayfalarda bulunan  iki ayrı Gesturededector ile  sarmaladigim Buttonlarim var. Basit bir eslestirme oyunu gibi. Bu widgetler içeriklerini iki ayrı listeden gelen veriler ile oluşturuyor. Senaryoda ilk önce birinci butona tiklaniyor daha sonra ikinci butona  içerisinde ki veriler eşleşiyor ise 1.buttonun içerisinde ki veriyi siliyorum.
Yaşadığım sorun tam olarak şu. Birinci tıklanan butonun içerisinde if(1.button==2.button) sorgum var doğal olarak ilk tiklamada if koşulu sağlanmadığı için 2. Tıklanma bekleniyor. 2. Tıklama gerçektestikten sonra.1. button tetiklenmedigi için ancak bir kez daha 1.butona tıklayınca istediğim oluyor. Bu durumu nasıl düzelte bilirim ?

**Comment by elkira37** [comment]
Kontrolü 1.butonda değil 2.butona tıklayınca yap daha sonra en basitinden setState komutuyla ilk butonu da yeniden çizdirebilirsin.

**Comment by Mustyy61** [comment]
Teşekkür ederim cevabınız için fakat 2. button ayrı bir classın içerisinde  ve index bilgisi üzerinden haberleşiyorlar. İşlemi ikinci buttona taşıyınca index bilgisini yollamamıyorum hata veriyor. İndexi listview.builder dışında nasıl kullana bilirim ?

**Comment by bafranokta** [comment]
> Teşekkür ederim cevabınız için fakat 2. button ayrı bir classın içerisinde ve index bilgisi üzerinden haberleşiyorlar. İşlemi ikinci buttona taşıyınca index bilgisini yollamamıyorum hata veriyor. İndexi listview.builder dışında nasıl kullana bilirim ?

En basitinden iki classın dışında ortak bir değişken tanımlayıp değeri bir buttonun onpressed'ında o değişkene atayabilir, daha sonra diğerinde okuyabilirsiniz Ayrıca dart temel konularına da tekrar bir göz atın isterseniz.
