### ISSUE TITLE
Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: id.flutter/background_service_android_bg. Response ID: 38

### ISSUE THREAD

**Issue by sorosons** [VB10/vboverflow#16]
Merhaba arkadaşlar
Kotlinde gelen bildirimleri anlık olarak alıp flutter trafına taşımak istiyorum ve uygulama kapalıyken bunları bir sql lite veya Sharedpreferencese kaydetmek istiyorum uygulama açıkken kotlin tarafında yazdığım kod sayesinde veriyi sağlıklı alabiliyorum ama uygulama kaplaıyken başlıktaki hatayı alıyorum (kotlin ve flutter tarafında backgorund service çalıştırıyorum ) 
şimdiden herkese teşekürler

**Comment by VB10** [comment]
bunu sessiz notifcaiton dedigimz yapiyla yapsan burada push ile locali updat edeiblrisin ozelllikle kotlin koduna girmeden hlalediblrisn gibi aslinda 

`Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();

  print("Handling a background message: ${message.messageId}");
}

void main() {
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);
  runApp(MyApp());
}`

**Comment by sorosons** [comment]
Teşekürler cevap için gelen tüm bildirimler için bunu yapmak istiyorum ve uygulama kapalıyken gelen veriyi sql lite kayıt etmek istiyorum

**Comment by VB10** [comment]
dedıgım gıbı eğer 1-1 to anlık olacaksa backgorund servist edinlemekte fayda var sqlite seklinde çalışmadığımdan bir şey eksik söylemek istemem ama bu firebasesin slient notificaton ypaısıyla kayıt aalbilrisn

**Comment by sorosons** [comment]
Ben daha çok şu an karşıalştığım problemi çözmek istiyorum doğrusu yani uygulama arka plandayken kotlin tarafından flutter tarafına aldığım veriyi işlemek istiyorum
