### ISSUE TITLE
Apk File Security

### ISSUE THREAD

**Issue by Theselman** [VB10/vboverflow#160]
Selamlar. Yerel veritabanı ya da firebase kullanmadan image_picker ile videoyu alan ve galeriye gallery_saver paketi ile bu videoyu kaydeden bir uygulama bu şekilde yayınlanırsa güvenlik problemi oluşturur mu? Güvenlik problemi ile kastetmek istediğim ise Apk dosyasına dışarıdan erişilebilmesi, kullanıcının düzenleyip telefona kaydettiği videosuna dışardan birilerinin erişme imkanı var mı?

**Comment by VB10** [comment]
bruada dikkat edilmesi gereken permissonlar bunun dışında eğer telefonu birisi ele geçirse evet her zaman o dosyalara erişebilir ancak şöyle bir kayıt işlemi yaparken eğer şifreli kayıt yaparsak sadece appten okunur bu sayede gitse bile bir sorun kalmaz. jailbreak veya kuallancı hatası dışında bildiğim kadarıyla zor + proguard gibi android apk security kuralları uygulanabilir onlar her yerde var
