### ISSUE TITLE
State Managment

### ISSUE THREAD

**Issue by sorosons** [VB10/vboverflow#161]
Merhaba state management olarak ne kullanılmalı bazıları Streamcontrollerin (Stream Sink StreamBuilder) bunlar mı yoksa provider riverpod block getx hangileri kullanılmalı yada kullanılmamalı açıkalrsanız sevinirim yada daha önce açıkladıysanız örnek video veya yazı linki paylaşabilirmisiniz iyi kodlamalar.

**Comment by VB10** [comment]
Merhaba özellikle bu altta paylaşacağım video ve bunun devamındaki bloc videosu düşünce anlatımı açısından çok iyi oturacaktır. Burada önemli olan yapılacak işe göre ve yetkinliğe göre yatırımı yapmak ve daha iyisini aramadan önce aslında basit kuralları uygulamak. Bunu kullandım bundan daha hızlı vs daha bugüne kadar gördüğüm duyduğum olmadı genelde atomic veya structre hataları bu tarz paketleri öldürüyor misal mobx de oldukça güzel bir paket.
yani önemli olan düşünce hep @sorosons 


https://www.youtube.com/watch?v=lMJx2PG9Hlw&lc=UgxbVpSBc4iM0zt-CrR4AaABAg
