### ISSUE TITLE
VB Flutter Road Map on HardwareAndro

### ISSUE THREAD

**Issue by hasangungr** [VB10/vboverflow#162]
Hocam size sorum şu 7 saatlik dart programlama videonuz ile başlangıç yaptım tavsiye ettiğiniz bir izleme sıralaması var mı gerek tekli videolar gerek video serileri oynatma serileri. Hem sıralama olarak hem önem olarak sizi en doğru nasıl takip edelim nasıl izleyelim hocam. Teşekkür ederim.

**Comment by yusufkecer** [comment]
Dartın temelleri videosundan sonra, 20+ saatlik flutter video serisi var. Bu seriyle devam etmeni öneririm. Temeli iyi bir şekilde oturttuktan sonra, bol çalışma ve kod yazmakla devamı gelir zaten.

**Comment by VB10** [comment]
bana göre en iyi yöntem şu olurdu ilk baştan sona doğru:
her zaman açık kaynak olup yan taraftaki dünyaları okumak hep şart bu kanaldaki düşünceyi alıp başka bir paketle birleştirebilirsen çok iyi yerlere gideceksindir

(kanalda önceden yayınladığım buton vs gibi basit örnek olan videolarada bakılabilir)
- dart 7 saat https://www.youtube.com/watch?v=H6NJHb5BJyE
- flutter full seri https://www.youtube.com/watch?v=lpvuM9lo3HU&list=PL1k5oWAuBhgXdw1BbxVGxxWRmkGB1C11l

bu ikisini yaklaşık 2x3x tekrar yapmak lazım üzerine 
- use case serileri
- arcihtecture template https://www.youtube.com/watch?v=fGNXqZd-Als&list=PL1k5oWAuBhgV_XnhMSyu2YLZMZNGuD0Cv

ek olarak vb10.dev okunmalı üstüne https://vbacik-10.medium.com/ de yazdığım yazılar ile teknik iyeliştirme sağlanmalı.
bu içerikleri izledikçe hazır ui kitler bularak bol tekrar yaparak mutlak öğrenime ulaşmış olunur https://www.uplabs.com/posts/challenge-app-ui-kit
