### ISSUE TITLE
Notification çalışmıyor.

### ISSUE THREAD

**Issue by ElgizCebrayilov992** [VB10/vboverflow#163]
Selam.
Sorunum iki paket ile ilgili.
win_toast 0.3.0 ve local_notifier: ^0.1.5.
Bu paketi kulananda normal bilgisaraylarda calisiyor. bilgisarayın sağ alt köşede bildiriş çıkıyor.
Amma Şirketin bilgisaraylarında bu çalışmıyor.
Şirketin İT elamanına sordum.O bana söylediki sen kod tarafında bildirişi user yetkisi vermen gerekir. Adminstrator yetkisi ile çalışdığı için Active directory senin bu bildirişini engelliyor ve Bilgisarayın ekranında gözükmüyor.
Şimdi ben sorunu nasıl çöze bilirim.
User yetkisini nerde vermem gerekir.

**Comment by VB10** [comment]
bu konuda bir bilgim yok bir şey diyedim tavsiyem hataları ilgili paketlere log olarak paylaşman.
