### ISSUE TITLE
video_player paketinde video oynatma hız ayarı

### ISSUE THREAD

**Issue by Theselman** [VB10/vboverflow#164]
Bir videoyu galeriden video_player ile alıp altta bir slider'a bağlı olarak controller.setPlaybackSpeed() yöntemi ile slider her değiştiğinde video oynatma hızını değiştiriyorum. Video oynatma hızı değişen yeni videoyu galeriye kaydetmek istiyorum ama hızı değişen video bilgisini hangi yöntemle alacağımı bulamadım controller.value ve controller.dataSource yöntemlerini denedim işe yaramadı. Bu değişen video bilgisini hangi yöntemle alabilirim? Bu konuda paketin dökümamına baktım stackoverflowda soru da açtım ama dönüş yapan olmadı. Linki bırakıyorum. [https://stackoverflow.com/questions/74982062/change-playback-speed-in-flutter-video-player-package]

**Comment by VB10** [comment]
@Theselman bu konuda doğrudan bir çalışmam olmadı paket özelinde bir konu gözüküyor bunu da pakete issue açmanı tavsiye ederim.
