### ISSUE TITLE
Flutter Projelerinde Versiyon Yükseltmenin önemi

### ISSUE THREAD

**Issue by sefaer** [VB10/vboverflow#165]
Frameworklerin yeni versiyonları geldiğinde en az 6 ay geriden gelinmeli yeni versiyona hemen geçiş sağlanılmamalı gibi bir durum var firmalarda. Bu durumu oluşabilecek her ihtimal için değerlendiriyorlar ve anlıyorum. Flutter için bu durum geçerli mi ? 1.22.6 olan büyük bir projeyi 3.3.9 a yükselttik, fakat geçişte yine de bekletme kararı alındı. Benim flutterda gözlemim versiyon yükseldikçe eski mevcut yapıları en az eskisi kadar kullanabiliyorsun ve üstüne daha iyi özelliklerde bir çok yeni yapı gelebiliyor. Yani Flutterda versiyonu yükselttikçe uygulamayı riske atan bir durum ihtimalini aslında daha aza indirgemiş olmuyor muyuz ve aynı zamanda kullanabileceğimiz bir çok yenilikte widget ve yapılar oluyor. 

Özetle : Versiyonu 1.22.6 Live olan bir uygulamayı Flutter  3.3.9 a upgrade edip live'i güncellemek risk yaratıyor mu ?

**Comment by VB10** [comment]
merhaba sefa yaklaşık 1. versiyonundan beri aktif olarak prod da işler yapan birisi olarak flutter versiyonları geçişleri en rahat olan fwlerden çünkü dediğin gibi daha çok depracated olarak ilerleyip ardından kaldırılıyor en köklü değişimi null safety vs ile geldi onun dışında genelde proje versiyonları update'inde bir kaç küçük import vs ile her şey çözülüyor. 

Verdiğin örnektede paketler ve kullandığın yapılar yeni durumlara göre güncellenir ise flutterdan ötürü bir sorun yaşamadan geçeceksindir. ama misal notifcaiton paketi yeni özellikler alıyor o kod sende olmuyor onu update etmek şart veya bir button silinmiş oluyor ama yerine muhakak başka widget çıkıyor. burada commit edeceğim konu build başarılı olduktan sonra doğru bir şekilde çalışıp projenizi güncellemiş olurusunuz.

bu tarz updatelerde genelde projelerde çok fazla eksik hata dependy sorunları ortaya patlar ve insanlar genelde bu update yapıp bu kodları da düzeltmek istemediğinden çok girmez ve update ötürü denilir. flutter özelinde 12k issue görüp bir kaç harekette ki kanalda var bu fixleyip sayıları rahatlıkla çözebiliyorsun
