### ISSUE TITLE
Temelden Zirveye Flutter #7 Dakika 20:00-30:00 arası LifeCycleDemo ile ilgili.

### ISSUE THREAD

**Issue by FurkanBekereci** [VB10/vboverflow#166]
Hocam merhabalar. Hocam benim 7. videoda kafama birşey takıldı. Serinin başlangıç videolarının birinde söylediğiniz üzere parent widgettan yapılan setState işlemi, ilgili ilgisiz tüm subwidgetları da yeniden çizmeye sebep oluyor. 

Daha önce angular yazdığım için ve orada rxjs observable'lar sıklıkla kullanıldığı için bunu sizin yaptığınız LifeCycleDemoView ve ColorDemo'da uygulamaya çalıştım. Bunun doğru olup olmadığını öğrenmek istedim sizden. Aşağıda, uyguladığım adımları sıralamaya çalıştım. Umarım açıklayıcıdır.

- Yaptığım şeyler initalColorı parentta setState yapmak yerine ColorDemo widgetinin içinde "StreamController streamController = StreamController.broadcast();" (Stream classını da dart kursundan dolayı kullanabileceğimi düşündüm.) gibi bir stream oluşturarak ve bunu initState() metodunda  widget.streamController.stream.listen() metodunu kullanarak subscribe oldum.

- Daha sonrasında parent widget içinde ColorDemo widgetini direkt build metodu içinde vermek yerine parent widgetin initState metodunda initialize ettim. Bunu yapmamdaki amaç ColorDemo widgetinin streamController propertysini appbar clear buttonunun onpressed callbackinde kullanmaktı.

-  streamController.add(null) metodu yardımı ile ColorDemo widgetına bir nevi sinyal yolladım. 

- listen() metodu ile üst widgettan sinyali yakalayabildiğimi gördüm. 

- Böylece parent widgetta diğer elementler bu yöntemle yeniden çizilmemiş olacak diye düşündüm.

- Daha sonra da broadcastten dispose metodunda cancel() metodu yardımı ile ayrıldım. Böylece broadcast açık kalmamış oldu.

-  Benim anlamak istediğim nokta, Stream yöntemini kullanmak mantıklı mı olur? Yaptığım işlemler aşağı linklerdedir.

https://github.com/FurkanBekereci/VB-Flutter-Tut/blob/master/lib/demos/color_demo.dart
https://github.com/FurkanBekereci/VB-Flutter-Tut/blob/master/lib/demos/life_cycle_demo.dart

Eline, emeğine, yüreğine sağlık dostum. İyi çalışmalar. Eline kuvvet :)

**Comment by VB10** [comment]
elbette yapılabilir yani burada dikkat etmek gereken alt dallardan bu objenin dispose olması veya benzeri durumalar misal inherdi widget ta kullabilirsin aynı mantıkla diyeiblirm bu tarz teknik yaklaşımları severim ama teknik ykalaşımda misal bu yaklaşımı obersver pattern ile birleştirip okusan yeterli olur
