### ISSUE TITLE
Scroll overflow

### ISSUE THREAD

**Issue by ramazan351** [VB10/vboverflow#167]
Merhaba,  senaryo şu şekilde; bir ekranda iki listview'im var biri horizontal kayıyıor biri vertical, ama sayfanın tamamının scroll olmasını istiyorum. reposive bir tasarım elde etmem için nasıl bir yol izlemeliyim.(vertical'de scrool olması gereken widget DefaultTabController ile sarmalanmış bir tabBar. Her TabBarView'in gövdesinde bir listview.builder var)
yardımcı olursanız sevinirim iyi çalışmalar dilerim..
**Code senaryosu :**
import 'package:flutter/material.dart';

void main() {
  runApp(
    const MyApp(),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: SingleChildScrollView(
        child: Column(
          children: [
            SizedBox(
              height: 100,
              child: ListView.builder(
                itemCount: 50,
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => Container(
                  color: Colors.red,
                  height: 100,
                  margin: EdgeInsets.only(right: 10),
                  child: Text("data"),
                ),
              ),
            ),
            Flexible(
              child: DefaultTabController(
                length: 3,
                child: Scaffold(
                  //Scaffold'un içerisinde Scaffold kullanmak ne kadar mantıklı olur?
                  appBar: PreferredSize(
                    preferredSize: Size.fromHeight(8),
                    child: ListView.builder(
                      itemCount: 3,
                      scrollDirection: Axis.horizontal,
                      itemBuilder: (context, index) => Tab(text: "Tab${index}"),
                    ),
                  ),
                  body: TabBarView(children: [
                    ListView.builder(
                      itemCount: 5,
                      shrinkWrap: true,
                      physics: NeverScrollableScrollPhysics(),
                      itemBuilder: (context, index) => Container(
                        height: 100,
                        margin: EdgeInsets.only(bottom: 10),
                        color: Colors.amber,
                      ),
                    ),
                    ListView.builder(
                      itemCount: 5,
                      shrinkWrap: true,
                      physics: NeverScrollableScrollPhysics(),
                      itemBuilder: (context, index) => Container(
                        height: 100,
                        margin: EdgeInsets.only(bottom: 10),
                        color: Colors.amber,
                      ),
                    ),
                    ListView.builder(
                      itemCount: 5,
                      shrinkWrap: true,
                      physics: NeverScrollableScrollPhysics(),
                      itemBuilder: (context, index) => Container(
                        margin: EdgeInsets.only(bottom: 10),
                        height: 100,
                        color: Colors.amber,
                      ),
                    ),
                  ]),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by seydidemir** [comment]
import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/material.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget>
    with SingleTickerProviderStateMixin {
  TabController? _tabController;
  int _tabIndex = 0;
  int _tablength = 3;

  @override
  void dispose() {
    _tabController?.dispose();
    super.dispose();
  }

  @override
  void initState() {
    _tabController = TabController(length: 3, vsync: this);
    _tabController!.addListener(changeTap);
    super.initState();
  }

  changeTap() {
    if (_tabController!.indexIsChanging) {
      setState(() {
        _tabIndex = _tabController!.index;
      });
    }
  }

  String? swipeDirection;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(
      //   title: Text(''),
      //   backgroundColor: Colors.orange,
      // ),
      body: SafeArea(
        child: ListView(
          padding: EdgeInsets.all(15),
          children: <Widget>[
            SizedBox(
              height: 100,
              child: ListView.builder(
                itemCount: 10,
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => Container(
                  color: Colors.red,
                  height: 100,
                  width: 100,
                  margin: EdgeInsets.only(right: 10),
                  child: Center(child: Text("data")),
                ),
              ),
            ),
            SizedBox(
              height: 10,
            ),
            GestureDetector(
              onPanUpdate: (details) {
                swipeDirection = details.delta.dx < 0 ? 'left' : 'right';
              },
              onPanEnd: (details) {
                if (swipeDirection == null) {
                  return;
                }
                if (swipeDirection == 'left') {
                  if (_tabIndex <= _tablength) {
                    _tabIndex++;
                    _tabController!.index = _tabIndex;
                    setState(() {});
                  }

                  print(swipeDirection);
                }
                if (swipeDirection == 'right') {
                  print(swipeDirection);
                  if (_tabIndex >= 0) {
                    _tabIndex--;
                    _tabController!.index = _tabIndex;
                    setState(() {});
                  }
                }
              },
              child: Container(
                child: Column(
                  children: <Widget>[
                    TabBar(
                      isScrollable: true,
                      controller: _tabController,
                      labelColor: Colors.redAccent,
                      indicatorColor: Colors.transparent,
                      unselectedLabelStyle: TextStyle(
                        color: Colors.black,
                      ),
                      tabs: [
                        Tab(text: 'Birinci Tap'),
                        Tab(text: 'İkinci Tap'),
                        Tab(text: 'Üçüncü Tap'),
                      ],
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    Container(
                      child: [
                        Column(
                          children: List.generate(
                            2,
                            (index) => Container(
                              height: 100,
                              margin: EdgeInsets.only(bottom: 10),
                              color: Colors.blueAccent,
                            ),
                          ).toList(),
                        ),
                        Column(
                          children: List.generate(
                            100,
                            (index) => Container(
                              height: 100,
                              margin: EdgeInsets.only(bottom: 10),
                              color: Colors.amber,
                            ),
                          ).toList(),
                        ),
                        Column(
                          children: List.generate(
                            4,
                            (index) => Container(
                              height: 100,
                              margin: EdgeInsets.only(bottom: 10),
                              color: Colors.purple,
                            ),
                          ).toList(),
                        ),
                      ][_tabIndex],
                    ),
                  ],
                ),
              ),
            ),
            SizedBox(
              height: 10,
            ),
            SizedBox(
              height: 170,
              child: ListView.builder(
                itemCount: 10,
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => Container(
                  color: Colors.green,
                  height: 100,
                  width: 100,
                  margin: EdgeInsets.only(right: 10),
                  child: Center(child: Text("data")),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

**Comment by seydidemir** [comment]
`import 'package:flutter/src/widgets/container.dart';
import 'package:flutter/src/widgets/framework.dart';
import 'package:flutter/material.dart';

class MyWidget extends StatefulWidget {
  const MyWidget({super.key});

  @override
  State<MyWidget> createState() => _MyWidgetState();
}

class _MyWidgetState extends State<MyWidget>
    with SingleTickerProviderStateMixin {
  TabController? _tabController;
  int _tabIndex = 0;
  int _tablength = 3;

  @override
  void dispose() {
    _tabController?.dispose();
    super.dispose();
  }

  @override
  void initState() {
    _tabController = TabController(length: 3, vsync: this);
    _tabController!.addListener(changeTap);
    super.initState();
  }

  changeTap() {
    if (_tabController!.indexIsChanging) {
      setState(() {
        _tabIndex = _tabController!.index;
      });
    }
  }

  String? swipeDirection;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // appBar: AppBar(
      //   title: Text(''),
      //   backgroundColor: Colors.orange,
      // ),
      body: SafeArea(
        child: ListView(
          padding: EdgeInsets.all(15),
          children: <Widget>[
            SizedBox(
              height: 100,
              child: ListView.builder(
                itemCount: 10,
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => Container(
                  color: Colors.red,
                  height: 100,
                  width: 100,
                  margin: EdgeInsets.only(right: 10),
                  child: Center(child: Text("data")),
                ),
              ),
            ),
            SizedBox(
              height: 10,
            ),
            GestureDetector(
              onPanUpdate: (details) {
                swipeDirection = details.delta.dx < 0 ? 'left' : 'right';
              },
              onPanEnd: (details) {
                if (swipeDirection == null) {
                  return;
                }
                if (swipeDirection == 'left') {
                  if (_tabIndex <= _tablength) {
                    _tabIndex++;
                    _tabController!.index = _tabIndex;
                    setState(() {});
                  }

                  print(swipeDirection);
                }
                if (swipeDirection == 'right') {
                  print(swipeDirection);
                  if (_tabIndex >= 0) {
                    _tabIndex--;
                    _tabController!.index = _tabIndex;
                    setState(() {});
                  }
                }
              },
              child: Container(
                child: Column(
                  children: <Widget>[
                    TabBar(
                      isScrollable: true,
                      controller: _tabController,
                      labelColor: Colors.redAccent,
                      indicatorColor: Colors.transparent,
                      unselectedLabelStyle: TextStyle(
                        color: Colors.black,
                      ),
                      tabs: [
                        Tab(text: 'Birinci Tap'),
                        Tab(text: 'İkinci Tap'),
                        Tab(text: 'Üçüncü Tap'),
                      ],
                    ),
                    SizedBox(
                      height: 10,
                    ),
                    Container(
                      child: [
                        Column(
                          children: List.generate(
                            2,
                            (index) => Container(
                              height: 100,
                              margin: EdgeInsets.only(bottom: 10),
                              color: Colors.blueAccent,
                            ),
                          ).toList(),
                        ),
                        Column(
                          children: List.generate(
                            100,
                            (index) => Container(
                              height: 100,
                              margin: EdgeInsets.only(bottom: 10),
                              color: Colors.amber,
                            ),
                          ).toList(),
                        ),
                        Column(
                          children: List.generate(
                            4,
                            (index) => Container(
                              height: 100,
                              margin: EdgeInsets.only(bottom: 10),
                              color: Colors.purple,
                            ),
                          ).toList(),
                        ),
                      ][_tabIndex],
                    ),
                  ],
                ),
              ),
            ),
            SizedBox(
              height: 10,
            ),
            SizedBox(
              height: 170,
              child: ListView.builder(
                itemCount: 10,
                scrollDirection: Axis.horizontal,
                itemBuilder: (context, index) => Container(
                  color: Colors.green,
                  height: 100,
                  width: 100,
                  margin: EdgeInsets.only(right: 10),
                  child: Center(child: Text("data")),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
`

**Comment by VB10** [comment]
bu tarz soruları stackoverflowa açalım
