### ISSUE TITLE
Unable to install "Runner" Sorunu

### ISSUE THREAD

**Issue by enginbolat** [VB10/vboverflow#168]
Selamlar, projemin ios kısmı için xcode üzerinden build almaya çalışıyorum fakat bir türlü fiziksel cihazda build alamıyorum.Sanal cihazda herhangi bir sıkıntı yokken fiziksel cihaza geldiğimde ise **Unable to install "Runner"** hatasını alıyorum.Hatanın detayını incelediğimde ise **This application’s bundle identifier does not match its code signing identifier.** hatasına ulaşıyorum.Fakat uygulamamda bundleID gibi özellikleri ayarladım. Anlamadığım kısmı ise flutter create ile yeni bir proje oluşturup aynı bundleID'yi verdiğimde herhangi bir sıkıntı olmuyor ve uygulamayı başarılı bir şekilde build alabiliyorum.

Sürümler

- xCode 14.2
- IOS 16
- Flutter 3.3.4
- Fiziksel Cihaz iPhone 7 ios 15.7

**Comment by VB10** [comment]
sag üstte runner edit scheme orada debug seçili yaparsan sonuç alacaksındır
