### ISSUE TITLE
Flutterdan swifte geçiş

### ISSUE THREAD

**Issue by emrecsmsk** [VB10/vboverflow#169]
Hocam staj yaptığım yerde swifte başlayacağım da. Flutter biliyorum. Sizce swifti baştan bir kaynaktan mı öğrenmem daha doğru olur yoksa mantığı aynı diye adım adım bildiğim şeyler orda nasıl diye mi bakmam daha doğru olur?

Sizce nasıl bir yol izlemeliyim?

Teşekkür ederim.

**Comment by VB10** [comment]
şimdi emre flutter ile swift başka alanlar flutter ile switft ui veya uikit karşılatiraiblrsin tabiki bunlarıda öğrenmek iyidir ama burada gerçek dil öğrenimi dersen swift ile dart odaklanman lazım. dart iyi öğrenirsen ikisini bilrikte çok daha fonksiyonel götürürsün
