### ISSUE TITLE
Programlama Dili Öğrenme Hakkında

### ISSUE THREAD

**Issue by onurumsunx** [VB10/vboverflow#17]
İngilizce bilmeden sadece türkçeyle iyi ve eksiksiz bir biçimde programlama dili  öğrenebilir miyim bunun için önerebileceğiniz herhangi bir kurs kaynak vs. var mı yoksa ingilizce öğrendikten sonra programlama dilini öğrenmeyi mi tavsiye edersiniz.Çalışmak veya kendini geliştirmeyle ilgili bir sorunum yok tabiri caizse köpek gibi çalışırım.

**Comment by Barismano** [comment]
Eğer ingilizce bilgin sıfır ise biraz zorluk çekebilirsin bunu sebebi türkçe kaynak sıkıntısı. Ama onun dışında başlangıç ve orta seviyede programlama öğrenebilirsin türkçe kaynak bir çok platformda mevcut ama komplike bir durumla karşı karşıya kaldığın zaman ingilizce kaynak okumak gerekebiliyor

**Comment by Barismano** [comment]
Bu arada Mate Translate diye bir chrome eklentisi var seçtiğin metinleri hızlı bir şekilde dil farketmeksizin çevirmeni sağlıyor ben zorlandığım yerlerde onu kullanıyorum tavsiye ederim


https://chrome.google.com/webstore/detail/mate-translate-%E2%80%93-translat/ihmgiclibbndffejedjimfjmfoabpcke

**Comment by VB10** [comment]
@onurumsunx selamlar
bir çok site alt yazı desteği veriyor aslında bu en başta çok işine yarayacktır misal pluralsight gibi siteler youtube dada var bunları bol bol kullan, paralel de ingilizceni teknik seviyede kavramlarla okuya okuya çevireceksin
,
Programlama dili öğrenme konusunda c# gibi java gibi yıllarını almış dillerle de başlayaiblir dart swift kotlin gibi dilin birini seçerek bu dilin strcture yapısını vs öğreniblirisn. hiç çekinmeden.

Bende google translate plugini kullanıyorum @Barismano chromdaki.
Lütfen köpek gibi çalışacağın nokta algoritma kurma bunları yönetme vs olsun üzerinede ui react flutter giib eklemeler ile gayet iyi olacaktır.
