### ISSUE TITLE
Flutter Hakkında soru.

### ISSUE THREAD

**Issue by sswean** [VB10/vboverflow#170]
1. Mobil uygulama yapmak istiyorum elimde Windows cihaz var hem anroid hem iOS cihazlara uygulamamı yüklemek istiyorum ama sanırım İOS tarafı için yükleme yapılmıyor. Şimdi ben Windows’ta kodladığım uygulamayı MacBook cihazlara aktarabilirmiyim yükleme yapmak için.
2. Elimde Ui var Figma tarafından yaptırılmış bunu uygulamaya nasıl yansıtabilirim (bilgisizim Yazılım öğrenmeye çalışıyorum, yani amacım bilgilenmem bu tarz konularda)
3. Sizce Nasıl ilerlemeliyim flutterda önerebileceğiniz kaynak, ders siteleri var mı (udemy gibi)
4. Bu yaptığım uygulamayı websitesine dönüştürebilirmiyim?

**Comment by VB10** [comment]
1- herhangi bir cross platfrom dotnet olsun java olsun ki flutter da dahil kullabilrisin
2- ekranları widget widget kodlayarak belrili tema ve size işlemlerini yaparak yapabilrisn flutter kendi sayfasında codelablar var onlara bakarın
3- [flutter.](https://flutter.dev/learn) bakabilrisin
4- evet  http://sesiniduydum.com/ misal flutter ile yazdık her yerde çalışıyor repo da benim public

**Comment by sswean** [comment]
Merhaba Hocam, Tekrardan selamlar.
Flutter'a 7 saatlik Dart Eğitimi videonuz ile mi başlayayım? 
Öyle yapmam daha mı iyi olur sizce, 
Yazılım hakkında bilgi ve tecrübem yok.

**Comment by sswean** [comment]
Merhaba Hocam, Tekrardan selamlar.
Flutter'a 7 saatlik Dart Eğitimi videonuz ile mi başlayayım?
Öyle yapmam daha mı iyi olur sizce,
Yazılım hakkında bilgi ve tecrübem yok.?
