### ISSUE TITLE
Animated ve Key Kavramları Coin Videosu

### ISSUE THREAD

**Issue by burakcevheroglu** [VB10/vboverflow#171]
Merhabalar hocam, yaklaşık 1 yıl önce çektiğiniz linkini bırakacağım bu videodaki mantık ile bir uygulama tasarlamaya çalıştım. Mantığı tamamıyla anladım ve biraz daha temiz bir kod olarak yazdım ama animasyon çalışmıyor.

Yazdığım kodda 4 farklı karakter var ve alignları pozisyona göre değişiyor. Videodaki gibi List<Widget> olarak Stack içine veriyorum. Sadece alignları değiştirdiğimizde, widgetların sırasını değiştirmediğimde sorun olmuyor ama birbiri üstüne gelmemesi için widgetların sıralamasını değiştirdiğimde keyler doğru da olsa animasyon çalışmıyor. Birinci durumdaki gibi kullanırsam da üst üste geliyor ve karakterler karışıyor. Bu widgetların üst üste gelmemesini nasıl çözebiliriz?

Videodaki fikir çok güzel hocam ayrıca teşekkür ederim bunun için. Kodların daha temiz olduğunu düşündüğümden isterseniz video çekip paylaşabilirsiniz, benim için sorun olmaz.

Video Linki: https://www.youtube.com/watch?v=JG-aYMS2AWU
Projem: https://github.com/burakcevheroglu/Character-Select-Flutter

**Comment by burakcevheroglu** [comment]
Eğer widget sırasını değiştirmezsem animasyon oluyor ama böyle gözüküyor, widget sırasını değiştirirsem de animasyon bozuk bir şekilde çalışıyor. Keylerde sıkıntı olduğunu sanmıyorum.

![](https://i.ibb.co/gyLtf68/Simulator-Screen-Shot-i-Phone-14-Pro-Max-2023-02-19-at-17-33-09.png)

**Comment by VB10** [comment]
@burakcevheroglu projeyi cekip bakma sansim yok ama eger animasyon olmuyorsa keylerde bir problem olusmus olabilir ona bak derim

**Comment by burakcevheroglu** [comment]
keyle alakalı bir şey olduğunu sanmıyorum ya çözemedim daha aktif sorun malesef

**Comment by VB10** [comment]
stackoverflowa açıp oradan destek alarak ilerleyelim buradan cevap çıkmayacak @burakcevheroglu
