### ISSUE TITLE
Firebase'de Firestore/Realtime veritabanlarında search işlemi nasıl yapılır?

### ISSUE THREAD

**Issue by SerdarYildiz06** [VB10/vboverflow#172]
Örneğin kullanıcı "serd" yazdığında users tablosundaki username'i "serd"ı içeren kullanıcıları dönmesi gerekiyor, (Serdar vs.)

**Comment by VB10** [comment]
bunu yapmak icin full text serach baglamak geerekiyor bunu hazir hizmet veren oldugu gibi kendi sunucunda search 

https://medium.com/firebase-developers/firestore-full-text-search-with-meili-b452e41e539c
https://firebase.google.com/docs/firestore/solutions/search

https://www.meilisearch.com/

**Comment by SerdarYildiz06** [comment]
Teşekkürler hocam
