### ISSUE TITLE
Speech-to-Text

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#173]
Merhaba ses dosyasını metne dönüştürmek istediğim bir projem var. Google Speech ve Speech to Text kütüphaneleri ile birkaç deneme çalışmam oldu. Fakat amacım uzun süreli (1 dakika üstü) ses kayıtlarını metne dönüştürmek. Henüz bir sonuca ulaşamadım. Fikir vermek isteyen, geçmiş projelerinde bu tarz bir çalışma yapan var ise çok memnun olurum. İyi çalışmalar.

**Comment by VB10** [comment]
bu konuda benim bir fikrim yok ondan bir şey söyleyemedim kolay gelsin
