### ISSUE TITLE
Flutter, Bluetooth, Beacon

### ISSUE THREAD

**Issue by mehmetozkn** [VB10/vboverflow#175]
Merhabalar,
Bir Beacon cihazımdan yayılan verileri Flutter uygulamasında görmek istiyorum.
flutter_beacon, beacon_broadcast, beacon_flutter ve beacons_plugin gibi paketleri denedim kaynak kodlarını çalıştırdım ama çoğu çalışmıyor hatalar veriyor. beacon_broadcast paketi çalışıyor fakat veriler gelmiyor. 
Beacon cihazdan gelen veriyi çekmek Flutter ile mümkün değil mi ? Flutter'ın Bluetooth ve Beacon paketleri yeterli değil mi ? Yardımcı olursanız çok sevinirim.

**Comment by sinanhaci** [comment]
https://pub.dev/packages/flutter_reactive_ble

Ben bu paketi kullanarak low energy ile çalışan bir hoparlör uygulaması yaptım ve canlıda. Paket philips tarafından Hue ürününde kullanılmak üzerine geliştirildi, bu sebeple ihtiyaçlarını karşılıyorsa bunu kullanabilirsin.

**Comment by mehmetozkn** [comment]
Başka bir şekilde sorunumu çözdüm teşekkür ederim.
