### ISSUE TITLE
Material3 Dropdownmenu width sorunu

### ISSUE THREAD

**Issue by yasinertune** [VB10/vboverflow#176]
Herkese merhaba, Material3 componentlerinde bulunan Dropdownmenu'yü projeye ekledim. Şuan üstünde çalıştığım proje hem web hemde mobil ile uyumlu. Dropdownmenu width parametresi alıyor. Width parametresine dinamik width vermeme rağmen dropdownmenu nün boyutu ilk oluştuğu gibi kalıyor. Ekranı büyütüp küçülttüğümüzde dinamik yapıyı bozuyor. Bu componentin linkini buraya bırakıyorum.  Fikir vermek isteyen, geçmiş projelerinde bu tarz bir sorunu çözen var ise çok memnun olurum. İyi çalışmalar.

[https://api.flutter.dev/flutter/material/DropdownMenu-class.html]

**Comment by VB10** [comment]
yasin bu tarz problemleri doğrudan stackoverflow olsun flutter reposu olsun açarsan daha hızlı dönüş alırsın eğer core pakette bir sorun var ise. şuan benim önüme böyle bir sorun gelmediği için bir şey diyemedim
