### ISSUE TITLE
Some Clean Code Question

### ISSUE THREAD

**Issue by alpuysal** [VB10/vboverflow#178]
- Bu iki kullanım arasında fark ne olabilir? 
- İkisinde de class ın özelliklerini saklamış olmuyor muıyum ?

```
class AppRouter {
  static final GoRouter _router = GoRouter(
    routes: <GoRoute>[],
    errorBuilder: errorWidget,
  );

  static GoRouter get router => _router;
}
```

```
class AppRouter {
  AppRouter._init();
  static final GoRouter _router = GoRouter._init();
  static AppRouter get router => _router;
}
```

**Comment by VB10** [comment]
signleton kullanımın bir kaç  çeişidi var bu ikisi özelinde çok anlamadım ama detayına bakarsan farklarını bulabilirsin
https://stackoverflow.com/questions/7790185/singleton-lazy-vs-eager-instantiation @alpuysal
