### ISSUE TITLE
Native'den diğer alanlara açılma

### ISSUE THREAD

**Issue by Flattih** [VB10/vboverflow#179]
Selamlar veli abi sektörle alakalı size danışmak istediği bir konu var twitter'da tweetinizin bir kısmında şöyle demiştiniz;
misal java-kotlin biliyorum native yazıyorum diyerek işi alıp içeride flutter yazabilir veya backend alanına girebilirsiniz.
Buradan native iş ilanına başvurup orada flutter backend yazabileceğimiz çıkar mı biraz detaylı anlatabilir misiniz?

**Comment by VB10** [comment]
şöyle bizim arkadaşlarımızda çok oluyor  genelde şirketlerin iç projelerinde veya yapmak istedi alt projelerde bu tarz tekonlojiler ile yazalım deniyor bu durumda ekiplerde core kadrolar girmek istemediği için ya yeni gelen yada yenilikçi arkadaşlar ya kötü senaryoda ekipte çok tutunamayanları koyuyuorlar.

Burada önemli olan o işe gireceğin yeri iyi analiz edip önce parasal özgürlüğüne koşmak paralelinde teknik yeteneğini geliştirip istediiğin alana yönelmek diyeiblirim @Flattih

**Comment by josephiino** [comment]
Hocam backend için bugün nodejs dökümantasyonu çalışmaya başladım fakat ileride iot cihazlarla çalışmak istediğim için hem gömülü yazılım hem backend için rust mı çalışmam lazım sonuç olarak node ile hızlı bir şekilde sektörde bulabilirim kendimi siz ne önerirsiniz
