### ISSUE TITLE
Flutter File Download Directory

### ISSUE THREAD

**Issue by abdullahkaraboga** [VB10/vboverflow#18]
Merhaba hocam,

Flutterda bir dosyayı /klasor/klasor/klasor/dosya.uzantı şeklinde spesifik bir directory'e download etmek istiyorum. Flutter bunu her iki platform için de destekliyor mu ?

**Comment by VB10** [comment]
Spesificten kasit tabiki app icerisinde application directroy veya temp olark birini secip altinda o klasorleri sen creat ede ede yapabilirsin. downloads routue altinda vb/ahmet/x.pdf gibi

https://pub.dev/packages/path_provider
