### ISSUE TITLE
Native teknolojiler için nereden hangi kurs alınmalı?

### ISSUE THREAD

**Issue by eliffozkann** [VB10/vboverflow#180]
Merhabalar, 
Cross platformu olarak Flutter biliyorum ve bu alanda kendimi geliştirmeye devam ediyorum. Kendimi daha fazla geliştirebilmek adına native de android öğrenmek istiyorum. Kotlin ve Java iyi bir tercih olur mu bu yolda? Ek olarak Kotlin ve Java'yı nereden öğrensem hangi kursu alsam daha iyi olur?

**Comment by VB10** [comment]
bence çok güzel bir yol java eski ve ölmüş gözüksede gücünde hiç eksilme yok geçenlerde java 20 çıkmıştı yanlış hatırlamıyorsam. özellikle backend vs yazmak için java güzel olabilir ama yeni başlayan arkadaşlara ben direk kotlin öneriyorum.

ben çok içerisinde olmadığım için daha kendime yeteri kadar baktım bugüne kadar öyle çok kurs vs açıkcası bilmiyorum ama bunlara bakabilir üstüne misal flutter da öğrendiğin bir tekniğin bu karşılığı nasıl olurdu acaba diye araştırabilirsin.
@eliffozkann 


https://www.udacity.com/course/developing-android-apps-with-kotlin--ud9012
https://developer.android.com/courses/android-basics-kotlin/course
