### ISSUE TITLE
Macbook Oneri

### ISSUE THREAD

**Issue by osmandemiroz** [VB10/vboverflow#181]
Mobil gelistirici icin 25 30 araliginda macbook onerileriniz nedir aklimda 8gb 512gb m1 pro var fikriniz nedir

**Comment by VB10** [comment]
selam osman şimdi orada önerim şu şekilde olacak
1- ikinci el problemim olmaz dersen bence ikinci el m1 pro vs 16 ram alabilirsin burada önemli olan bizim için ram pro olmsada da olur
2- sıfır dersen m2 m1 farketmez hatta eski modellerden bile olur 16 ram minumum uyar.
3- mac mini tarzı da alabilirsin eğer ekranın varsa genelde evde olunduğu için iyi oluyor kasa performansı da iyi.

benim tercihim ilk bilgisayar ikinci el olması iyidir
** ekran 13 öneririm bende misal o var çok büyük sorun oluşturmaz
bunlar uygundur sıfır için
https://www.hepsiburada.com/apple-macbook-air-m1-cip-16-gb-512-gb-macos-13-3-inc-qhd-tasinabilir-bilgisayar-uzay-grisi-z124m116512-tq6-pm-HBC00001D3U82
