### ISSUE TITLE
Swift mi yoksa Cross Platform yazilimlari mi (flutter react native)?

### ISSUE THREAD

**Issue by loneroust** [VB10/vboverflow#182]
Oncelikle merhaba Veli Abi seni severek takip ediyorum vakit buldukca videolarini izleyip fikir sahibi de olmaya calisiyorum.
Ben bilgisayar muhendisligi 2.sinif ogrencisiyim ve yazin staj yapmam gerekli su anda da Flutter ogrenim surecinin cok baslarindayim, baslamadan once arastirmami da yapmistim reactla arasinda tereddutsuz fluttera baslamak istemistim (bu konuda da fikirlere acigim) ama turkiyede gerek is alani olsun staj imkanlari olsun cok fazla yok sorum su olacak ilerde mobil uygulama gelistirici olmak istiyorum fakat cross platform app ve web icin de etkili olan flutter ya da react nativele mi devam etmeliyim yoksa swift ogrenmeye mi baslamaliyim? Ya da once sunu ogren sonra vaktin kaldiginda da digerine bak secenegi mantikli mi oyleyse hangisine oncelik vermemi tavsiye edersiniz? Simdiden cok tesekkur ederim.

**Comment by VB10** [comment]
işin mutfağı her zaman native swift or kotlin öğrenmek şart. unutmamak gereken ana nokta swift mi dart mı tartışılır js tartışılır dil ile dilleri karşılaştır ki ne öğrendiğimizin farkında olalım.

sektördün durumu ortada linkedinden bakıp ilerleeyebilrisin native yolu flutter react ne dersen orada hepsi mevcut ona göre yolunu çözebilriisn
