### ISSUE TITLE
How to provide Main View Model with Mobx.

### ISSUE THREAD

**Issue by ismailcaakir** [VB10/vboverflow#183]
Selamlar,

Uygulamamda senin anlattığın mobx derslerinden esinlenerek hatta birebirini alarak mvvm kullanıyorum. Fakat bir sorum olacak, uygulamanın genelinde sayfadan bağımsız bir state management yapmak istiyorum. Örneğin abonelik başladığında tüm uygulamada herhangi bir sayfadaki görseller reklamlar vesaire  duruma göre değişecek. Bunu mobx ile yapabilir miyim? Yoksa changeNotifier  mı kullanmalıyım. Uygulamayı genel base bir model ile sarabilir miyim. Sonrasında bu modeli tüm sayfalarımdan güncelleyebilir miyim.

**Comment by VB10** [comment]
mobx veya provıder bu cok onemli değil aslında burada amac observer bir yapı kurmak onlar olmadan dahi olur. ara paketler sadece kullanımı kolaylaştırır.
mobx dersen en üstte viewmodel yaar observer ile sarmlarsan ona göre o değişiklikten tüm sayfalar etkilenir buna dikkat etmek gerekir.
