### ISSUE TITLE
FlutterError: Software caused connection abort && Failed host lookup: 'api.xyz.com'

### ISSUE THREAD

**Issue by kamxy** [VB10/vboverflow#185]
Herkese selamlar,

Uygulama da http isteklerinde bazı kullanıcılarda crashlitycs üzerinden bu hataları alıyorum isteklerimde. 

`Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Failed host lookup: 'api-lb.appfurther.io'. Error thrown Init User.
       at IOClient.send(io_client.dart:88)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at get.<fn>(http_custom.dart:47)
       at ._withClient(http_custom.dart:256)
       at UserController.initUser(userController.dart:33)
       at LoadingScreenState.checkRequirements(loading_screen.dart:172)
       at LoadingScreenState.asyncInits(loading_screen.dart:121)`

veya 

`Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Connection timed out. Error thrown null.
       at IOClient.send(io_client.dart:88)
       at BaseClient._sendUnstreamed(base_client.dart:93)
       at get.<fn>(http_custom.dart:47)
       at ._withClient(http_custom.dart:256)
       at ReaderViewController.getConfig(readerViewController.dart:35)`

gibi hatalar alıyorum. ilk bakışta internet problemi olarak gözükse bile bu istekler atılmadan internet kontrolü yapıyor ve sonrasında bu istekleri atıyorum. 
internette bulduğum çözümler olarak 

`<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />`
` android:usesCleartextTraffic="true"`

denedim olmuyor konu hakkında bir fikriniz, çözümünüz var mıdır ? teşekkür ederim.

kodum basitce budur 

`try {
      final url = this.routes.userRoutes.getSettings;

      // Send the request
      final response = await httpCustom.get(
        url,
        headers: await HeaderUtils.authorizedGet(),
      );
      var responseJson = jsonDecode(response.body);

      User user = User.fromJson(responseJson['user']);
      Settings settings = Settings.fromJson(responseJson);
      await storage.write(key: StorageKeys().user, value: user.toString());
      await storage.write(
          key: StorageKeys().settings, value: settings.toString());
      sendSuccesLog(funcName: "initUser");
      return user;
    } catch (e, stack) {
      FirebaseCrashlytics.instance.recordError(e, stack, reason: 'Init User');
      checkNetworkConnection(funcName: "initUser");
      return null;
    }`

**Comment by VB10** [comment]
bu sanırım ssl vs ile alakalı sunucu üzerinden geliyor aslında header vs param ekleyerek çözülebilir @kamxy
