### ISSUE TITLE
firebase_ui_auth paketini projeye ekleyememe

### ISSUE THREAD

**Issue by afurkanyildiz** [VB10/vboverflow#187]
firebase_ui_auth paketini eklemeye çalıştığımda sürekli olarak uyumsuzluk sorunu hatası alıyorum, sizin videonuzdaki sürümleri kullanınca da aynı güncel sürümleri kullanınca da, intl ^0.17.0 olarak görünüyor proje de sürekli olarak flutter_ui_auth ise intl ^0.18.0 ‘ı desteklediğini söylüyor,

intl ^0.17.0 iken:

Because every version of flutter_localizations from sdk depends on intl 0.18.0 and firebase_ui_localizations >=1.0.0-dev.1 depends on intl ^0.17.0, flutter_localizations from sdk is incompatible with firebase_ui_localizations >=1.0.0-dev.1.
And because firebase_ui_auth >=1.1.11 depends on firebase_ui_localizations ^1.2.0, flutter_localizations from sdk is incompatible with firebase_ui_auth >=1.1.11.
So, because firat_bilgisayar_sistemleri depends on firebase_ui_auth ^1.1.17 which depends on flutter_localizations from sdk, version solving failed.

Intl ^0.18.0 yapmaya çalıştığımda ise:

Because firebase_ui_auth >=1.1.11 depends on firebase_ui_localizations ^1.2.0 which depends on intl ^0.17.0, firebase_ui_auth >=1.1.11 requires intl ^0.17.0.
So, because firat_bilgisayar_sistemleri depends on both firebase_ui_auth ^1.1.17 and intl ^0.18.0, version solving failed.

Hatasını alıyorum.

Flutter pub upgrade ve flutter pub outdated yaptığımda yine aynı hataları alıyorum.

**Comment by VB10** [comment]
Bunu stackoverflow açmalısın
