### ISSUE TITLE
Snippet or Key Bindings

### ISSUE THREAD

**Issue by efekangvndk** [VB10/vboverflow#188]

**Comment by aio001** [comment]
Anladığım kadarıyla Flutter'da sık kullanılan snippet'ları istiyorsunuz. Bunun için hali hazırda zaten vscode extensionlar var fakat kendiniz özelleştirmek istiyorsanız. Komut paletinden snippet yazıp configure snippets diyerek özelleştirme yapabilirsiniz. Benim kullandığım snippetlar şöyle:
Belli bir el alışkanlığı ile çok yardımcı olabiliyor. 
![image](https://user-images.githubusercontent.com/100313333/230078037-b6103eb2-8a96-4dfe-ae99-f17a7545e5c3.png)
`{
	"add material": {
		"scope": "dart",
		"prefix": "material",
		"body": "import 'package:flutter/material.dart';",
		"description": "fast material library"
	},

	"fast getter": {
		"scope": "dart",
		"prefix": "fastGetter",
		"body": "$1 get $2 => $3;",
	},

	"fast static const": {
		"scope": "dart",
		"prefix": "staticConst",
		"body": "static const $1 = $2;",
		"description": "fast static const"
	},
	"Fast Icon Add": {
		"scope": "dart",
		"prefix": "ficon",
		"body": "Icon(Icons.$1)",
		"description": "Fast icon"
	},

	"Singleton Eager": {
		"scope": "dart",
		"prefix": "singletonClass",
		"body": [
		  "class $1 {",
		  "static $1? _instace;",
		  "static $1 get instance {",
		  "_instace ??= $1._init();",
		  "return _instace!;",
		  "}",
		  "$1._init();",
		  "}"
		],
	  },

	"abstract class ~ view model":{
		"scope": "dart",
		"prefix" : "viewmodel",
		"body": [
			"class $1ViewModel = _$1ViewModelBase with _$$1ViewModel;",
			"abstract class _$1ViewModelBase with Store, BaseViewModel {",
  			"@override",
  			"void setContext(BuildContext context) {",
			"viewModelContext = context;",
			"}",
			"@override",
			"void init() {}",
			"}"
		],
	}

	
}`

**Comment by aio001** [comment]
unutmadan ben de Veli hocamdan görmüştüm daha detaylı anlatımı [bu linkte var.](https://youtu.be/euw6Np2Z9n4?list=PL1k5oWAuBhgXdw1BbxVGxxWRmkGB1C11l)

**Comment by efekangvndk** [comment]
çok saolun çok teşşekür ederim .

Oğuz Kağan Güllü ***@***.***>, 5 Nis 2023 Çar, 15:21
tarihinde şunu yazdı:

**Comment by efekangvndk** [comment]
yanlız size bir soru daha sorsam veli hocamın kullanmış olduğu apple phone
similatrörü nedir acaba

efekan güvendik ***@***.***>, 14 Nis 2023 Cum, 16:02 tarihinde
şunu yazdı:

**Comment by aio001** [comment]
Windows kullanıyorsanız kullanamazsınız. Mac kullanıyorsanız xcode'da similators kısmında var.

**Comment by efekangvndk** [comment]
hımm anladım çok saolun altarnatif olarak android studio var sanırım
elimizde bir tek :D bende mac alıcam ama yaz tatilinde malesef :D birde
sizlere acaba vscode kullanıp android studio ya işlem yapabilirmiyiz
flutter

Oğuz Kağan Güllü ***@***.***>, 15 Nis 2023 Cmt, 10:30
tarihinde şunu yazdı:

**Comment by VB10** [comment]
@kagangullu teşekkürlerr
