### ISSUE TITLE
Tab barda diğer sayfaya geçerken dispose metodu çağrılmıyor

### ISSUE THREAD

**Issue by Mryuksel101** [VB10/vboverflow#189]
Tab bar yapımın bir sayfasında banner reklam kullanıyonıyorum. Tab barımdaki başka sayfaya geçsem bile banner reklamım dispose olmuyor ve   "onAdLoaded" diğer sayfalarda da çalışıyor. CupertinotabScafold kullanıyorum

```dart
  listener: BannerAdListener(
          onAdLoaded: (ad) {
            setState(() {
              log("_bannerAd = ad as BannerAd;");
              _bannerAd = ad as BannerAd;
            });
          },
          onAdFailedToLoad: (ad, err) {
            debugPrint('Failed to load a banner ad: ${err.message}');
            ad.dispose();
          },
        ),



```

**Comment by VB10** [comment]
@Mryuksel101 buradan bır sey anlasılmıyor dispose olmaz tab dispose düşmediği için tabview içinde yaz disposei yada o widget özelinde
