### ISSUE TITLE
Arkaplanda lokasyon gönderme

### ISSUE THREAD

**Issue by Barismano** [VB10/vboverflow#19]
Bir kurye uygulaması üzerine çalışıyorum kurye uygulamayı kapatsa bile 15 saniye aralıkla  kuryenin o anki konumunu database e göndermek istiyorum 3gündür bu konu üzerine çalışıyorum pub devde bulduğum pluginler ya hata veriyor yada sürümleri eski bunu nasıl yapabilirim?

**Comment by VB10** [comment]
Selamlar @Barismano bu konu tabiki şöyle yapmanı öneririm. doğrudan bir platform seçersen misal android orada uygulamayı bacgkorund servis veya ile bağlayıp bunuda istersen flutterın pigeon ile bağlarsın native tarafadan o kodu çağrırsın.
https://pub.dev/packages/workmanager

Zira ios tarafı için bu işi yapmanın benim bildiğim yolu map uygulaması işaretleme ama backgorundda dineleme yapmaya ios genel olarak izin vermiyor bilidğim yaptığımız applerde 5dk gibi bir süresi sonra siliyor burada slient notificotn bakıpğ bunu telefona gönderip oradan bilgi almayı yapabilirisin veya telefonu uyandıraiblirisn

**Comment by Barismano** [comment]
Selamlar Hocam "background_locator" adlı plugin ile çalıştırmayı başardım en sonunda uygulama kapatılsa bile plugindeki interval özelliği sayesinde 10-15 saniyede de bir konum gönderiyor. Yardımlarınız için çok teşekkürler hocam iyiki varsınız

Plugin : https://pub.dev/packages/background_locator

**Comment by VB10** [comment]
cok tesekkür ederim barış iyiki sende varsın burada bu çözümünüde paylaşıp başka arkadaşlara destek olduğun için

**Comment by aea91** [comment]
> Selamlar Hocam "background_locator" adlı plugin ile çalıştırmayı başardım en sonunda uygulama kapatılsa bile plugindeki interval özelliği sayesinde 10-15 saniyede de bir konum gönderiyor. Yardımlarınız için çok teşekkürler hocam iyiki varsınız
> 
> Plugin : https://pub.dev/packages/background_locator

IOS ta app kill edildiğinde de konum gönderiyor mu bu paket sayesinde?

**Comment by Barismano** [comment]
Şuan sadece android üzerine çalışıyorum yakın zamanda projeyi iosa build edicem o zaman yazarım buraya.Pluginin sayfasında ios kurulumuda var bir bak istersen

**Comment by aea91** [comment]
> Şuan sadece android üzerine çalışıyorum yakın zamanda projeyi iosa build edicem o zaman yazarım buraya

Teşekkürler. Gececilere selam olsun :)

**Comment by Barismano** [comment]
uyumak yok :D

**Comment by EmreKabali** [comment]
Bilgi için teşekkürler arkadaşlar
