### ISSUE TITLE
Flutterda hive paketini her kullandığımda aynı hatayı alıyorum terminaldeki installerı yapmama ragmen aynı hatayı alıyorum

### ISSUE THREAD

**Issue by osmandemiroz** [VB10/vboverflow#190]
![Görüntü 3 04 2023 18 28](https://user-images.githubusercontent.com/103650538/229556600-bfa86786-2f59-46f1-b946-2d6132e33848.jpeg)

**Comment by osmandemiroz** [comment]
sorunu çözdüm 
arch -x86_64 sudo gem install ffi 
komutları ile siz de aynı sorunu yaşıyorsanız çözebilirsiniz

**Comment by VB10** [comment]
@osmandemiroz cevabı paylaştığın için teşşekkürler
