### ISSUE TITLE
Bluetooth ile Veri Aktarım Sorunu - Platform Exception

### ISSUE THREAD

**Issue by yavuzfk** [VB10/vboverflow#191]
### Açıklama
- [flutter_bluetooth_serial](https://pub.dev/packages/flutter_bluetooth_serial)  paketi kullanımında  [issue](https://github.com/edufolly/flutter_bluetooth_serial/issues/174) de bulunan hatayı alıyorum, başkaları da aynı hatadan muzdarip.
- İlgili paket örneğini kullanmaya çalışıyorum. Kodlara erişebilirsiniz.
- Paket amacı bluetooth ile iki cihaz arasında iletişim ve veri alışverişi yapmak. Cihazı bulup seçtikten sonra veri gönderim esnasında PlatformException atıyor.

### Notlar:
- Ana amaç BLE kullanmadan cihazlar arasında veri alışverişi yapmak. QR yönteminde data boyutu maalesef çok küçük. BLE kullanan paketler android cihazımı göremediği için bluetooth classic teknolojisi kullanan paketleri deniyorum. BLE kullananlar kulaklık, mouse gibi cihazları görmekle beraber denediğim telefonları göremiyor. 
- Farklı yöntem, tavsiyelere açığım.

#### Teşekkürler

**Comment by yavuzfk** [comment]
- [wifi-direct](https://pub.dev/packages/flutter_p2p_connection)  paketi ile veri transferini hallettim. Soket açıp bağlanma yolu ile kolayca veri aktarılabiliyor, teşekkürler.

**Comment by VB10** [comment]
@yavuzfk cevabı paylaştığın için teşekkürler
