### ISSUE TITLE
firebase giriş yapma sorunu

### ISSUE THREAD

**Issue by seyitarvis** [VB10/vboverflow#192]
Uygulamayı başlatıp kayıt olup ardından giriş yaparsam sorun yok, ama uygulamayı açtığımda direkt daha önce oluşturduğum bir kayıtla giriş yaparsam eğer uygulama duruyor, uygulama sürekli olarak parentdatawidget hatası veriyor ve bununla ilk defa karşılaşıyorum. Bu bir widget hatası olduğu için sebebin bu olduğunu düşünmüyorum.

**Comment by VB10** [comment]
@seyitarvis bu tarz bir hata bende hiç görmedim tavsiyem stackvoerwloa exception logları ile paylaşman. bu hata muhmteleen firebaseden değil senin kodlarından geliyor

**Comment by seyitarvis** [comment]
Veli hocam selamlar tekrardan. kayıt ol kısmını projemden kaldırmamı söylediği için hoca sorun çözülmemiş olsa da çözülmüştü. Ancak şuan tekrar firestore kullanmam gerekiyor ve sorun net olarak firestore paketini pubsec.yaml eklediğimde başlıyor. Paketle ilgili herhangi bir kodum bulunmamasına rağmen uygulamayı başlattığımda running pod install... olarak bekletiyor ve proje başlamıyor. Ben projeyi vsCodede yazıyorum xCode ile ilgili bi sorun olabilir mi anlayamadım çevremde hiç yaşayan da yok bu problemi kısır döngüde kaldım.
