### ISSUE TITLE
Mobil geliştirici olma süreci, başlama, iç dünya, neler bekliyor, cross ve native, neler yapmalı

### ISSUE THREAD

**Issue by VB10** [VB10/vboverflow#193]
Bir çok arkadaş bu soruyu her yerden soruyor burayı yavaş yavaş büyüterek dolduracağım.

**Öncelikle başlarken muhakkak bu içeriği izlemenizi tavsiye ediyorum hemen hemen tüm sorularınız burada cevap bulacak:**

[![Mobile Development](https://img.youtube.com/vi/PLZmKkqGCBA/0.jpg)](https://www.youtube.com/watch?v=PLZmKkqGCBA)

**Üstüne seçim yapmak bilgisayar mühendisliği ile alakalı soruları buradan:**
#71 

**Youtube kanalında izlemeler için:**

#162 
[![Kanal izleme sırası](https://img.youtube.com/vi/luFkWD2zlF0/0.jpg)](https://www.youtube.com/watch?v=luFkWD2zlF0)

**Native öğrenme için** 
#75

**Comment by Pehsacinp** [comment]
Jr Flutter pozisyonu neleri bilmesi neleri yapması gerekir ui yapsa sadece yeterli olur mu?  teşekkür ederim şimdiden cevabınız için.
