### ISSUE TITLE
Yakın Ağ Paylaşım Uygulamaları hakkında görüşler

### ISSUE THREAD

**Issue by mertssmnoglu** [VB10/vboverflow#194]
[LocalSend](https://github.com/localsend/localsend) isimli bir yakın ağ paylaşım uygulaması mevcut bilgisayar-telefon arasında bu uygulamayı iletişim için bu uygulamayı kullanıyorum. Hem open source olması hem de aktif olarak geliştiriliyor olması benim işime geliyor ve birebir olmasa bile AirDrop alternatifi olma yolunda ilerlediğini düşünüyorum. Apple ekosistemindeki kadar rahat olmasa bile iş gördüğünü ve kalabalık ortamlarda fotoğraf gönderilecekken "iPhone'u olanlar airdrop atsın kalanlara da WhatsApptan atarız" muhabbetine ortak bir dil olacağını düşünüyorum. "Herkesde localsend vardı dimi açsanıza" ile iş bitirilebilir gibi geliyor.

Ben tek bir uygulama üzerinden anlattım ama tabi bu işin birçok farklı kısmı var. Sizlerin görüşleri nelerdir?

**Comment by VB10** [comment]
bence çok güzel bir düşünce tabi bu tarz şeylerde insan güven arıyor network katmanında saklama yada yollanan dataların kalitesi gibi ama bu arkadaşlar onu yapmış gibi duruyor. bu tarz appler hep tutacak ilerleyecek duruyor
