### ISSUE TITLE
Flutter'da WebView tarayıcı versiyonu sorunu

### ISSUE THREAD

**Issue by tolgasozbir** [VB10/vboverflow#196]
Webview_flutter paketini kullanarak bir siteyi uygulama içinde ziyaret etmek istiyorum, fakat şöyle bir problemle karşılaşıyorum: Web sitesini harici bir tarayıcıda açtığımda sorunsuz bir şekilde açılıyor ancak uygulama içinde açmaya çalıştığımda resimdeki hatayı alıyorum. Bu sorunla ilgili pek bir şey bulamadım. Bilgisi olan biri yardımcı olabilirse sevinirim. Şimdiden teşekkür ederim.

Edit: Eski tarayıcı sürümlerinde oluşan bir kodlama problemi nedeniyle belirli bir sürümün altındaki tarayıcı sürümlerini kabul etmiyorlarmış.

<img src="https://user-images.githubusercontent.com/79727679/236845695-41163099-853e-4b7b-bcb1-7a192254f5a5.png" width="256">

Örnek kodum aşağıdaki gibidir:

```dart
final url = Uri.parse("https://kutuphane.uskudar.bel.tr/yordam");

final _webViewController = WebViewController()
..setJavaScriptMode(JavaScriptMode.unrestricted)
..loadRequest(url);

body: WebViewWidget(controller: _webViewController)
```

**Comment by gataman** [comment]
Merhaba, nativede webview.settings içerisinde userAgent belirleyerek tarayıcıların versiyonlarına müdahale edebiliyorduk. Flutterda webview kullanmadım ancak setUserAgent methodu var. Benzer mantık onda da geçerlidir. Aşağıdaki şekilde dener misin? Uygulamayı emulatörden kaldırman, durdurup yeniden çalıştırman vs gerekebilir.

```dart
const userAgent =
        'Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Mobile Safari/537.36';
   
    _webViewController = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setUserAgent(userAgent)
      ..loadRequest(url);

**Comment by tolgasozbir** [comment]
Hocam, teşekkürler. Ben de setUserAgent parametresini kullanmıştım ama çalışmamıştı. Uygulamayı silip tekrar yüklemek gerekiyormuş. Öğrenmiş oldum. Çok teşekkürler, ilginiz ve cevabınız için.
