### ISSUE TITLE
Flutter | Global Management nasıl yapılmalı?

### ISSUE THREAD

**Issue by BerksDev** [VB10/vboverflow#197]
Merhabalar,
Şu anda kafamda oturtamadığım bir iki soru var. Sitenizde global değerler kısmını inceledim ancak aşamadığım noktalar var.

- Cart, Wishlist yapısı kurmam gerek ve bunu global olarak yapmalıyım. Anlamak istediğim nokta Add to Cart, Wishlist gibi global olayları bütün ürün bulunan sayfaların viewmodel'ine yazmamak için nasıl bir yol izlemem gerekiyor?

- API'den gelen verileri sayfanın viewmodel kısmında çekiyorum. Ancak sayfadan sayfaya geçtiğim durumda aynı sayfaya tekrar döndüğümde tekrar bir loading işlemine maruz kalıyorum init içinde kullandığımdan dolayı. Bunun yaşanmaması için ne yapmam gerekiyor?

**Comment by VB10** [comment]
- ilk yapı için bu cart işlerini yönetecek tüm katmanlardan bağımsız ve alt katmanlara haber verecek bir layer olmalı misal cartcontext ve bunu dinleyen obsverver katmanlar. bu sayede carttan etkilenenleri burası alacak ve bir viewmodele koymadığın için işler karışmayacak
- ikinci kısımda global kullancağın verileri hep bir ayrı yerde tutup initlerinde buradna okuyarak yoksa apiye git demen lazım
