### ISSUE TITLE
Ios Development konusunda hangi yönteme ağırlık vermek gerekir?

### ISSUE THREAD

**Issue by urazalkis** [VB10/vboverflow#199]
Merhabalar,flutter geliştiriciliğinin yanında ios geliştirmeye de merak salmaktayım fakat ios dünyasında piyasada storyboard mı yoksa no storyboard snapkit vb yöntemler mi daha fazla kullanılmakta ios developerlar bu konuda rehberlik ederse memnun olurum.Swift ui meselesine girmiyorum çünkü hali hazırda eski yazılmış projelerin neredeyse tamamı uikit ile yazılmış durumda diye biliyorum.Şu anlık yalnızca geleceğe yatırım olarak görülebilir gibi duruyor.Birde ios geliştiriciliği konusunda önerebileceğiniz kaynaklar,şunu bilseydim zamandan tasarruf ederdim gibi diyebileceğiniz şeyler varsa dinlemekten memnuniyet duyarım teşekkürler

**Comment by VB10** [comment]
native konuda şuan en doğru yatırım ukit ve no sb duruyor sektör için ama gelecekte görüldüğü üzere bizi swiftui bekliyor. ki swiftui applerde bir çok yerde uikit kullanıyoruz.

swift dili gücünü iyi bilip
no sb yapısına hakim olma çok önemli

**Comment by osmancan23** [comment]
bende aynı oldayım storyboarddan sa no sb yapısı daha çok kullanılıyor. ilk başta karmasık gelse de storyboarda nazaran daha rahat. ve bence swift dilinin mantıgını oturttuktan sonra kursdan devam etmek yerine proje bazlı gitmen daha iyi olur

**Comment by urazalkis** [comment]
Yorumunuz için teşekkür ederim
