### ISSUE TITLE
(FLUTTER) Base View modelinde loading senaryosu 

### ISSUE THREAD

**Issue by aea91** [VB10/vboverflow#2]
Tüm sayfaları BaseView den türettiğimizde loading işlemini de baseview i manipüle ederek yapmak hakkında ne düşünürsünüz mantıklı mıdır önerir misiniz?

1. Tüm sayfalar baseview den stateless olarak türetilir.
2. Loading işlemi tek yerden baseview de yürütülür (Provider ile)
3. Future işlemler BaseView ile gelen init mehodunda yapılır öncesinde ve sonrasında loading true false ile tetiklenir.

**** BASE VIEW *****
// loading true olduğunda LoadingView gözüküyor
 body: Stack(
          children: [
            widget.onPageBuilder(context),
            context.watch<MainState>().getIsLoading
                ? const LoadingView()
                : Container()
          ],
        ),
*** Sayfa içindeki init işlemi (BaseView ile gelen) ***

  initState: () {
        init();
      },
*** init fonksiyonu ***
   init() async  {
      context.read<MainState>().updateLoading(true); //=> loading set true
     ***  await Future rest api işlemi ***
      context.read<MainState>().updateLoading(false); //=> loading set false
    }

**Comment by VB10** [comment]
Şimdi bu noktada tabi çok yöntem olaiblir baseview ile sayfaları türetip burada method kazandırmak evet iyi bir çözüm olabilir ama şöyle olursa misal

Loadıng {
future request
loading widget

build method {
isloading? cirprgr : child.
}

buradaki child disardan gelir yani senin generic uretigin misal
},

Ikinci olarak sayfa uzerinde yapmak aslinda su sekildede olabilir network layerine yzilir burada bir alert dialog kurlup bu sayede tum sayfalarada ayni loading gosterilir

3 butonlara yazilabilir buda iyi bir cozum olabilir
