### ISSUE TITLE
Marvel projesi inceleme

### ISSUE THREAD

**Issue by mertguven** [VB10/vboverflow#20]
Marvel API kullanarak yaptığım basit bir flutter projesi örneğidir. Projeyi inceleyerek eksiklerimi ve hatalarımı söyleyebilir misiniz?
Proje linki: [marvel_universe](https://github.com/mertguven/marvel_universe)

**Comment by VB10** [comment]
bir kaç isseu açtım ama genel olarak hoşuma gitti temiz tatlı olmuş eline emeğine sağlık
