### ISSUE TITLE
Flutter projelerinde bağımlılıkları yönetme

### ISSUE THREAD

**Issue by SamedHrmn** [VB10/vboverflow#200]
Merhaba , direkt örnek vererek anlatmaya çalışayım:
Flutter mobil projesi X paketini kullanıyor ve bu paket kendi içerisinde örneğin Y paketini kullanıyor. Fakat biz bu Y paketini ana projemizde de ayrıyeten kullanıyoruz. Ana projedeki Y paketi sürümü ise X paketinin Y bağımlılığına etki ediyor. Bu sebeple ana projedeki Y bağımlılığını ya uyumlu sürüme geri çekmek ya da X paketini locale indirip üzerinde oynama yapmak zorunda kalıyorum. Benzer bir sorunu da bazen native taraflı yaşıyorum. Örneğin X paketi sürümü android taraflı bağımlılıklarla düzgün çalışırken iOS tarafı için çakışma yaratıyor. Fakat bildiğim kadarıyla Flutter'da bi paketi android ve ios olacak şekilde ayrı ayrı sürümlendiremiyoruz. Bu yüzden paket iki taraf için de uyumlu olana kadar sürüm güncelleyemiyorum.

Büyük projelerde bunu nasıl yönetmeliyiz? Teşekkür ederim.

**Comment by VB10** [comment]
tabi bu kritik bir case ama native tarafında gelen sorunlar için yapılabilecek en iyi şey o paketin daha dogrusu pluginin üzerine gidip o kodu yazmak. öbür seneryodada androidde şu kasın iosda şu kalsını flutterden yapamıyorsun. flutterde misal ovveride yapmamız gibi.
