### ISSUE TITLE
Flutter ile Yazılan Uygulamayı Native Çevirme

### ISSUE THREAD

**Issue by ferhatiltas** [VB10/vboverflow#201]
Selamlar,
Flutter ile yazılan bir uygulamayı native (Java,Swift) ile yazıp marketlerdeki (Play ve App Store) mevcut Flutter paketi üzerine yeni paketi native ile yayınlayabilir miyiz ?

**Comment by VB10** [comment]
yep problem olmaz burada storelar gelen fw değilde ipa bazlı apk bazlı bakıyor ondan ötürü bir sorun çıkmıyor.
