### ISSUE TITLE
Cupertino UI Android tarafında ekranda nasıl görünüyor ?

### ISSUE THREAD

**Issue by umutyerebakmaz** [VB10/vboverflow#202]
Merhaba aklıma bir soru takıldı ve deneme fırsatı bulamadım. Tecrübeli arkadaşlara sormak istiyorum. Senaryo şu...
Uygulamamda sıkca Cupertino UI kullandım. Cupertino bildiğim kadarı ile iOS un native UI sı na denk geliyor. iOS cihazlarda sorunsuz çalışacağını düşünüyorum. Ama kafamda şöyle bir soru beliriyor. Peki ya Android cihazlarda Cupertino UI ile yazılan componentler Android tarafında kullanıcının ekranına nasıl yansıyor. Sorumu cevaplarsanız büyük bir merakımı gidermiş olacaksınız. Şimdiden teşekkür ediyorum. İyi çalışmalar.

**Comment by VB10** [comment]
cupertino componentler aynı iosdaki gibi gözüküyor burada eğer tek kod yazarsanız aynı çıktıyı alıyorsunuz. Burada platform spesific kullanmak istersek misal 
`CircularProgressIndicator.adaptive()` şeklinde kullanarak iosda kendi compnenti andoride kendi çıktısını görebiliyoruz. flutter hali hazırda bir çok componentde adaptive özelliğini veriyor.

Bu paketteki kullanımda bunu daha kolay ve daha çok widget e geçmiş halde bize sağlıyor
https://pub.dev/packages/flutter_platform_widgets
