### ISSUE TITLE
Kanaldaki flutter news app Hakkında

### ISSUE THREAD

**Issue by balkayunus7** [VB10/vboverflow#205]
Flutter news app kısmında oluşturduğumuz Id Model ve BaseFirebaseModeli abstract tanımlayıp news modeli üzerinde  with ile eklemeye çalışınca hata alıyorum. Sadece İmplement eklememe izin veriyor.Böyle olunca override ettiği için veri gelmiyor. Sorun ne olabilir acaba?

![image](https://github.com/VB10/vboverflow/assets/98759759/1f39a47f-674c-4f24-8840-d68ea273fa7a)
![image](https://github.com/VB10/vboverflow/assets/98759759/0e69954e-1450-4dd3-91c6-68a6a5fe8fd4)

**Comment by balkayunus7** [comment]
Sorunu çözdüm faydalanacak arkadaşlar için alta ekliyorum.
![image](https://github.com/VB10/vboverflow/assets/98759759/68306eb4-ad60-4e4f-90d2-062ec4f3cbbb)
Üstteki kısım analysis_options.yaml dosyasına eklenicek.

**Comment by mrjake34** [comment]
abstract class sadece extends ve implends edilebilir mixin i with ile kullanabilirsin

**Comment by VB10** [comment]
@balkayunus7 bir örnek kod direk paylaşrısan bakayım repo vs buradan görmeedim

**Comment by vikendiserifi** [comment]
abstract class'ı mixin olarak değiştirirsen sorun çözülecektir.
