### ISSUE TITLE
C#, Unity kendini geliştirme

### ISSUE THREAD

**Issue by Bechoarslan** [VB10/vboverflow#207]
Merhaba abi, 4.sınıf digital oyun tasarımı öğrencisiyim son senem ve kendimi geliştirebilmem açısından herhangi bir tavsiyen var mı ? (Şu an c# unity açışından intermediate seviyesindeyim)

**Comment by VB10** [comment]
bora abıyı takıp ederek ileriye gidebilrisn
https://www.youtube.com/watch?v=ianfUtXrntE&list=PLAeDHZeGYg-DYfCgiYiDOG4UaN9Qp1jT7
