### ISSUE TITLE
Gerçek anlamda sıfırdan başlangıç

### ISSUE THREAD

**Issue by mertgulr** [VB10/vboverflow#209]
Hocam öncelikle iyi günler,
Hocam özetleyim. pandemide Bilgisayar programcılığı okudum ne derse girdim ne sınava. Küçüklüğüme veriyorum.
İngilizcem yok kurslara başladım. 
Araştırmacıyım yeterince 3 gündür araştırma yapıyorum ki araştırma yaparken sizi buldum.
Yaptığım araştırma sorduğum tanışlardan aldığım yanıtlar özetle şöyle:
1-C veya muadilleri ile başlamamı önerenler oldu
2-Algoritmayı kavrayıp sonra istediğin dile başlamamı önerenler oldu.
Sorum şu; gerçek anlamda sıfırdan nereden başlamalıyım. algoritmaysa algoritma, dilse dil, matematikse matematik gibi. 
Mobil(flutter) veya backend düşünüyorum. Fakat sorum genele faydalı olması adına benden bağımsız nereden başlanmalı diye sormak istiyorum

**Comment by mrjake34** [comment]
3 gündür yanlış yerlerde araştırma yapmışsın yazılıma yeni başlayacak olan birine dil önerilmez. İlgin olacak alanı önce bulman gerekiyor, yapay zeka mı, mobil mi, gömülü sistemler mi, siber mi?, bir çok alan var önce bütün alanları öğren ilgin olan alana yönel zaten alan seni belli teknolojilere ve dillere yöneltecek sende dili ve teknolojiyi o zaman seçebilirsin. Algoritma bir dile veya yazılım sektörüne özel bir şey değil algoritmayı kavramak için algoritmik düşünceyi benimsemen gerekiyor bunu oyun oynayarak bile yapabiliyorsun zaten

**Comment by mertgulr** [comment]
Dediğim gibi mobil veya backend düşünüyorum. Herkes farklı bir şey diyor. Sizin de önerinizi öğrenmek isterim. Doğru araştırmayı doğru başlangıcı nasıl yapabilirim?

**Comment by VB10** [comment]
@monoxle 

1- sıfırdan başlama yolu kesinlikle basit diller (insanın anlaması yakın) c# swift dart gibi başlamaktan geçiyor. burada amaç öncelikle yazıyorum diyebilmek misal dart için https://dart.dev/codelabs/dart-cheatsheet veya c# için bora abinin youtube kanalına bakabilirisn
2- algoritme vs zaten aslında kavranamz algoritma insanın hayadır bugüne kadar yaptığın her şey bir algoritmadır sadece bunu koda dökmen gerekir. bu kısımda sana yakın gelen dili bulup bol bol tekrardan geçiyor misal bir bakkalda iki kalem alan app gibi. algoritma birde öyle durup durup gelişmez sonuçta hiçbiirmiz uper değiliz koda dokunmak kodun içinde boza boza yazmak lazım
3- backend öğrenirken zaten front ihtiyaç olur orada react flutter vs vs hepsi zamanla gelir
