### ISSUE TITLE
Mobil Uygulama geliştirirken geliştiricinin kâr yüzdesi ne kadar olmalıdır? 

### ISSUE THREAD

**Issue by demirdev** [VB10/vboverflow#21]
1- Bir mobil uygulama geliştirirken sadece geliştirme ve yayınlama ile alakalı tüm işleri yapan bir geliştiricinin uygulamanın kazandırdığı kârdan ne kadar yüzde alması uygundur.

Bunun yüzdesi uygulamaya göre değişiklik gösterir fakat bir öneriye/görüşe ihtiyacım var.

2- Bu uygulamayı geliştirirken geliştirme karşılığı uygulama sahibinden ara ara ücret aldım. Bundan sonraki geliştirme işleri için ücret almayarak gelirdeki kârdan pay almak istiyorum. Yüzde kaç teklif etmem uygun olur?

Teşekkürler.

**Comment by VB10** [comment]
Selam mehmet bu konualar tabiki projesine kişisine göre değişiklik gösterir ancak:
1- Projede mobil geliştirici eğer tüm proje'yi yazıyor backend firebase vs yapıyorsa o projede en az %30 luk bir hakkı olur bu bir yazılım birimidir
2- Eğer only mobile dev ise %10 12 yeterli olabilir
3- Burada yine projenin kapistesi belirlenmeli ilk versiyonlar böyle olabilir sonradan yine %10luk &8 lik bir stock option teklif edilebilir. Güncel sektörde gördüğüm

tabi az gelebilir ama şunu unutmamak lazım bir çok proje bir çok yazılım var yapılıyor yazılıyor yani kimse eşşsiz dğeil eşsiz olan o proje ve takım eğer uyum ve en önemli kısım projenin satışı yani projeyi 100k ya satıp %30 almakla 3milyona satıp %10 almak arasındaki basit fark gibi.
