### ISSUE TITLE
Mssql veri tabanına mac pcden erişim nasıl mümkün?

### ISSUE THREAD

**Issue by seyitarvis** [VB10/vboverflow#211]
Herkese selam, lenovo pc ile .net mssql ile bir api oluşturdum. Buradaki veriler mobil uygulamama çekmek istiyorum ancak lenovoda emülatör kullanmak büyük bir işkence. Mac bilgisayarımdan bu mssql’e bağlanmanın bir yolu var mıdır?

**Comment by VB10** [comment]
@seyitarvis mysql değil .net apine bağlan local host üzerinden aynı wifi de erişebilirsin

**Comment by seyitarvis** [comment]
Swaggeri macbookta aynı wifi üzerinden ayağa kaldırdığımda 500 statuscode veriyor. Swaggeri ya da postmani microsoftta kullanıp apiye macten bağlansam veriler gelir mi yani hocam
