### ISSUE TITLE
Flutter apk sorunu

### ISSUE THREAD

**Issue by kubrasahin** [VB10/vboverflow#212]
Merhabalar 
Flutter uygulamam emülatorde sorunsuz çalışıyor.
Apk aldım ve  login olmaya çalışıyorum ancak veri tabanına kayıtlı kullanıcıyı bulamıyor.
Ama kayıt ekranında yenı kullanıcı kayıtını oluşturabiliyorum.
İnternet erişminede izin verdim ancak sorunun neden kaynaklı olduğunu bulamadım.

**Comment by kubrasahin** [comment]
Bana yardımcı olabilirmisiniz?

**Comment by mrjake34** [comment]
Login Kodlarını yada github reposunu paylaşabilir misin kod olmadan bir şey söylememiz çok zor

**Comment by MehmetKaranlik** [comment]
@kubrasahin Androidde network iznini verdin mi ?

**Comment by VB10** [comment]
@kubrasahin https://stackoverflow.com/a/55606098/6647293

direk cevabın bu
