### ISSUE TITLE
İçinde Expanded widget bulunan sayfamı nasıl Scrollable yapabilirim ?

### ISSUE THREAD

**Issue by cankayalp** [VB10/vboverflow#213]
Aşağıdaki kodda Column widgetını SingleChildScrollView widgetı ile wrapledim fakat hata aldım. Şimdiye kadar Expanded yerine Flexible denedim. Column yerine Flex denedim yine hata aldım. Not: Kodumu henüz temize çekmedim. Kusurlar affola
`body: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: [
          Container(),
          Expanded(
            child: PageView.builder(
              itemCount: imageUrls.length,
              onPageChanged: (index) {
                setState(() {
                  _currentPage = index;
                });
              },
              itemBuilder: (context, index) {
                return Image.network(
                  imageUrls[index],
                  height: 384,
                  width: 307.5,
                );
              },
            ),
          ),`

**Comment by VB10** [comment]
stackoverflowa acabilrisin
