### ISSUE TITLE
Düşük sistem pc de flutter geliştirme

### ISSUE THREAD

**Issue by emirustaoglu** [VB10/vboverflow#214]
Hocam merhaba;

Yaklaşık olarak 5-6 yıldır masaüstü ve web projeleri geliştiriyorum. Kendimi geliştirmek ve yazmış olduğum yazılımlarda da ihtiyaç olmasından dolayı mobil programlamayada geçmek istiyorum. Daha öncede göz ucu ile baktığım flutterı hem çapraz platform desteği hemde nispeten daha kolay öğrenilebildiği (kendimce ve gördüğüm kadarı ile) mobil platforma girişte uygun görüyorum.

Ancak hali hazırda kullanmış olduğum bilgisayarım özellikleri biraz düşük (İntel celeron 1,5ghz işlemci dahili grafik, 8 gb ram) bu bilgisayar ile flutter ile geliştirme yapabilirmiyim veya direk mobil üzerine olmasa da videolarınızdan yararlanarak benzer projeleri web projesi gibi geliştirebilir miyim ?

Yeni bir bilgisayar alana kadar en azından bir yerden başlamak istiyorum ve internette bu soruma pekte bir cevap bulamadım sadece android studio kurmadan geliştirme ile ilgili içerikler gördüm ancak oda olur mu emin olamıyorum. 

Elimdeki projede bitirmem gereken işlerim olduğundan da birebir deneme yapamıyorum maalesef zaman sıkıntısı olduğu için.

Şimdiden cevaplarınız için teşekkür ederim.

Saygılar.

**Comment by VB10** [comment]
bu konuda net bir bilgim yok ama bu gune kadar hic sorun duymadim.
