### ISSUE TITLE
Widget part'larında yapılan ui operasyonları ve logic işlemleri

### ISSUE THREAD

**Issue by vikendiserifi** [VB10/vboverflow#215]
Hocam şu şekil bir yapıda, month_item_widget, home_view'e part-part of ile bağlı. month_item_widget içerisinde yazılması gereken logic'ler ve ui operasyonları nerede yazılmalı? sub widget'lerin home_view_model ve home_view_mixin'le bağlantısı nasıl olmalı? Teşekkür ederim.

![Ekran görüntüsü 2023-08-04 132312](https://github.com/VB10/vboverflow/assets/141434926/81b8241f-dcf4-477a-8650-0c54498e99db)

**Comment by VB10** [comment]
month için bir view model kurup içinde yapabilirisn sub feature adı altında eğer bir feature büyür ama no context ise sub future yap ve içinde cubit bloc viewmodel ile yönetebilirsin üst sınıf asla alt sınıfı bilmemli sadece haberleşmeli datalardan
