### ISSUE TITLE
flutter native 

### ISSUE THREAD

**Issue by yusufkukus58** [VB10/vboverflow#216]
hocam merabalar bn bişey sorcaktım siz sektorde içli dışlısınız çok flutterın sektorde yeri nasıl iş bulma konusunda pişmanlık duyulurmu mesela xmarin hic yok denecek kadar ogrense biri pişmanlık duyar gibi  bide bn bide freelance veya startup kendi uygulamamı yapacam  ama alıstırma yapıyorum figma tarzı yerlerden bn tasarımlara uygun api yok cok apiden cekme gibi konuları sonra ogrensem  beck end yada firabase gibi sunucu ogrensem ole tutsam verileri sizce uygun olurmu

**Comment by VB10** [comment]
kanalda fltuter ve backned path vıdeoları var onları izlersen nehi seçeceğini anlayabilirsin.
