### ISSUE TITLE
Static implement için farklı bir bakış açısı

### ISSUE THREAD

**Issue by bolt4dev** [VB10/vboverflow#217]
Hocam merhaba, dartta maalesef static methodları ve constructorları override edemiyoruz. Çok fazla modelimiz olduğu ve hepsinin toJson-fromJson a sahip olduğu bir durumda nasıl bir base class yapılabilir? fromJson'u bir base classdan alıp override etme konusunda pek bir çözüm üretemedim. Sizce nasıl bir yol izlenmeli?

**Comment by VB10** [comment]
@b0ltxyz vexana bakabilirsin misal burada base model yaptik veya benim repolarda base firebase model orneklerimiz var burada tojson from jsonlari ayirip baglayaiblrisin.
