### ISSUE TITLE
Flutter ile Geliştirme Yapmak için Macbook Önerileri

### ISSUE THREAD

**Issue by josephnade** [VB10/vboverflow#218]
İyi çalışmalar. IOS tarafında da geliştirebilmek anlamında macbook ihtiyacım var ve bunun için para biriktiriyorum lakin fiyatlar ortada. Sizce rahatça flutter ile geliştirme yapabileceğim en düşük özellikler ne olmalı? Bununla alakalı bilgilendirebilir misiniz? Şimdiden teşekkürler...

**Comment by vuralkayracetintas** [comment]
Hocam selamlar, 
aslinda herhangi bir m1 - m2 islemcili herhangi MacBook isini gorur gibi üst düzey bir şey olmasina çok fazla gerek yok . giriş seviyesi m1 air is gorur.

**Comment by VB10** [comment]
ben minumun m1 air 8gb da yazani gordum ondan ilk baslagicta cok fazla abartmadan hatta ikinci el almani tavsiye ederim.

ama alabiyorlarsan m1 16 ideal isine yeterli olur ama ilk pc ikinci el tavsiyem
