### ISSUE TITLE
Kendimi geliştirdiğimi ve artık kendime ne katabileceğim hakkında bilgi edinmek istiyorum. 

### ISSUE THREAD

**Issue by MertTheTopDev** [VB10/vboverflow#219]
Github: https://github.com/AzmanMerto
web: https://nomotetes.dev
my project: https://github.com/AzmanMerto/Aiachy-0.09
[Mert Turedu CV.pdf](https://github.com/VB10/vboverflow/files/12654075/Mert.Turedu.CV.pdf)

**Comment by VB10** [comment]
3 ekim yayinda biraz bahsettim eline saglik biraz daha github repolarina dikkat etmen gerekiyor
