### ISSUE TITLE
[flutter] bottomsheet ve klavye kullanımı.

### ISSUE THREAD

**Issue by kucukkaa** [VB10/vboverflow#22]
bir uygulama üzerinde çalışıyorum. bottomsheet üzerinde farklı sayılarda textformfieldlarım  ve diğer listtile elemanları var. bu fieldlara text girmek için tıkladığımda klavye açılırken bottomsheet constructor 'ı  yeniden çalışacak şekilde yenileniyor. ve listtile elemanlarının son stateleri bu sebeple kayboluyor. klavye kapanırken de yeniden sayfa refresh oluyor. araştırma yaptım ama sorunu çözemedim.  

anladığım kadarıyla sorun klavye açılırken sayfanın boyutunun yeniden ayarlanması ile ilgili bir sorun var.
bu sorun  klavye bottom elemanı olduğundan  ve bottomsheetle beraber de kullanılınca hepten ciddi probleme dönüşüyor.

scaffold için resizeToAvoidBottomInset: false değerini set ettim, bir çok yöntem denedim ama sorun çözülmüyor.

**Comment by sametteam06** [comment]
2 gündür ben de aynı sorunla uğraşıyorum. bakmadığım yer kalmadı fakat çözüm bulamadım.

**Comment by demirdev** [comment]
Merhaba @kucukkaa ve @sametteam06 , StatefulBuilder kullanmayı dener misiniz?
Kod paylaşabilirseniz yardımcı olmak isteyen arkadaşlar daha rahat çözebilir.

**Comment by VB10** [comment]
eger bottom sheet yaptıgın sayfayı ayrı bır statefull yaparsan ve oradaki değerli kendi içinde tutarsan 1. olarak bu 
ikinci olarak misal user listesi doldruyorsun savebastın geri açılrıken o save ettiğini veriyorsun.
ek olarak yine controller da dışaradan gelebilir constrctor yeniden değilde build methodu tekrar tetikliyor ondan
