### ISSUE TITLE
Ödeme sistemleri

### ISSUE THREAD

**Issue by a-social** [VB10/vboverflow#221]
Ödeme sistemlerini ogrenmek istiyorum test etmek icin gpay i ogrenmeyi denedim ancak api baglantisi kuramadim detayli bi ogretici yapabilir misiniz gpay haricinde turkiyede yaygin olan paytr var dediler paytr klavuzunu okudum ancak dart ta  nasil kullanabilirim anlayamadim bu ve buna benzer odeme sistemleri var hazirda paketi olmayan bunlari kendimiz nasil kullanir hale getirebiliriz bir yolu var midir hocam

**Comment by VB10** [comment]
burada yapilacak sesy misal gpay test cardlarini kullanmak ama turkiyede yok misal paytr restfull test cadlarini bulup bunlari kendi tarafina baglayacaksin
