### ISSUE TITLE
Json Serializable Ram Üzerindeki Etkisi

### ISSUE THREAD

**Issue by CanGonulacar** [VB10/vboverflow#224]
Json serializable ile oluşturduğumuz modeli inceledim. Örnek.g.dart'a baktığımızda oluşturulan metotlar global metotlar.  Global değişkenler ve metotlar derleme zamanında ram'e girerler ve hafızadan silinmezler. Buradaki fark part, part-of ve private metotlar. Bunun bellek üzerinde bir etkisi var mı? Bu metotlar silinir mi? Eksiğim veya yanlışım varsa uyarın lütfen

**Comment by VB10** [comment]
bu işe yarayabilir.  ve evet ramda tutuluyor globaller bunlar privat eolduğu yada daha çok küçük işler olduğu için çok büyük bir etkisi olmuyor diye biliyorum bende

https://blog.logrocket.com/why-not-use-global-variables-flutter/
