### ISSUE TITLE
Donanımdan Yazılıma Geçiş

### ISSUE THREAD

**Issue by TheeITGuy** [VB10/vboverflow#225]
Merhaba, yayında yazdım ama fark edilmedi sanırım.  3 yıla yakın süredir IT Specialist olarak çalışmaktayım. Artık yazılım dünyasına geçiş yapmak istiyorum.  Back-end kısmına meraklıyım. Mesleği yazılımcı olan arkadaşlarım .Net önerdi. En yaygını bu mu? Yurtdışında ne kadar yaygın? Nereden başlamamalıyım? Bu tarz soru işaretlerim var.  Yardımınızı rica ederim.

**Comment by VB10** [comment]
java çok yaygın aslında trde .net çok var diyeiblirim ama java da aşşağı kalmıyor. açıkcası .net c# öğrenmek çok daha kolay olur genelde toolar vs ile birlikte.

burada ikisinin teknik specleri dışında aslında günün sonunda database cloud vs derken çok ortak noktaları olacaktır öğrenme adına

c# adına borakasmer.com a bakabilirsin onun youtube eğtiimleri de var, java konusunda evren hoca var ona bir danışabilirsin twitterdan vs java commda taner hocada var onlarda yardımcı oluyorlar hep

**Comment by VB10** [comment]
birde buradan tech şirketlerine bakıp ne ne kadar daha iyi anlayabilirsin
https://stackshare.io/companies/uber-technologies

**Comment by MCH10** [comment]
Verdiğin bilgiler için teşekkür ederim. Bir yerden başlamama yardımcı olacak bu bilgiler. En azından kafamda bir zemin oluşturabildim.

**Comment by TheeITGuy** [comment]
Anlattıklarına göre ve attığın linke göre çoğunluk java, js, react, node js kullanıyor. o zaman bana bir yol ayrımı oluştu. Java mı? .net mi? Buna karar vermem lazım. Sonrası gelecektir diye umuyorum.
