### ISSUE TITLE
Notification ile sayfa yönlendirmesi ve ölü token?

### ISSUE THREAD

**Issue by aekaba** [VB10/vboverflow#226]
Order güncellendiğinde firebase ile kullanıcıya bir background bildirimi gidiyor, ve yönlendirmeyi yapıyorum aslında, Benim problemim tokenim çok hızlı ölmek zorunda. Refresh tokenimde aynı durumda olduğu için 2 side öldüğünde refresh edemeyip login sayfasına yönlendiriyorum. Asıl sorunumda burada başlıyor. Kullanıcı login olduktan sonra tekrar o sayfaya yönlendirebilirmiyim ve nasıl yaparım?

**Comment by VB10** [comment]
burada eğer kişi token öldü diyelim shop detay sayfasına gidecek.

401 yedikten sonra bunu interceptor ile anlayıp gitmek istediği route değerini bir in memory cache tutarak bir map içerisinde misal tamamlayıp login oldutkan sonra eğer bir data varsa bu linki tekrar trigger et diyerek yapabiliriz.

yani gelen 401 gelen o notificaton model cache tutulur login olduktan sonra bu gelen model ilgili navigasyon sayfasına verilerek işlem tekrarlanır
