### ISSUE TITLE
Kartal paketi padding 

### ISSUE THREAD

**Issue by vuralkayracetintas** [VB10/vboverflow#227]
![SCR-20231011-ugmc](https://github.com/VB10/vboverflow/assets/73638860/8280bfce-9d63-498a-82cf-c40eb21c9f4c)

![SCR-20231011-ufou](https://github.com/VB10/vboverflow/assets/73638860/5088b685-57a6-4519-b426-f17d40fbfa5f)

kartal paketini kullanarak hem top hemde left olarak nasıl padding kullanabilirim ?

**Comment by VB10** [comment]
context.padding.onlyleft + context.padding.only right, + operotoru edge istets için ovveride edilip yazılmış durumda @vuralkayracetintas

**Comment by vuralkayracetintas** [comment]
Bas tacisin abi tesekuurler :) @VB10
