### ISSUE TITLE
notched shape özelliği başka durumlara nasıl eklenir

### ISSUE THREAD

**Issue by a-social** [VB10/vboverflow#229]
BottomAppBar ve BottomNavigationBar arasında belirli farklar var hatt baya farklılıklar var BottomNavigation bar kullandığım bir uygulamam var içerisinde notch özelliğini kullanarak belirli bir boşluk yaratmak istedim ama tabiki olmadı bottomappbar da direkt olarak geliyor bu özellik kendime özel bi widget yaratmaya çalıştım ama işin içerisinden çıkamadım bir türlü acaba olan bir widgeti başka bir widgeta benzetmek için yapabileceğimiz bir olay var mı yada buna benzer bir paket. tüm hikayemi bottomnavigationbar üzerinde yazdım ancak notch eklemek için bottomappbara çevirmem gerekti bir sürü sıkıntılar oluştu pageviewimi ayarladım dedim tam diğer bu sefer uygulamamı baştan çalıştırınca sorunlar oluştu buna bir çözüm var mıdır saygıdeğer insan:)

**Comment by VB10** [comment]
şimdi bu noktada tabi tam bakmak lazım ama bazen bizim de kullanırken kaldığımız yer oluyor burada önemli olan bazı ui componetnleri var olan misal notch için illaha bottom appbar uymuyorsa kendimiz yazmamız gerektiği. custom draw gibi  yada bu site gibi.

yani her zaman ana component değil bakışa göre ilerleyip olmama durumunda custom gitmek lazım.
https://fluttershapemaker.com/#/
