### ISSUE TITLE
Tavsiye ettiğiniz yabancı Flutter eğitim kanalları nelerdir?

### ISSUE THREAD

**Issue by hasaneke** [VB10/vboverflow#23]
Cevaplar için teşekkürler :)

**Comment by Dzturk** [comment]
[https://www.udemy.com/course/flutter-bootcamp-with-dart/](url), Angela Yu ablamız yabancı kaynaklar arasında en derli toplusu gibi geliyor. 

[https://www.youtube.com/c/FlutterCommunityVideos/videos](url) Flutter Community kanalında aradığınız konu özelinde güzel cevaplar bulabilirsiniz. Arada hap bilgi yayınları ve videoları paylaşılıyor. 

Ben görsel olarak öğrenen biriyim. Bir sorunum varsa bunu makaleler, dokümantasyonlar vs. inceleyerek çözümlemek yerine, izleyerek anlamak daha kalıcı geliyor bana. Bu yüzden ekstrem bir sıkıntım yoksa genellikle sıkıntımı Youtube'a yazarak çok çeşitli videolar izliyorum o sıkıntı ile alakalı. Bu da bazen X'i ararken Y'yi de öğrenmeme faydalı oluyor. A-Z bir kursla başlayım gideyim diyorsanız Veli Hoca ve Angela Yu, kurs olarak fazlasıyla yeterli diye düşünüyorum. Fakat yolda ilerlerken illaki bir şeylerle karşılaşacak ve çözüm üretmek zorunda kalacaksınız bu kursları takip ederken. Size bu işi asıl öğreten zaten o çözüm arayışlarınız olacak. Google büyük nimet, belli bir seviyeye gelene kadar kullanmaktan çok kaçınıyoruz fakat o eşiği aşan insanlar zaten alıp yürüyorlar. Google araştırması bu işlerin %70'i bence. Herkese başarılar dilerim. Saygılar.

**Comment by aea91** [comment]
Veli hocamdan iyi olmasın Rose Coder iyidir.

**Comment by VB10** [comment]
yes bu arkadaşlar çok iyi ben ingilzice konusunda en en çok önerdiğim bu
https://flutter.dev/learn
bride bu pdf öneriririm diğer içerikler içinzaten. githubtaki repoları inceleyip bunları örnek yaparak öğrenmesi en iyisi bu kitabın dart in action da çok güzel
<img width="257" alt="image" src="https://user-images.githubusercontent.com/17102578/174676444-f66a5563-887c-4402-b4ba-90632257304e.png">
