### ISSUE TITLE
İleri Dart Nasıl Öğrenilir? 

### ISSUE THREAD

**Issue by ghost** [VB10/vboverflow#231]
Merhaba hocam Flutter çalışıyorum ve widgetlarla bir sayfa çizme konusunda çok sorun yaşamıyorum. Ama en büyük sorunum sizin gerçek hayat case'leri videolarınızdaki yazdığınız kodları yazmakta. Kendimi bu konuda çok eksik hissediyorum ve nasıl geliştireceğimi bilemiyorum. Bir videoya ya da dökümana tamamen bağlı olmadan kod yazabilecek duruma gelmek istiyorum. Sizce bu eksiklerimi nasıl çözmeliyim? Farklı diller çalışarak bu eksikliğimi Dart diline uyarlayabilir miyim?
Bu konuda her şeyi yapmaya hazırım hocam, tavsiyeleriniz neler olur? Şimdiden teşekkürler hocam.

**Comment by ghost** [comment]
Eğer soru çok açık değilse örnek vererek açıklamak istiyorum. Bir müşteri bana gelip herhangi bir istekte bulunduğunda bu isteğini nasıl yapıcam, bu çok zor, bunu yapamam değil de bunu böyle yapabilirim düşüncesine sahip olmak istiyorum. Eksiğimin ne olduğunu anlayamadım, OOP eksiğim mi var yoksa sorun nedir bilmiyorum. Yardımlarını beklerim. Bu konu üzerine çalışıp kendimi geliştirmeye hazırım.

**Comment by VB10** [comment]
@HikmetMelik şimdi bu konu yani teknik olarak ileri yada bir soruna teknik gelişmiş cevap vermek ne kadar öğrenirsen öğren bir kerede olacak bir iş olmuyor burada önemli olan şey teknik kalıplara ezber yaparak değil misal abstractioan car bmw değil poly gibi kavramları daha realite nasıl olurdu diye düşüneceksin.


gidip design patternleri daha java c# gibi dillerde araştırıp yani yıllardır olup binlerce çözüm üretilmiş yerlerde bulup bu örnekleri misal darta uygulamaan gerekir. 
https://www.statuscake.com/blog/useful-design-patterns/

işin özü bu teknik gelişim diğer dillerle birleştirerek sonuca varmak ve misal diyelim müşteri senden bana A firması için %10luk isconta koyarak bir kod yazar mısın dedi diyelim

bunu doğrudan bir yaklaşım yapmak yerine önce en kolay en akla gelenle gidip üstüne kendin boşta kaldıkca nasıl yapardım derisn misal:

1- if company ==a  result = result - 20 gibi

ama desen ki abi yarın da B gelecek elbet ve oranda değişecek bir çok pattern buna uyabilir adapter kullanırsın misal yada benzeri dersin ki ben bir Company interface yaparım içinde discount oranın girer make methoduyla hesapla derim bundan türemesini isterim

o zaman çözüm hem daha kontrollü hem test edileblir hemde temiz hale gelirdi
1- result = company.make()
