### ISSUE TITLE
yazılıma başlarken hangisini öğrenmek iyi olur

### ISSUE THREAD

**Issue by vuralyazilimm** [VB10/vboverflow#232]
Selamun aleyküm.Ben yazılımı hem sevdiğimden hem de kafamdaki fikirleri gerçekleştirmek açısından öğreniyorum.
Yani,PARA İÇİN .Lakin sadece para değil.Seviyorumda.Kafa yormak aşırı hoşuma gidiyor.
Yazılım alanındaki hedefim MAAŞ değil.Ben tamamen kendim için öğreniyorum.Yani
İşin GİRİŞİMCİLİK tarafındayım.

veli abinin dart eğitiminle ilerlerken Şunu düşündüm:
Duolingo gibi uygulamaların hepsinin WEBSİTESİ var.Madem uygulamada yapılanlar
WEB sitede de yapılabiliniyor,O halde website programla öğrenmem,uygulama öğrenmeye
Nazaran daha MANTIKLI OLMAZ MI?

Basit e ticaret web siteleri değilde gerçekten sağlam siteler geliştirmek benim amacım.

Bu açıdan,UYGULAMA YAZILIMI MI YOKSA WEB SİTE YAZILIMI ÖĞRENMEK Mİ daha mantıklı?

**Comment by aekaba** [comment]
Yani ben kendim olarak mobil uygulamaları kullanmak istiyorum. Dualingonun web sitesinin olduğunu bile yeni duydum çünkü uygulama daha kullanışlı. Seninde kullanıcıların neyi tercih ediyorsa ona geliştirme yapman daha doğru olur. Mobile çıkan bir uygulama için yinede bir backend e ihtiyacın olacaktır. bunu yaparkende bir front da koyarsın ortaya. Bunların hepsini flutter ile tek bir kodla yapabilirsin birde bu yönü var tabi. Ama konuya uygulama yazılımı mı web site yazılımı mı öğrenmek dersen bunlar yazılımcının az da olsa bilmesi gerektiği konular.

**Comment by VB10** [comment]
@vuralyazilimm şimdi burada web yazılım mobil yazılım aslında yok. burada önemli olan yazılım var. ve yazılımın da backend, front end ve system olarak üç alan var en temelde. 

dualingo websitesi yazılımını öğrenmek değil aslında burada dualingo da diyelim bir butona bastın sana soru çıktı bu bir backend kararıdır ve bu aslında ne web ne mobil işi onlar sadece gösteriri. birini seçmek web mobil diye değil aslında backend ve front end olarak ilerleme iyidir.

şu soruyu sorarsan kendine yön bulabilirsin
1- dualingo sisteminin iş kararlarını yöneten arka taraf mı olmak isterim yani backend
2- dualingo sisteminin ön tarafı müşterinin kullandığı ekranları yazıp son kullancıya erişmek mi isterim yani front end

en temel en basitçe bunlar diyeiblirim. @vuralyazilimm
