### ISSUE TITLE
ChatGPT API & Flutter

### ISSUE THREAD

**Issue by aio001** [VB10/vboverflow#233]
Merhabalar. Flutter ve ChatGPT kullanarak bir app yazıyorum. Sıra API bağlamaya geldiğinde araştırma yaparken fark ettim ki bir kısım [chat_gpt_sdk](https://pub.dev/packages/chat_gpt_sdk) kullanırken bir kısım ise http ile istek atmış. Aradaki fark ne? Hangisini tercih etmek mantıklı?

**Comment by MuhammedKpln** [comment]
Fark yok, sdk ile zaten başkası tarafından yazılmış http isteklerini kullanıyorsun sadece.

**Comment by VB10** [comment]
@MuhammedKpln katılıyorum sdk integrasyonlu bir paket olmuyor genelde arka tarafta restfull istekler gidiyor sdk eğer telefondan beslenirse misal ml gibi daha platform spesifc oluyor @kagangullu
