### ISSUE TITLE
Firebase Crash

### ISSUE THREAD

**Issue by aekaba** [VB10/vboverflow#234]
Yaptığım uygulamada Firebase Analytics, FCM, Crashlytics eklentilerini kullanıyordum. Uygulama açılırken, daha kendi splash ekranıma gelmeden yani native splash ekranında uygulama crash veriyor ve native splash ekranı kalıyor, uygulama benim yaptığım splash ekranına geçmiyo başka bir tabirlede donuyor. Uygulamamın V1 kısmı için firebase i kaldırdım, Ama notif ve hataları ayıklamak için firebase i tekrar kullanmak istiyorum çünkü işimi kolaylaştırıyor. Ama bu hatayı tekrar alırım diye başka eklentilere bakıcam galiba(one signal, Sentry) gibi. Firebase i kaldırdığım için elimde örnek kod yok ama umarım yazılarımdan hatayı anlayabilmişsinizdir. Sizce bu hatayı neden alıyorum? Eklenti kurulumumdamı hata vardı? Eğer bunlara bir çözüm bulamazsam bunlar yerine kullanabileceğim eklenti önerileriniz varmıdır acaba?
Şimdiden Teşekkür ederim.

**Comment by gundogduali** [comment]
Eğer native splash üzerinde hata alıyorsan runApp methodundan önce çağırdığın kodlarda exception atıyordur. Bir çok sebebi olabilir. Firebase methodlarını çağırmadan önce initialize etmemiş olabilirsin. runApp den önce çağırdığın kodları debuglayarak hatayı bulmak daha kolay olur.

**Comment by aekaba** [comment]
Teşekkürler.
