### ISSUE TITLE
Prod ve test için ayrı uygulamalar yapmamak?

### ISSUE THREAD

**Issue by aekaba** [VB10/vboverflow#235]
Uygulamam testen stora geçme aşamasında, İlerde geliştirmelerde kullanacağım test uygulaması ile çalışan gerçek uygulamayı ayırmadan nasıl geliştirme yapabilirim? test api farklı bunu flutter debug mod yada release ise ayırmayı düşündüm eğer debug mode ise test url i gelir release ise gerçek api. Uygulamayıda release branchi ile ayırıp maindede normal geliştirmeyi devam ettirsem acaba nasıl olur? Bana şuan 00:00 da 4 saatlik kodlama ardından biraz mantıklı geldi ama veli hocamada bir danışayım dedim. Diğer arkadaşlarda canlar saolsunlar stackoverflowdan önce buraya geliyoruz artık. Dertleşme noktası gibi.
Neyse konudan çok saptım kusura bakmayın.
iyi akşamlar.

**Comment by bafranokta** [comment]
Bu foto yeterli mi, servise göndersek değişimini siz yapsanız maliyet nedir?

Ata Emir Kaba ***@***.***>, 18 Ara 2023 Pzt, 00:08 tarihinde
şunu yazdı:

**Comment by VB10** [comment]
bu noktada  kesinlikle flavor kullanarak appleri ayırmak gerekir yani 
test-app
ve app olarak iki ayrı app en doğru yol. yarın bir firebase push denemek istediğinde misal iki aynı bracnhi veya sadece app url değişerek bunu yönetemezsin. en kafa rahat yolu iki ayrı app işin özü diyebilirim.

eline sağlık şimdiden teşekkür ederim burası en güzel yerimiz :)
