### ISSUE TITLE
Firebase ve SQL Veritabanı Seçimi Hakkında İkilem

### ISSUE THREAD

**Issue by Bircansezgin** [VB10/vboverflow#236]
Adım Bircan,  9 Ay gibi bir süredir iOS native uygulamalar geliştiriyorum.  Firebase üzerinde çalışırken bazı teknik konularla karşılaştım ve bu konularda sizin görüş ve önerilerinizi almak istiyorum.

İlk olarak, Firebase Firestore kullanarak kullanıcı verilerini(TC gibi özel bilgileri, Kart Bilgileri) bulutta saklayamayacağımı fark ettim. yani öyle okudum. Bu durumda, bu verileri nereye saklamalıyım? MongoDB - Realm mı yoksa sanal sunucu kiralayıp PHP/MySQL gibi yerel veritabanlarını mı tercih etmeliyim? (restful api) Bu konuda net bir yönlendirme almak benim için önemli.

İkinci olarak, Firebase'i zaten öneriliyor biliyorum. Firebase'in yanına, SQL tabanlı veritabanları konusunda hangi önerilere sahipsiniz ya da önermezsiniz? Bu konuda deneyimlerinizi paylaşabilirseniz çok memnun olurum.

(restful api) HTTP istekleri IOS üzerinden bir kaynak gerçekten çok işime yarayabiliri.

Sorularıma ayırdığınız zaman ve değerli görüşleriniz için şimdiden teşekkür ederim. Umarım en kısa sürede yanıtıları alabilirim.

Saygılarımla

**Comment by VB10** [comment]
1- kritik bilgileri kendi sunucunda şifreli tutup bunları uyg kapsamında devlete veya kanallara vermen gerektiği için firebase den ziyade herhangi bir database çözümü ile kendi localinde saklyabilirsin.
2- burada çözüm isterin en olduğuyla ortantılıdır aslında misal firebase önerme diye bir şey yok. diyelim ki senin çok ilişikili yani yönetici çalışan bunun roller ivs var bu durumda llişikisel veri tabanları çözümüne gidilir. daha anlık data yazma okuma hızlıca o dataya erişip işlem yapma olduğunda document db gibi no sql çözümler seçilir.

kaynak konusunda özel bir seçim yok hepsi aynı firebase rest deneyebilirsin misal paket kullanmadanda yöntemi benim mediumda var. ios özelinde kanalda yine benim anlattığım network katmanı örneği de mevcut.

database konuları çok kolay veya öneri üzerine verilebilecek bir karar değil. proje ister ne yapmak istediğin ve bu kapsamda elinde gücünle doğru orantılı diyeiblirim. bazı kocaman projeyi tek db giden de olabilir kimisi 5 farklı graph document sql gibi üçünü aynı anda yönetende görülür. daha iyisini seçmek proje ile çok doğru orantılı. 

genelde tek db gider bu arada ileride onlar çoğalır. senin case de db firebase kullanaman yasal yükümlükler gereği tc tutulamaz. kendi localinde bile tutsan onu şifreleme vs vs gerekecek işin özü
