### ISSUE TITLE
Flutterda Modüler Yapı Kullanımı

### ISSUE THREAD

**Issue by dilberates** [VB10/vboverflow#237]
Merhaba Hocam ben Dilber. Sadece Flutterda kafam bir konuda çok karıştı. Modüler bir dosya yapısı kullanıyorum projemde ama geçenlerde klasör sayımın fazla olduğu söylenildi. Ben ise modüler düzenli bir yapı kurduğumu düşünüyordum. Sizce karmaşık bir yapı mı kurmuşum. Büyük olacak bir projede kullanılıyor. Ekteki resim gibi genelde. Lütfen bu konu hakkındaki düşünceleriniz nedir  çok değerli benim için.

Şimdiden Teşekkürler. 

![Screenshot 2024-01-09 at 17 19 47](https://github.com/VB10/vboverflow/assets/48033000/5c604f9e-3210-426f-96ad-b40b9a848900)

**Comment by VB10** [comment]
şuanki görünen yapı sorun göstermiyor açıkcası bu tarz kararlar ekiple verilir ve ekip neyi uygun görürse öyle ilerler. en fazla modeller veya reposityory katmanları tek bir folder altında toplanabilir buda yine ekip kararı
