### ISSUE TITLE
Bluetooth classic scan Ios

### ISSUE THREAD

**Issue by haznigulec** [VB10/vboverflow#24]
Merhabalar,
Uygulamamda bluetooth ile tarama yapıp bir cihaza bağlanmak istiyorum. Bluetooth LE ile android ve iosta rahatlıkla yaptım bunu ama şuan bluetooth classic ile iosta scan edip bağlanabileceğim yol bulamadım ve birkaç yerde ios un buna izin vermediğini okudum. Bi yolu yok mudur bunun acaba?

**Comment by VB10** [comment]
bu konuda bir bilgim yok ne yazıkki burada bilgili bir arkadaş varsa yorum atacaktır ama tavsiye mşu native bir appte deneyip eğer yapabilirseniz bunu fluttere bridge etmeniz koaly gelsin
