### ISSUE TITLE
Yazılım ve Mobil Uygulama İçin Bilgisayar Seçimi

### ISSUE THREAD

**Issue by edslan** [VB10/vboverflow#240]
Merhabalar;

Flutter dilinde kod yazıp mobil cihaz üzerinde rahatça simule edebileceğim bir apple bilgisayar arayışı içresindeyim. Beni şuanda ve uzun süreçte bir sorun çıkartmayacak derleme yaptığımda takılma yada sorun çıkarmaması benim için önemli. Konu ile ilgili yardımcı olur musunuz? Aklımda mac mini m2 ve macbook air var.

**Comment by VB10** [comment]
flutter özelinde bir bilgisayar aramaya gerek yok önemli olan apple olması ios için ve ram. bun oktada m1 air başlangıç için oldukça yeterli. yine diğer bu modeller uygun olur 16 ram olursa daha iş görür
