### ISSUE TITLE
Custom Widget oluşturma konusunda

### ISSUE THREAD

**Issue by CanGonulacar** [VB10/vboverflow#241]
![SRLQl](https://github.com/VB10/vboverflow/assets/89852107/336fff3e-59a4-4f49-b79c-983b650c99a3)

Merhabalar, Fotoğraftaki 2 tarz arasındaki farkları öğrenmek istiyorum(ram,okunabilirlik,temiz kod vs). Acaba ilk sınıfta fonksiyon gibi parametre olarak 2 tane veri alıyoruz ama 2. sınıfta verileri oluşturmuş olup belleğe 2 tane daha veri oluşturmuş mu oluyoruz?
Stateless widget oluşturduğumuzda yeni bir context bağlamış oluyoruz. context e ihtiyacımız yoksa eğer ilk kodlamayı mı kullanmalıyız? gibi sorular geliyor aklıma. Teşekkürler şimdiden

**Comment by VB10** [comment]
@CanGonulacar merhaba burada bir çok tavır var aslında ma ben kendim eğer bir sınıfın alt sınıfı olarak eleman yapacaksam senin örneğin ikincisi gibi onu seçiyorum.

yani ondan türeyen başka elemanlar yapıyorum ki bu benim onay verdiğim bir şey veya kodsal olarak diyelim ki bu olmasın istennseydi classı nbasına final atınır ve kaılıtım engelennirdi.

Elbette statless yeni context yeni bir iş yükü doğurur tabi ne boyuttu handle edilir ama ben daima ikinci taraftayım. bazı yerlede bunu yanllış olarak konusanlarda gördüm ama benim bakışıma göre mantıklı ve performanslı yöntem
