### ISSUE TITLE
aslında garip bir soru open cv  ile uğraşmak mı tflite (tensorflow ile uğraşmak mı) ?

### ISSUE THREAD

**Issue by a-social** [VB10/vboverflow#242]
bir proje var elimde ancak kafam karışık open cv bilgim var biraz ve python üzerinden güzel bir servis hazırladım flask kullanarak. uygulamam serverim ile iletişim kuruyor ve işlenecek görüntü firebase e ulaştırıyor güncellenmiş cevap olarak gönderiliyor ANCAK bugün tensor flow diye bir şey gördüm ve merak ettim aşağı yukarı benim yaptığım işlerin aynısını yapıyor yine de kullanmak istediklerim eksik ama bir nebze de olsa karşılıyor sorum ise şu.

uygulamam servis kullandığı için sadece fotoğraflar gönderildiği zaman o cevap ekranından çıkabiliyor ve diğer işlemlerine devam edebiliyor işlemler bitttiğinde cevabım otomatik olarak gidiyor ben bu işi localde yaparsam eğer ki görüntü işleme olayını lifecycle olayını da doğru kullanabilirsem eğer ki vakit kaybıma değer mi bununla uğraşmam bu servide 1 ayımı verdim ve güzel bir şekilde oluşturdum 1 hafta sonra bakıma girecek eğer ki tflite kullanan varsa beni aydınlatabilir mi zaman olarak kısa mı sürer uzun mu sürer.
(fotoğrafa göre değişebilir evet ancak gönderilen fotoğrafım 10 adet geri dönen cevap ise chat gpt api si ile bir cevap bu sebeple servisimin dönüşü ortalama 2 dk falan sürüyor)

KISACA
tensorflow kullanılır mı ? :)

**Comment by VB10** [comment]
dogrudan ılgılı oldugum bır konu değil ondan bir yorum yapıp yanlış yönlendirmek istemem ama illaki paketler kendine göre avantajlar sağlar.

birinci yol open cv sana bir fikir öğretir bunu başka yerlere yontarsın ama ikinci yol müşteri ister ve ona göre efor vermek istemeden güvenilir tet yollu bir tercih yapmak istersen seçmek gerekreiblir
