### ISSUE TITLE
uygulamada ödeme kısımlarını oluşturmak için hangisi daha mantıklı ?

### ISSUE THREAD

**Issue by a-social** [VB10/vboverflow#243]
in app purchase veya pay paketini mi kullanmak daha mantıklı önceden pay paketi için araştırma yapmıştım test ederken veya diğer durumlarda çok sıkıntı yaşadım ve başkasına yaptırdım ödeme kısmını şuan için öğrendim ancak hala zor geliyor bana şimdi ise in app purchase diye bir paket gördüm bu paket hakkında bir fikriniz var mı ? bizi aydınlatabilir misiniz hocam :)

**Comment by VB10** [comment]
bır paketı yıne kullanmadan once pkaetin issue kısmına bakıp sorunlara bakıp ilerlemek lazım. daha mantıklı yok herkes en iyisini ister ama her paketin kendine göre avatnajı olabilir kendi scope bakmak laızm
