### ISSUE TITLE
Bloc ile global veri paylaşımı

### ISSUE THREAD

**Issue by muratolcal** [VB10/vboverflow#244]
Merhabalar,
Bloc ile yazmaya çalıştığım bir sistemde kullanıcı login olduğunda dönen bir responsem var. Bu response içerisinde diğer sayfalarda da çekeceğim veriler için gereken bilgiler bulunuyor. Denediğim yöntemlerde sadece kendi sayfası içerisinde ki cubit ve stateler ile işlem yapabiliyorum ancak diğer sayfalarda sadece null dönüyor. Provider kullanan bir çok arkadaş gördüm ancak bunu bloc cubit ile halletmek daha doğru olacağını düşündüm. Ayrıca SharedPrefences kullanan da bir çok arkadaş gördüm. Sizce bu konuda nasıl bir yol izlemeliyim. Şimdiden cevaplarınız için teşekkür ederim.

Kodlar için Github repom: [](https://github.com/muratolcal/PDKS)

**Comment by muratolcal** [comment]
https://github.com/muratolcal/PDKS

**Comment by CHEETLOCK** [comment]
dostum üstün körü baktım. data is ...... yapıyorsun fakat data değişkenine null olabilir diyorsun. Gönderirken null gönderiyor olabilirsin. Detaylı bakamadım ama bir kontrol et null yaptığın değişkenleri istersen

**Comment by VB10** [comment]
@muratolcal burada ciddi bir kaç sıkıntı var yapılar kurulurken dikkat etmek gerekirken en üstte login bloc adı altında yapının tüm proje katmanın erişilir olduğu gözüküyor ama içeride bakmak lazım tek tek. 
@muratolcal  https://www.youtube.com/watch?v=tj5-EBrczxk&t=47s

bu vıdeo ızleyıp tekrar yapına bakabilirsin yine kanalda benzeri içeriklerle global man. vs yapılar kurulabilir
