### ISSUE TITLE
windows kullanarak swift geliştirme

### ISSUE THREAD

**Issue by Mustafkgl** [VB10/vboverflow#245]
Merhabalar,

Öncelikle sağlıklı günler diliyorum. Windows kullanarak (ya da apple cihaz sahibi olmadan) swift geliştirmek istiyorum. Çevresel bir araştırma yaptığımda her kafadan ayrı bir sesin çıktığını gördüm. Çok fikir ayrılığı var bu konu ile alakalı. Nasıl yapalım abim, ne diyorsun bu işe. Şimdiden teşekkür ederim.

**Comment by VB10** [comment]
@Mustafkgl burada önemle olan dili öğrenmek ise evet yapılabilir linux kurabilir veya https://swiftfiddle.com/ buradan dilin kalıplarını run ede ede öğrenebilirsin.

framework için macos ihtiyacı yada linux üzerinden bir kurulum lazım

**Comment by Mustafkgl** [comment]
@VB10 Direkt uygulama yapmak istiyorum. Ayni zamanda da dersim icin gerekli. Cevap icin cok tesekkur ederim ayrica arastiracagim.
