### ISSUE TITLE
iOS Push Notification Data

### ISSUE THREAD

**Issue by SercanParsanoglu** [VB10/vboverflow#246]
Merhabalar Flutter ile bir uygulamanın notification tarafını geliştirmekteyim. Android tarafında aldığım data mesajı sorunsuz bir şekilde local notification ile işleyip kullanıcıya bildirim olarak gösterebiliyorum. Fakat anladığım kadarıyla   iOS tarafında data mesajlar, uygulama kapatılmaya zorlanmış ise uygulamayı tetikleyemiyor bundan dolayı data mesajı işleyip kullanıcıya notification olarak gösteremiyorum. iOS tarafında sadece data mesaj ile kullanıcıya notification gösterebilmemin bir yolu var mıdır acaba? Şimdiden teşekkür ederim.

**Comment by VB10** [comment]
bunu bir fcm tarzı servis ile çözmenin dışında bir fikir gelmedi aklıma açıkcası local notification konusunda haklısın yetersiz oluyor bu konuda. kendi özel push servisi yazmakta maaliyetli olacaktır.
