### ISSUE TITLE
Arka planda çalışan uygulama açıldığında siyah ekran alma

### ISSUE THREAD

**Issue by muhammetsalci** [VB10/vboverflow#248]
Merhabalar Flutter ile bir uygulama geliştirmekteyim. Uygulamam arka plandayken açınca bazen siyah ekranda kalıyor.
Bunun sebebi ne olabilir?
Çözümü ne olabilir?

(tam olarak neyden kaynaklı olduğunu anlayamadığım için kendim ekran kaydı alamadım ama aşağıda paylaştığım video benim yaşadığım sorunun bire bir aynısı)

https://github.com/VB10/vboverflow/assets/102540491/184a087e-5154-420b-97ca-27fe49dfcaf6

**Comment by VB10** [comment]
@muhammetsalci bun github flutter reposuna acarsan daha iyi olur
