### ISSUE TITLE
Flutter: Quality Loss In The Background Image

### ISSUE THREAD

**Issue by kheif** [VB10/vboverflow#249]
Flutter'da Scaffold'un `extendBodyBehindAppBar` özelliğini açıyorum ve body'e Expand içinde bir Image widget'ı koyuyorum. Daha sonra da AppBar'ın rengini `Colors.black.withOpcaity(0.7)` yapıyorum fakat arkadaki resimin AppBar'ın altında kalan kısımlarında bozulmalar meydana geliyor. Bana verilen dizayndaki ile hiç bir şekilde aynı gözükmüyor. Bu kaybın nasıl önüne geçebilirim? Yardımcı olabilen olursa çok sevinirm.

[Sorunun fotoğrafları ve kodları ve daha detaylı hali Stackoverflow'da](https://stackoverflow.com/questions/78207848/flutter-quality-loss-in-the-background-image)

**Comment by VB10** [comment]
@devEge kodunda build methodu icinde olan system kodunu tavsiye ederim oncelikle onu kaldirman gerekir. genelde bunlar elevetiondan kaynaklaniyor oraya bakabilrsin
