### ISSUE TITLE
constant değerlerin ortaklaştırılması

### ISSUE THREAD

**Issue by skyturkish** [VB10/vboverflow#25]
![image](https://user-images.githubusercontent.com/73424678/174449013-6977046c-f6fd-48dc-9b90-a1806d427827.png)

![image](https://user-images.githubusercontent.com/73424678/174449036-fff082d7-a724-4490-aff3-6511462bcc7e.png)

![image](https://user-images.githubusercontent.com/73424678/174449243-50fe8fc4-86d3-48ac-88a0-d3c4a596e765.png)

Flutterda proje geliştirirken constant değerleri, mesela View için kullandığımız bir Paddinglerin hepsini tek dosyada mı tutmamız lazım yoksa yerine göre bazı constant değerler aynı file'ın içinde durabilir mi. Mesela  "static const EdgeInsets horizontalMedium = EdgeInsets.symmetric(horizontal: 10);"  gibi bir padding değerini ortak bir yerden 7 farklı yerde kullandık, ama projenin ilerisinde bir yerin paddingi beğenmedik, orayı güncellemek demek diğer yerleri de güncellemek demek olacaktır. bu da istemediğimiz bir şey ya da bu sonradan değiştirme durumunun asla yaşanmaması mı gerekiyor, tam pixel perfect olmadan variable'ların ortak olarak toplanmaması lazım gibi bir şey. çok önemli gibi durmuyor ama bazen yazarken bazen bırakıyorum tek dosyada bazen bırakmıyorum, ortak topluyorum. bunun Best practice olayı yok mu yoksa, projeden projeye değişkenlik gösteriyor mu ?

**Comment by Dzturk** [comment]
Ben genellikle projeye has olan, sizin de yukarıda yazmış olduğunuz Primary - Secondary - Selected Nav Bar gibi color, padding vs. ayarlarını kodlarının yazıldığı yerde tutuyorum. Atıyorum Nav Bar ile alakalı constantlar Nav Bar'ın kodunun yazıldığı yerde ve orayla ilgili bir değişiklik yapılması gerektiğinde direkt o dosyadan hem fonksiyonal değişiklik hem görsel değişiklik yapma imkanı veriyor tek yerde. Diğer yandan sürekli değişikliğe uğraması muhtemel şeyleri de ayrı bir yerde ama direkt nokta atışı şekilde tutuyorum. horizontal10Px, topOnly20Px, all40Px gibi. Benimki biraz hastalık bu şekilde yapan başka var mı bilmiyorum ama projenin her alanında genellikle her case için bir padding değerim hazır oluyor constant dosyamda :) Bu konuyla ilgili de bir best practise olacağını sanmıyorum. Bana daha çok yazanın tercihi gibi geliyor ama farklı kullanım senaryolarını görmek mutlu eder beni :) Başarılar dilerim.

**Comment by VB10** [comment]
selamlar buradakı ana nokta projede paddinglerin tüm sayfalrada aynı olması noktası yani x sayfasındada y sayfasıdnada topbottom paddıngler hepsabit olmalı aslında Bu sebebeple bir çok yönetem yapaılabilir
misal ben

`
  const PagePadding.horizontalNormalSymmetric() : super.symmetric(horizontal: 14);
  const PagePadding.horizontalHighSymmetric() : super.symmetric(horizontal: 18);
`

yapıp bunuda Padding propetysine atıyorum buradaki en önemli nokta projede yazakrenm müşteri dahi olsa bir sabit matmeatikle gitmek.Her projeninb ir standartı vardır aslında ama bunu tasarıcmı arkadaşlar kacıraibliyor misal 15 veriyor senin onları 16 ile göstermende sorun yok.

Yani günün sonunda best practices ana sayfaların apddignlerinin aynı olması ek sayfalarıda özel eklemeler yapılmalı bir yerdens onra x sayfasında acaba kac vermiş diye değil zaten projenin hatları belirli olmuş olacak

kolay gelsin
