### ISSUE TITLE
Büyük Uygulamalar için kulllanılabilecek hızlı ve güvenli db'ler önerir misin?

### ISSUE THREAD

**Issue by a-social** [VB10/vboverflow#253]
Büyük projeler için hangi db yi kullanmak daha mantıklı olur evet bir cevabı yok ancak genel anlamda video ve fotoğraf tutulacak bir db ayarlayacağız bu sebeple firebaseden kaçınmaya çalışıyoruz daha uygun sistemler olabilir diye düşünüyoruz senin de bir fikrini almak istedim mesela Hatay'ı yaşat uygulaması için hangi db kullanıldı neden kullanıldı. 
zaman ayırıp okuduğun için teşekkür edeirm iyi çalışmalar abim :)

**Comment by VB10** [comment]
@a-social burada biz firebase kullandik database olarak fire store storage olarak yine firestore kullanildil. Sebeplerimiz:
- guvenlik: security rullar ile guvenlik altina alabilme
- hiz ve esneklik: cok hizli okumay yazm yaapabiliyoruz

simdi biz bu projede ozellikle takim ve kurgu gerigi bunu sectik burada senin yapman gereken takim kurgusu misal database enginer varsa ona gore bir yapi kurulup cdn yapilabilir. yine duruma gore document db database icin secilebilir veya birden fazla db kurgusu olabilir. tek bir cozum yok aslinda her zaman icin en iyis bu demek icin
