### ISSUE TITLE
Bottom barda iki ayrı state güncelleme.

### ISSUE THREAD

**Issue by emrearik** [VB10/vboverflow#26]
Merhabalar.

Bottom navigation barımda Kategoriler ve kelimeler olmak üzere iki adet sayfam var. Kategoriler sayfasında kategoriyi bloc ile güncellediğimde kelimeler sayfasında kategorinin eski hali duruyor. Kategori güncelleme sayfasında kelime blocunu tetiklemeye çalıştım. çalışıyor gözüküyor ama hala kelimeler güncellenmiyor.

![Kategoriler sayfası](https://i.ibb.co/FJ1kQRn/1.png)
![Kelimeler sayfası](https://i.ibb.co/ZcFLCnS/2.png)

Firestoreden direkt stream olarak çekmeden yapmaya çalışıyorum.

Yardımcı olursanız çok sevinirim teşekkürler.

**Comment by yakupemeksiz** [comment]
Aynı bloc üzerinden çalıştığından emin olmanı tavsiye ederim. Farklı instances üzerinde çalışıyor olabilirsin. Kontrol etmek için hashCode larına bakabilirsin. Faklılarsa eğer singleton yapıp demeni öneririm.

**Comment by VB10** [comment]
buradaki sorun şuradan geliyor anladığım şimdi ik ayrı blocun var bunları yöneten bir ana tabda bloc yapabilirsin ve bu sayede bunlara haber verebilirisn. Yani 
TabbarBloc gibi bir yapı kurup burdan ikinci tabdaki değişiklşille birinci tabı udpate edebilirisn veya bir provider ilede yapbilrisin.

Diğer nokta eğer bir listenin güncllenmesi isityorsan bloc t arafında equalty ile sarmalayıp propertylerini vermeye unutma bloc orneklerine benim repolarada bkarsan göreceksinidr
