### ISSUE TITLE
Yazılıma yeni başlayacak kişilere öneriler. 

### ISSUE THREAD

**Issue by MehmetErenButun** [VB10/vboverflow#27]
Özellikle üniversitede farklı bir bölümden mezun olmuş veya okuyan ve yazılım ile ilgilenen kişilere neler önerirsiniz. Kendilerine nasıl bir yol haritası çizmeliler ?

**Comment by VB10** [comment]
selamlar özellikle bu konuda bir kaç iisseu daha kapatmıştk ona bakabilriisn ama genel olarak temel bır mantık onemlı
üretim de olmak yani backend vs biraz yoraiblir ve iş bulmak zor olabilir bence b uradkai en iyi yol fornt end işleri

bu. konuda fltuter react gibi teknolojileri seçip en yakın olanla başlayaiblirisn
burada onemlı olan hızlıca algoıtmayı cozup urun uretmek devam etmek lazım upworks tarzı sitelerden ucuza işleri alıp oradan devam edileiblir

**Comment by MehmetErenButun** [comment]
Cevabınız için teşekkür ederim.
