### ISSUE TITLE
Flutter StreamSubscription

### ISSUE THREAD

**Issue by oguzcc** [VB10/vboverflow#28]
Merhaba. Harici bir uygulamadan paylaşılan linki stream ile tüm sayfalar üzerinden dinlemem gerekiyor. Ana sayfaya bu dinlemeyi ekliyorum fakat başka bir sayfaya geçtiğimde dinleme iptal oluyor. Projedeki tüm sayfalarda bu dinlemeyi eklemem gerekiyor. Bu da çok fazla kod tekrarı. Bunu nasıl çözerim. Tek bir yerden dinleme yapsam ama tüm sayfalar tarafından veri dinlenebilse.
Kullanmaya çalıştığım paket https://pub.dev/packages/receive_sharing_intent

**Comment by aea91** [comment]
BaseView de yapabilirsiniz. Videolarda var. Ben baseview e internet kontrol ekledim tüm sayfalarda dinleyebiliyorum.
