### ISSUE TITLE
BaseView onDispose methodu

### ISSUE THREAD

**Issue by aea91** [VB10/vboverflow#29]
Merhaba,

  return BaseView(
        onDispose: () {
          Logger().i("view disposed");
        },

BaseView den türetilmiş stateless widgetlarda onDispose methodu sayfalar arası geçişlerde çalışmıyor.
Not: Tüm sayfalar baseview den türetildi.

**Comment by VB10** [comment]
burada arkadan öne gelirken methodun evet tetiklenmesi lazım widget öldüğünden nerede sorun tam oluyor kaçırdım ama bu muhmtelen bizim arichtevcture deki bir sorun yeni versiyon gelecek orad abilrikte bakarız

**Comment by aea91** [comment]
Veli hocam acaba tüm viewler baseview den türetildiği için ve aslında birinden diğerine geçerken yine baseview çatısı altında olduğu için mi dispose olmuyor?

BaseView aşağıdaki gibi 

class BaseView<T> extends StatefulWidget {
  final VoidCallback onDispose;
  final VoidCallback initState;
  final Widget Function(BuildContext context) onPageBuilder;

  const BaseView({
    Key? key,
    required this.onDispose,
    required this.initState,
    required this.onPageBuilder,
  }) : super(key: key);

  @override
  _BaseViewState createState() => _BaseViewState();
}

class _BaseViewState extends State<BaseView> {

  @override
  void initState() {
    super.initState();
       widget.initState();
  }

  @override
  void dispose() {
    super.dispose();
    widget.onDispose;
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: widget.onPageBuilder(context),
    );
  }
