### ISSUE TITLE
(Swift) CoreData'da generic + Multithreaded işlemler

### ISSUE THREAD

**Issue by MehmetKaranlik** [VB10/vboverflow#3]
Hocam Swift'te CoreData için generic bir manager yapısı kurdum işte singleFetch & multipleFetch vs gibi featureları bulunduran

[Manager linki](https://github.com/MehmetKaranlik/CoreDataManager/blob/main/CoreDataManager/CoreDataManager/Manager/CoreDataManager.swift)

Burada ki fonksiyonları daha performant hale getirmek için multi-thread kullanmak istiyorum var mı tavsiyeniz ?

**Comment by VB10** [comment]
acikcasi bunu benim projelerimde genelde single thread gittigimden burada dikkat ettigim bu isleri backgorundda yapmak oldu hep. paralel db istekleri yapmakla cok calismadim ama bu yaziya bakabilirsin

https://ali-akhtar.medium.com/mastering-in-coredata-part-11-multithreading-concurrency-rules-70f1f221dbcd
