### ISSUE TITLE
Flutter için dart dışında bir programlama dili kullanmak

### ISSUE THREAD

**Issue by HasancanCakicioglu** [VB10/vboverflow#30]
Merhaba hocam benim sorum şu mesela yapay zeka öğreniyorum bunu flutterdaki uygulamamda python ile yazmak istiyorum bunu yapabilirmiyim yapabilirsem dart dışında başka bir programlama dili kullanmak herhangi bir performans kaybına yol açarmı vb. sorunlara.Aynı şekilde javascript'de web için.yoksa bunlara hiç gerek yok mu pythonla yazdığım yapay zeka kodunu **eksiksiz** dart ile yazabilirmiyim veya javascriptle yazdığım kodu dartla. 
Yapabilirsem nasıl yapabilirim aynı projede dart,python,javascript kullanmayı.

**Comment by VB10** [comment]
Selammlar bu konu genel dünyada aslında çok önemli bir nokta. özellikle şöyle bakaibliriz
- benim de bildiğim arkadaşımla birlikte bir phthon modelimizi tensorflow lite üzerinden flutter projemize aktarmıştık https://pub.dev/packages/tflite bu tarz bir paket ile eğer bunu kullanarak yaparsan hiç aslında bir şey yapmadan sadece dart ile yapabilriisn
- Bir projemizde obejctive c gücünden kullnarak bir modelleme yapmıştık burada swift mobil bile yetmemişti ondan önce objective c yazı psonra mobile bridgey apmıştık yani iki platformda gerekiyor
- Son olarak apı yazımı noktası bazende misal bir işlemi web apilerle sağlıyoruz bunun içinde js or c# go gibi dillerden yada pythonun backend frameworku olan flask djongo ile servis olarak sunarak da sağlanabilir
