### ISSUE TITLE
[Flutter] Shared Preferences ve Update

### ISSUE THREAD

**Issue by hasanaliozdemir** [VB10/vboverflow#31]
Merhabalar, 

Uygulamamda shared_preferences paketi ile bazı verileri tutuyorum. Merak ettiğim konu ise şu;

Kullanıcı 1.1.2 versiyonundan 1.1.3'e yükseltti. Cihazda kaydedilen verilerin kaybolma veya bozulma ihtimali var mıdır?

Eğer böyle bir durum yaşanıyorsa,
```
{
    "places" : [
     {"id" : 1},{"id" : 2}
     ] 
}
```
şeklinde tutulan ve sıkça güncellenen bir listede eksilme yaşanabilir mi?
Eksilmeden kastım;
```
{
    "places" : [
     {"id" : 2}
     ] 
}
```

Bu bahsettiğim durumlar yaşanmıyorsa da tam olarak update sırasında bu verilere ne oluyor açıklarsanız sevinirim 😄

IOS ve Android için değişkenlik gösteriyor ise onu da bilmek isterim.

**Comment by yakupemeksiz** [comment]
Xml olarak telefonunda kayıtlı kalıyor. Update edildiğinde xml dosyası update olmuyor bu yüzden verilerde bir değişme olmayacaktır.

Konu hakkında:
https://medium.com/@prasanthiyarramareddy/storing-and-accessing-shared-preferences-f5da25ed572d

**Comment by VB10** [comment]
listleerde onemli olan referanstir referans bir yerde kullaniliyorsa ve sen o refereanstan direk silme yaparsan anca veri kaybi olur.
Veri kaybi @nolcreak dedigi gibi bir sorun yaratmayacaktir.
