### ISSUE TITLE
flutter to sql server

### ISSUE THREAD

**Issue by mehmetshakar** [VB10/vboverflow#36]
Merhaba Hocam,

apisiz olarak flutter ile ms sql server e bağlanıp crud işlemleri ve diğer sorguları çalıştırabilir miyim? Nasıl?

teşekkürler, iyi çalışmalar.

**Comment by sinanhaci** [comment]
Selam, 
MSSql server'a bağlanma isteğiniz, varolan bir database'i kullanma amacıyla mı?
Alternatif olarak mobilde verileri saklamak için bunu kullanabilrisiniz: https://pub.dev/packages/sqflite

Ayrıca MSSql kullanma konusunda kararınız kesinse biraz araştırma yaparak bir kaç yol buldum, örnek olarak bir url paylaşacağım. Deneyimleyip takıldığınız yerleri tekrardan buraya yazarsanız yardımcı olmaya çalışalım.

https://stackoverflow.com/questions/63145249/using-sql-server-with-dart

**Comment by mehmetshakar** [comment]
Yanıtınız için çok teşekkür ederim Sinan Bey,

veritabanı  uzak bir sql sunucudaki veritabanıdır, mvc core kullanıyorum api olarak ancak sanki performans problemi var, o yüzden dolaylı değil de direkt bağlanabilir miyim diye bakıyorum.

teşekkür ederim.

**Comment by sinanhaci** [comment]
Rica ederim iyi çalışmalar.

**Comment by VB10** [comment]
@mehmetsahakar her sneryoda dbye direk baglanmamak lazim mobilde client bazli paket ciktigimizdan clientta eski bir kod ortayi cok kotu hale getirebilir. Bu durumlarda direk db uzerinden is yapmak icin sql degilde firebasei rest servis olarak kullanabilirz https://medium.com/hardwareandro/5-minutes-firebase-rest-service-c990c1f70031
