### ISSUE TITLE
Notification and push routes

### ISSUE THREAD

**Issue by yakupemeksiz** [VB10/vboverflow#38]
Bir local notification ile istenilen ekrana rota push etmek istiyorum.

Uygulama arka plandan silindiğinde (suspended) bu işlemi gerçekleştiremiyorum.

Diğer tüm durumlarda çalışıyor.

**Comment by aea91** [comment]
** Uygulama arka plandan silindiğinde ** Bu cümlenin geçtiği tüm senaryolar Native ile yapılıyor. Hem Android hem IOS için.

**Comment by VB10** [comment]
eger app kapaliysa ve opush geldiyse aslinda firebase uzerinde inital message var onu alarak atilan son durumu alabilirsin.
Ama eger arka plandayken appe bir islem yapmak lazimsa slient notifcaitona bakabilrisin
