### ISSUE TITLE
Yazılıma Başlarken

### ISSUE THREAD

**Issue by ofsemiz** [VB10/vboverflow#4]
Selamlar Veli Hocam,

Şu anda Network Mühendisi olarak çalışmaktayım yazılım alanında ilerlemek istiyorum fakat şunu farkettim, şu ana kadar izlediğim kurslarda çok fazla bilgi kirliliği var. Hiç birinde yazılımın temel mantığı, temel konseptleri anlatılmıyor. Benım amacım mantığı öğrenmek ne bilim algoritma nedir veri yapıları nedır, nesne yönelimli programlama nedır nerelerde kullanılır vs. Kurslarda hemen yazılım programını indirip hesap makınası yaptırtıyolar. Kendı alanım ıcın dıyorum benim alanımda mesela vlan konusunu öğrenmek için hemen swıtch üzerindeki kodlara bakıp topolojiye dalmazsın, önce bir vlan nedir niye vardır olmazsa ne gibi sorunlar olur, vlan nasıl taglenir paket içeriği nasıldır en az 2 saatlik bir konu eğer temel seviyede öğreneceksen, hee eğer dediğim gibi bu tarz kurslara bakarsan adam sana 10 dk da swıtch içindeki komutları yazdırır çalışır da şakır şakır ama farklı bir topoloji istendği zaman boş boş bakarsın. Bu yüzden ben de aynı şekilde eğitim arıyorum acelem yok anlamak istiyorum sonrasında script öğrenme işi kolay diye düşünüyorum okuduğum araştırdığım kadarıyla. Aynı şekilde networkde vlan işini soktukten sonra ister huaweı cıhaz ıster cısco cıhaz üzerinde çalış vlan ı biliyorsan gerisi 15 dk da öğreneceğin script e bağlıdır. Bu konu hakkında yardımlarınızı beklıyorum nerden başlayabilirim ? Kitap mı alayım, bir yerden kurs mu izleyeyim izleyeceksem nelere dikkat etmem gerekir vs genel olarak yeni başlayan birine öğrenmek için tavsiyeler...

Teşekkürler. Saygılarımla.

**Comment by VB10** [comment]
Selamlar
Kitap konusunda tr sektorunde tek kitap bilirim sefer algan her yonuyle c# bunu okuyabilirsin,
Egitim olarak ise onerim basit algortima kurma adina java veya c# gibi alanlarda ilerlemek akabininde biraz front end teknlojlieri ile eger mac varsa swfit mobil  js react dart flutter gibi bunu pekistirmek.

Bu konularda o kadar yabanci content varki ozellike buralar igormek misal egghead gibi misal pluralsight gibi sitelere basvurmak.
Tr egitimleri genelde balik verme uzerine oldugundan dillerin core konseptilerini en iceriklerle alt yazili pekistirebilirsin.

Gunluk algortima sorulari ve cozumler cok iyi olacaktir bunun uzerine freelance sitelerden basit sekilde ilerleyip tasklar alabilirsin

**Comment by tunahanugrasir** [comment]
Hocam merhabalar, benim 2 küçük kardeşim var. Biri 7. sınıfa geçecek diğeri liseye geçecek. İkiside benim gibi bilgisayar mühendisliği okumak istediklerini söylüyorlar ama sadece lafta böyle. Ben abileri olarak onlarında yazılıma ilgi duymalarını istiyorum. Gün boyunca hep bilgisayar başındalar ama hep boş şeylerle uğraşıyorlar. Onları nasıl yönlendirebilirim ne gibi kitaplar videolar sağlayabilirim? İnternette oyun üzerine kurulu yazılım eğitimlerini pek sevmiyorlar. Birkaç gün önce C derslerini göstereyim dedim yaparken zevk aldılar ama iki gün sonra hiç bakmadılar bile. Tam olarak ne yapmam gerektiğini bilmiyorum. Yardımcı olursanız sevinirim hocam, iyi günler dilerim.
