### ISSUE TITLE
Apple developer account

### ISSUE THREAD

**Issue by kadirozenn** [VB10/vboverflow#41]
Apple cihazlarında kişilere özel private uygulamaları nasıl dağıtabilirim?

**Comment by ozkanozcan** [comment]
Android cihazlardaki gibi link göndereyim kurulum yapsınlar şeklinde dağıtım ios tarafında jailbreaksiz malesef olmuyor.

Kısa süreli kullanım olacaksa TestFlight üzerinden dağıtabilirsin. 

Uzun süreli olacak ama App Store üzerinden dağıtmak istemiyorsan inHouse dağıtım için Apple Enterprise hesabı alıp uygulamayı onunla imzalayıp dağıtım sertifikaları oluşturup dağıtabilirsin 

Araştırman gereken anahtar kelime "Inhouse distribution"

**Comment by sinanhaci** [comment]
Eğer cihazların id'sini developer hesabına kaydedersen, ipa çıktılarını cihazlara gönderebilirsin. 
Örn : https://www.diawi.com/
Ancak bunun sürdülebilir bir şey olduğunu düşünmüyorum. Test amaçlı bu işlemi yapacaksan arkadaşın dediği gibi testflight ile bu işi halledebilirsin.

**Comment by kadirozenn** [comment]
Öncelikle cevaplarınız için teşekkür ederim. 

TestFlight sorunumu çözmüyor. Çalıştığım şirkette firmalara özel ios uygulama geliştiriyorum flutter ile daha önce bu konuda herkese açık uygulama yayınlamaktan başka tecrübem olmadı. Apple business manager veya Özkan beyin dediği gibi Apple Enterprise hesabı ile bu sorunumu aşabilirmiyim?

**Comment by sinanhaci** [comment]
Evet aşabilirsiniz. Ayrıca şirketlere MDM çözümleriyle de IPA çıktılarını dağıtabilirsin. Örn: Intune..

**Comment by kadirozenn** [comment]
Sonuç olarak Apple business manager  hesabı açıp oradan devam ediyorum.

**Comment by ozkanozcan** [comment]
Enterprise hesap ile biz dünya çapında 3000-3500 civarı cihaza dağıtım yapıp uygulama kullandırtmıştık.  
cihaz sayısı sınırı olmadan uygulamanızı dağıtabilirsiniz.

**Comment by ozkanozcan** [comment]
Teknik destek lazım olursa [Hüseyin Usta](https://mobile.twitter.com/huseyinusta)  bu konuda Türkiyenin en iyi eğitmenlerindendir. Destek alabilirsiniz.

**Comment by kadirozenn** [comment]
Tamamdır çok teşekkür ederim vaktinizi ayırıp cevapladığınız için
