### ISSUE TITLE
SwiftUI @MainActor kullanımı hk.

### ISSUE THREAD

**Issue by endmr11** [VB10/vboverflow#42]
Merhabalar, 

SwiftUI da DispatchQueue.main.async kullanılsa da kullanılmasa da ViewModel sınıfına @MainActor eklemenin bir zararı var mı? Teşekkürler.

**Comment by MehmetKaranlik** [comment]
Actor property wrapper'ı datarace'i engellemek için geliştirildi. Context izole etmek üzerine çalışıyor. Multi-threading environment'ta aynı instance'ı okuma-yazma yaparken işlemi aynı loop'ta birleştirip sırasıyla bitmesini bekliyor. MainActor ise bu izole durumun Sadece main threadde olması için. UI'ni güncellediğin classlarda bkz. ViewModel main actor kullanmak mantıklı bir davranış. Sadece asenkron çalışması için Task'in içinde set edilmesi gerek.

**Comment by endmr11** [comment]
@MehmetKaranlik Teşekkür ettim kral

**Comment by VB10** [comment]
eline saglik @MehmetKaranlik
