### ISSUE TITLE
Some TextField errors, stackOverFlow

### ISSUE THREAD

**Issue by skyturkish** [VB10/vboverflow#43]
https://stackoverflow.com/questions/72747861/when-the-click-textfield-and-open-keyboard-so-many-error-appears-then-click-ne

**Comment by sinanhaci** [comment]
TextField'ı TextFormField yaparak denediğinde de sonuç aynı mı?

**Comment by skyturkish** [comment]
onu yaptım ve sadece SamsungSmartSugges.... keepsstopping hatası vermemeye başlıyor, kalanı aynı

**Comment by hasanaliozdemir** [comment]
bu değişikliği yaptıktan sonra aldığın hatalar uygulamanın işlevselliğini etkiliyor mu yoksa daha çok uyarı gibi mi?

**Comment by skyturkish** [comment]
işlevselliğini etkilemiyor  uyarı gibi ama DEBUS CONSOLE'da aşırı spam oluyor, ileride bilmediğim bir problemin kaynağı olabilirler diye çözüm arıyorum bir yandan bunlara

**Comment by hasanaliozdemir** [comment]
gerçek cihazlarda bu çok sık olan bir durum diye biliyorum, simülatörde de aynı şekilde spam atıyor mu?

Ayrıca AWS tarafından sağlanan paketler bile bu spam olayını yapıyor, sanırım sebebi gerçek cihazlardaki android sisteminde app üzerinde etkisi olan sistem uygulamaları.  Release yayınlanmış bir çok appte bu spam olayını gördüm sıkıntı çıkartmasa gerek diye düşünüyorum.
