### ISSUE TITLE
Api'den veriler çekiliiyor ama snaphot data null görüyor => type 'Null' is not a subtype of type 'Map<String, dynamic>' in type cast

### ISSUE THREAD

**Issue by nuriulgen** [VB10/vboverflow#46]
Future<List<User>?> fetchPostItems() async {
    try {
      final response = await _dio.get('$FIREBASE_URL/users.json');

      if (response.statusCode == HttpStatus.ok) {
        final datas = response.data;
        if (datas is List) {
          return datas.map((e) => User.fromJson(e)).toList();
        }
      }
    } catch (e) {}
    return null;
  }

**Comment by skyturkish** [comment]
tüm kodu sağlayabilir misin, ama şu anlık gördüğüm senin isteğinde liste dönmüyor, Map<String,dynamic> dönüyor, ilk başta, if (datas is Map<String,dynamic>) demen ondan sonra return (datas as List).map((e) => User.fromJson(e)).toList(); yapman lazım gibi. ama dediğim gibi daha fazla bilgi sağlarsan,en azından istek olarak nasıl bir şey istediğini, daha fazla yardımcı olabiliriz.

**Comment by nuriulgen** [comment]
Apiden  veriler geliyor ama  Future builder kısmı hep not found widget döndürüyor

 
![WhatsApp Image 2022-06-27 at 18 10 17](https://user-images.githubusercontent.com/45700377/175973807-c85d3cf9-2259-44ac-995e-a9f2e9ecbf16.jpeg)

![WhatsApp Image 2022-06-27 at 18 05 26](https://user-images.githubusercontent.com/45700377/175972848-9e867e1c-e472-46a6-94b3-0e16db3e9695.jpeg)

![WhatsApp Image 2022-06-27 at 18 07 17](https://user-images.githubusercontent.com/45700377/175973161-29b736ce-6b0b-4de6-959c-b465c5720e4a.jpeg)

**Comment by haznigulec** [comment]
FutureBuilder<Map<String,dynamic>> yaparsan null dönmeyecektir
