### ISSUE TITLE
Flutter'a başlamadan önce ne yapmalı? 

### ISSUE THREAD

**Issue by karaaliogluonur** [VB10/vboverflow#47]
Hocam öncelikle mutlu haftalar diliyorum. Umarım herkesin hali vakti yerindedir.

Ben bir şey danışmak istiyorum. İnşaat mühendisliği bitirdim ve şu an yüksek lisans yapıyorum fakat artık bu meslekte kendimde bir gelecek görmüyorum. Bu sebeple flutter çalışmaya başlamıştım. Önceden biraz python bilgim olduğu için dart diline çabuk alıştım. Fakat şu anda tam verim alamadığımı düşünüyorum. Acaba direkt flutter ile başlamakla hata mı yaptım? Flutter çalışmaya başlamadan önce bir hazırlık süreci gerekli mi, mesela flutterdan önce nelere çalışmalıydım? Cevabın için şimdiden teşekkür ederim. 🙏🏻

**Comment by ozkanozcan** [comment]
Veli hocam daha iyi bilir ama şu sanki iyi bir yol haritası gibi :

![FlutterRoadmap](https://user-images.githubusercontent.com/423519/175946559-0e3150e5-36a2-4d69-a080-93291416e4c3.png)

**Comment by VB10** [comment]
@ozkanozcan hocamin onerdigi bu yol cok guzel bir kere cok mantikli eline saglik

Ek olarak benim onerim su sekilde
- Dart dilini oop olarak iyi hale getirmek daha cok ogrenmek adina java oop konularina bakip mobile uygulamak
- mobilin ana noktarlarini bilmek feature setleri auth cache etc
- ui widgetleri iyi bilmek hizli gelistirmek
