### ISSUE TITLE
Flutter Web 

### ISSUE THREAD

**Issue by aea91** [VB10/vboverflow#48]
Merhabalar,
Flutter web te yeni versiyonu yüklediğimde canlıda yeni versiyon gelmiyor. 
Geçmiş temizlendiğinde ancak güncelleniyor.
Yenileme butonu koydum. Tüm cacheleri temizlemeye çalıştım yine olmadı.
Programatik olarak yeni versiyonu nasıl çekebiliriz internet tarayıcadan geçmişin temizlenmesi gibi.

**Comment by okmsbun** [comment]
Merhaba
Ben bu sorunu (KISMEN) bu şekilde çözdüm.
Build almadan önce `web/index.html ` de `scriptTag.src = 'main.dart.js?v=` 'e farklı versiyon numaraları verilebilir.
Aynı şekilde buna da `var serviceWorkerUrl = 'flutter_service_worker.js?v=`

Daha fazla ayrıntıya buralardan ulaşabilirsin.

> [https://stackoverflow.com/a/61287128/15285043](https://stackoverflow.com/a/61287128/15285043)

> [https://medium.com/flutter-community/caching-in-flutter-for-web-42b3ae0e348f](https://medium.com/flutter-community/caching-in-flutter-for-web-42b3ae0e348f)

> [https://github.com/flutter/flutter/issues/71333#issuecomment-735217435](https://github.com/flutter/flutter/issues/71333#issuecomment-735217435)

> [https://stackoverflow.com/a/61720981/15285043](https://stackoverflow.com/a/61720981/15285043)

**Comment by aea91** [comment]
Dediğiniz adımları yaptım çözüm olduğunu düşünüyorum.
Teşekkürler

**Comment by VB10** [comment]
@okmsbun eline saglik
