### ISSUE TITLE
[Flutter] Not converting to Turkish characters when making upper case

### ISSUE THREAD

**Issue by azaderdogan** [VB10/vboverflow#49]
for example:
i -> I

**Comment by kadirbekar** [comment]
https://pub.dev/packages/turkish

This library would be helpful for that kind of scenarios.

**Comment by azaderdogan** [comment]
> https://pub.dev/packages/turkish
> 
> This library would be helpful for that kind of scenarios.

Thank you. this works for me.

**Comment by kadirbekar** [comment]
You are welcome.
