### ISSUE TITLE
BuildContext isn't a valid override of 'Store.context' 

### ISSUE THREAD

**Issue by muhammedakyuzlu** [VB10/vboverflow#5]
[flutter-architecture-template](https://github.com/VB10/flutter-architecture-template) serisinde
settings_view_model.dart
abstract class _SettingsViewModelBase with Store, BaseViewModel {
}
bir hata aliyorum ayni anda Store ve BaseViewModel with   edemem 

HATA BU 
abstract class BaseViewModel
package:start/core/base/model/base_view_model.dart
'BaseViewModel.context' ('BuildContext? Function()') isn't a valid override of 'Store.context' ('ReactiveContext Function()').dartinvalid_override
store.dart(11, 23): The member being overridden.

**Comment by VB10** [comment]
bu hqatanın yeri arcihtecture template repoosu burada buna gerek yok ikincisi çözüm olarka var olan arcihtecture templaeti clone edersen direk çalıştığını göreceksin
