### ISSUE TITLE
Model classlarının yönetilmesi Flutter

### ISSUE THREAD

**Issue by EyupEnsarAlmaz** [VB10/vboverflow#50]
Elimdeki api den veriyi çekmek için model oluşturdum. Ancak modelin alt classları mevcut. Ben ise service yazarken ana classı baz aldığım için alt classlardaki verileri göremiyorum.  Alt classlara ulaşmak için nasıl bir yol izlenmeli? Cevaplarınız için Teşekkür ederim.  

Örnek;
![Screenshot_5](https://user-images.githubusercontent.com/67228806/176021908-295038c5-5fce-489e-a973-77d13d3f8b12.png)
![Screenshot_6](https://user-images.githubusercontent.com/67228806/176021924-7e51b17a-660a-4028-843d-c3cff2c3bfdd.png)

**Comment by kadirbekar** [comment]
Her bir model classınız içerisinde servisten gelen datayı parse etmek için gerekli metotları (Örneğin gelen datayı parse etmek için **fromJson(Map<String, dynamic> json)** veya servis tarafına veri göndermek için **toJson** gibi metotlar) yazabilirsiniz.  Daha doğrusu modellerinizi yukarıdaki gibi tutarsanız işlem yapmanız daha temiz ve kolay olacaktır diğer şekilde map şeklinde de iç içe değerleri okuyabilirsiniz. 

Örneğin servisten datayı okumak istiyorsunuz. 

``final TranslateModel response = await service.fetchTranslateModel();``<br>
``inspect(response["phonetics"][0]["text"]); ``

gibi okuma yapabilirsiniz. Fakat hata yapma ihtimali yüksek. Elle key değeri yazıp değer okumaya çalışacaksınız.

Diğer bir şekli ise:

[Json serializable](https://pub.dev/packages/json_serializable) paketini kullanırken parse metotlarının paket tarafından üretilmesi için ise şu şekilde bir kullanım var:

**_$ModelAdiFromJson(json)** veya data göndermek için **_$ModelAdiToJson(this)** gibi. Bu paketin standartıdır. 

Örneğin şu an ki resim için bir çözüm üretmek gerekirse:

**TranslateModel** içerisine:

``factory TranslateModel.fromJson(Map<String, dynamic> json) => _$TranslateModelFromJson(json);``

**Phonetics** içerisine:

``factory Phonetics.fromJson(Map<String, dynamic> json) => _$PhoneticsFromJson(json);``

Servisten veri geldiğinde model içerisindeki alanlarınız (field) hatasız bir şekilde eklendiyse bu alanlara erişip değeri okuyabilirsiniz. Örneğin:

``final TranslateModel response = await service.fetchTranslateModel();``<br>
``response.phonetics 
şeklinde bir veri okuması yapabilirsiniz.``

Tabii gerekli annotationlar eklenir, üretilecek olan modelin yolu bu dosya içerisinde doğru bir şekilde tanımlanırsa script çalıştırıldığında modeliniz hazır olacaktır.

dosya yolu tanımlamak için

``part 'model_adi.g.dart'`` en üst classın üstüne ekleyebilirsiniz.

**Comment by VB10** [comment]
@kadirbekar süper teşekkür ederim gayet yeterli
