### ISSUE TITLE
Goole Map Init'i Isolate ile yapmak

### ISSUE THREAD

**Issue by guccisekspir** [VB10/vboverflow#51]
Google Map init olurken çok ciddi bir bekleme söz konusu olabiliyor. [Flutter'da issue](https://github.com/flutter/flutter/issues/28493) açılmış durumda  ama hala bir çözüm yok(2019'dan beri). Bunu Isolate ile çözebilmemiz mümkün müdür ? Mümkünse nasıl ilerlemeliyiz ?

**Comment by aea91** [comment]
Ek olarak iOS ta son Google Maps versiyonunda aniden kapanmalar oluyor. 
Çok fazla marker kullanınca da muazzam bir kasma ve yine atma oluyor.

**Comment by alperenekin** [comment]
Flutter'da platform channel ile native e yapılan işlemler Isolate olarak yapılamıyor. Sanıyorum ki google maps de bu şekilde çalıştığı için isolate ile mümkün olmayabilir. Ancak native kullanan pluginleri isolate gibi kullanabilmek için [isolate_handler](https://pub.dev/packages/isolate_handler) plugini var belki iş görür bu durumda. Deneyip sonucu paylaşırsanız güzel olur görmek açısından 👍

**Comment by VB10** [comment]
simdi bu konuyu ben bir kere yaptim ama bulursam paylasacagim o kodu ancak sunu soyleyebilirim bence eger map gozukecekse google static api kullanin sadece bir noktayi gostermek icin genelde business te amac o noktayi gostermek oldugundan bu topa girmek icin ekliyoruz google static map apide route bile ciziliyor
https://developers.google.com/maps/documentation/maps-static/overview

**Comment by VB10** [comment]
bulunca baska bir issuede paylasacagim suan buna bir cozumum yok diyelim
