### ISSUE TITLE
Responsive Tasarım

### ISSUE THREAD

**Issue by skyturkish** [VB10/vboverflow#52]
Projedeki her şeyi ; textstyle'daki size, Paddings, widget's height & width. Her şeyi dynamicHeigh ve dynamicWidth sayesinde MediaQuery üzerinden yapıyorum. Ve hiç bir sıkıntı çıkmıyor başka ekranlara geçtiğim zaman, eninde sonunda sabit değer yok projede. Veli hocanın Responsive videosunda Expanded ve flexler ile yapıyordu, ben böyle yapıyorum. ikiside eninde sonunda aynı amaca hizmet ediyor ve istenilen tüm özellikleri sağlıyor ama daha önce görmedim benim gibi yapan, acaba bunun bilmediğim bir dezavantajı falan mı var acaba ? 

![Screenshot_3](https://user-images.githubusercontent.com/73424678/176485706-d73aedb2-0161-4583-8457-832dfd3ebd63.png)
![Screenshot_1](https://user-images.githubusercontent.com/73424678/176485721-a35ee8c6-580a-41b5-aadc-a977f31dfa5f.png)
![Screenshot_2](https://user-images.githubusercontent.com/73424678/176485725-10b8d395-2b3f-4b70-a52c-46b3b3afb270.png)

**Comment by VB10** [comment]
bu kullanım güzel biz misal respoviewrapper gibi paketlerle çok büyük deviceiler için yeni eklemler yapıyoruz.

Özetle
- Eğer sayfan flex ile yapabiliyorsan en temiz kullanım
- Sayfan list ise daha generic bir görüntü için dynamic iyi ama genelde listview sonsuzluk olduğundan standart size'lar iş görür
