### ISSUE TITLE
Node Js için Öğrenme Yolu

### ISSUE THREAD

**Issue by mustafacavusoglu** [VB10/vboverflow#54]

**Comment by mustafacavusoglu** [comment]
JavaScript temellerini bilen biri nodejsi daha iyi öğrenmek için önce typescript öğrenmeli mi? 
Yol olarak tavsiyeleriniz nelerdir? 
Teşekkür ederim

**Comment by VB10** [comment]
@mustafacavusoglu bu konuda bir kac bilgim var ama konunun icinde cok olmadigimdan sallamak istemem.
- benim react yazdigim donemden var sayarak
- ts ogrenmek bence cok onemli hem oop uygulamak hem test code yazbilmek icin diyeblirim.

**Comment by VB10** [comment]
birde buna bakabilirsin   https://github.com/aliyr/Nodejs-Developer-Roadmap

![image](https://user-images.githubusercontent.com/17102578/177057980-4b3190a9-dc53-4c02-9405-b116b266e1ee.png)

**Comment by mustafacavusoglu** [comment]
Teşekkür ederim abi.
