### ISSUE TITLE
Adaptive

### ISSUE THREAD

**Issue by Eldar2021** [VB10/vboverflow#56]
Projede flutter_screenutil kullanmayı önenriyor musunuz? Kullanırsak performans sorunu yaşayabilirmiyiz?

**Comment by abdullahkaraboga** [comment]
Teknik olarak sorunuzun cevabını bilmiyorum ama aynı sayfa tasarımı için ayrı ayrı flutter_screenutil ve MediaQuery kullanıp Flutter Performance ve Android Profiler kullanarak performansı kendiniz deneyimleyebilirsiniz.

**Comment by Eldar2021** [comment]
Teşekkür ederim
