### ISSUE TITLE
flutter'ın kendi orijinal kodunu değiştirmek

### ISSUE THREAD

**Issue by skyturkish** [VB10/vboverflow#59]
https://stackoverflow.com/questions/72899228/change-the-original-fluttersany-framework-code 

Projede status bar'ı transparent yapmam lazımdı onun için Theme'i kullanarak tüm projede transparent yaptım ama ona ek olarak SafeArea(top:false) yapmam lazım bir de yanında, ben de dedimki 30 yerde top:false yazacağına gider orijinal kodu güncellerim, varsayılan değer true idi ben false yaptım ve sorun çözüldü ama :lotohmm: bu iyi bir şey mi, yapılmalı mı , yapılacaksa hangi durumlarda yapılmalı.
![Screenshot_3](https://user-images.githubusercontent.com/73424678/177793876-02896067-496d-4265-a703-6599407a5435.png)

**Comment by skyturkish** [comment]
Öyle böyle değilmiş, aşırı kötü fikirmiş orjinal koda dokunmak, dokunmayalım :nodders:

**Comment by skyturkish** [comment]
```
class mySafeArea extends SafeArea {
   Widget child;

  mySafeArea({
    Key? key,
    required this.child,
  }) : super(
            key: key,
            child: child,
            top: false,
            bottom: true,
            left: true,
            right: true,
            minimum: const EdgeInsets.all(0),
            maintainBottomViewPadding: false);
  @override
  Widget build(BuildContext context) {
    return SafeArea(child: child);
  }
}
```

**Comment by VB10** [comment]
kendisi yazdi kendisi bozdu :)
