### ISSUE TITLE
IOS Background Task Calistirma Sorunu

### ISSUE THREAD

**Issue by ibrahimcss** [VB10/vboverflow#6]
Merhaba veli hocam, background tasklarda flutter ile bir cozum bulamayinca native olarak swift ile bir kac denemem oldu ama arka planda 10 dakikada bir mesaj gonderme islevi yine basarisiz ios background'da kill ediyor. Apple tarafinin dokumanlarida bu konu hakkinda imkansiz oldugunu belirtiyor,
sizler background tasklar hakkinda bir gelistirme yaptinizmi ios tarafinda ? yada native olarak'ta periodik islemler backgrounda imkansizmi ios icin ?

**Comment by VB10** [comment]
Selamlar
Bu doğru bir done doğrudan bir app'i arka tarafta anroid gibi bacgkrund task yapmana izin vermiyor apple bunun iki yöntemine sadece ok veriyor
- Music app veya Map app olacak

Diğer nokta bunu Workmanager ile yapabilirsin ama ios tarafında bu 10dk'nın net bir karşılığı yok genelde 1h da atar 10dkda atar yani orada bir netlik yok
https://pub.dev/packages/workmanager


Birde bu silent notification yapısına bakabilirsin
https://github.com/firebase/flutterfire/issues/8277

**Comment by aea91** [comment]
Silent notification gelir gelmez konumu alıp bir kaç sorgu yapıp sonra post edebilir miyiz? Burada yapabileceğimiz işlemlerin bir sınırı var mı? Teşekkürler

**Comment by ibrahimcss** [comment]
anladigim kadari ile ya notification disinda herhangi islem yapamazsin, benimde gelistirdigim bir projede bacground task ile bazi datalari periodik olarak post etmem gerekli ama ios tarafi bacground tasklara izin vermiyor, trik olarak notification ile yapmayi planladim ama imkansiz
