### ISSUE TITLE
[Flutter] Uygulama tamamen kapalı durumdayken konumunu alıp servise yollamak

### ISSUE THREAD

**Issue by azaderdogan** [VB10/vboverflow#60]
Merhabalar,
Uygulama tamamen kapalı durumdayken örneğin 5 dakikalık periyotlarla konumunu alıp servise yollamam gerekiyor. Böyle bir durumda nasıl bir yol izlemeliyim sizce? Baktığım zaman alarm manager aklıma geldi fakat sanki çok kullanışlı olmayacak gibi. Yani amacım belirli bir lokasyonun yakınından gectiği zaman bildirim yollamak.
Teşekkürler şimdiden.

**Comment by aea91** [comment]
Android ve IOS için servis yazarak. Flutter ile çok problemli bu hususta Native şart.

**Comment by abdullahkaraboga** [comment]
pub.dev'de şöyle bi paket var. İsterseniz bi göz atın.

https://pub.dev/packages/background_location

**Comment by aea91** [comment]
> pub.dev'de şöyle bi paket var. İsterseniz bi göz atın.
> 
> https://pub.dev/packages/background_location

Uygulama öldürüldüğünde bu paket işe yaramıyor.

**Comment by Barismano** [comment]
Hocam Şöyle bir paket var bak istersen ben bu paketi kullanıyorum kullanıcı uygulamayı kapatsa bile servis belirlediğim endpointe lokasyon gönderiyor 5 saniyede bir. Bu paketi bulana kadar çok uğraştım umarım işine yarar

paket : https://pub.dev/packages/background_locator

**Comment by azaderdogan** [comment]
> Hocam Şöyle bir paket var bak istersen ben bu paketi kullanıyorum kullanıcı uygulamayı kapatsa bile servis belirlediğim endpointe lokasyon gönderiyor 5 saniyede bir. Bu paketi bulana kadar çok uğraştım umarım işine yarar
> 
> paket : https://pub.dev/packages/background_locator

aaa hocam super bu. Deneyeceğim bunu. cok tesekkur ederim.

**Comment by Barismano** [comment]
Ne demek Hocam ne mutlu  yardımcı olabildiysek 👍

**Comment by kadirozenn** [comment]
Merhaba, bahsettiğiniz problem karşısında daha önce flutter_foreground_task paketini kullanarak 5 dakikada bir konumu alarak sunucuya göndererek problemi çözmüştüm. Yalnız arka plan servisi başladıktan sonra bildirim çubuğunda uygulama çalıştığına dair bir bildirim çıkıyor.

paket https://pub.dev/packages/flutter_foreground_task/versions

**Comment by VB10** [comment]
@kadirozenn  @Barismano net cozumler lokasyonu iosda dogrudan arkadan dinlemenin bir yolu bunun icin location app yapip kullanicadan izin almak gerekiyor ve surekli dinleme gibi calsiiyor slient notifniaciton konusunada bakabilrisin ayri oalrak
