### ISSUE TITLE
Future tamamlandıktan sonra otomatik olarak sayfaya navigate etme

### ISSUE THREAD

**Issue by EyupEnsarKus** [VB10/vboverflow#62]
Herkese selamlar. Elimde bir buton var ve butona bastığımda beni farklı bir sayfaya yönlendirecek. Yönlendireceğim sayfaya dışarıdan data passliyorum ancak  Ben bu butona bastığımda verinin geldikten sonra sayfanın açılmasını istiyorum. Future tamamlandıktan sonra yönlendirilmesini istiyorum.Bunu nasıl yapabilirim yardımcı olursanız çok sevinirim

**Comment by endmr11** [comment]
.then ile yapabilirsin ama tavsiye edilmiyor. future fonksiyonu çağırdığın butonu async yapabilirsin veya yeni bir future fonksiyonu açıp orada çağırdığın fonkisyonu await ile bekleyebilirsin.

void main() {
  getAllData();
}
Future<void> getAllData() async {
  print("test1");
  await Future.delayed(Duration(seconds: 5)); //Future işlemin örnek servise istek atmak `http.get()`
  print("test2"); //Yapacağın Navigate işlemi
}

**Comment by abdullahkaraboga** [comment]
FutureBuilder çözüm olabilir diye düşünüyorum. 

```
FutureBuilder(
future: data(),
builder: (BuildContext context, AsyncSnapshot snapshot) {

if (snapshot.hasData) { // data varsa

//kodunuz

} else { //datanın olmadığı durumda
//kodunuz
}
```

Ekstra zaman için Timer da ekleyebilirsiniz.
