### ISSUE TITLE
Graphql

### ISSUE THREAD

**Issue by isshort** [VB10/vboverflow#63]
Herkese selamlar! 
Model (toJson,fromJson) oluşturmadan graphql query ile çalışabilir miyiz.
Yani querylerimiz direck Map<String,dynamic> cunku graphql'da calistigimizda cok nested objeleri gererktiriyor.

**Comment by VB10** [comment]
yani yapabilrisin.  bunu kullanabilrisin https://pub.dev/packages/graphql
