### ISSUE TITLE
Flutter uygulamasındaki videolar için en iyi backend

### ISSUE THREAD

**Issue by aysealmaci** [VB10/vboverflow#64]
İçersinde birçok video olacak bir flutter uygulaması için backend olarak firabase kullanmak mı daha mantıklı olur elastic, mongo db gibi teknolojileri kullanmak mı? Uygulama uzerinde açılmak istenen video seçildiğinde veri tabanından o videonun yolunu alıp media server yardımı ile açılacak.

**Comment by VB10** [comment]
selamlar
burada firebase storage acisindan video vs hiz o bir cok paramatre ve flutter ile kolay uyumu sayesinde aslinda cok kolay bir sekilde entegre edeilebilir ama amazonun s3 image store hizmetide cok iyi hizli ve daha fiyat olarak ucuz diyebilrim.

Gunun sonunda baslarken firebase guvenli iyi bir secim ama devaminda fiyat icin dusunmekl lazim.

Kendi suncunuzda bu isi db cozumleriyle yapmaniz da iyi aslinda ama bu seviyede dev, bulmak baska bir yol acabilir takima gore bu karar verip devam edilmeli aslinda.

**Comment by aysealmaci** [comment]
> 

Cevabınız için çok teşekkür ederim.
