### ISSUE TITLE
Reordablelistview.builder ile liste elemanlarını sıralama

### ISSUE THREAD

**Issue by Barismano** [VB10/vboverflow#65]
Merhaba timer ile periyodik olarak rest api den json datası alıyorum ve bunu reordablelistview.builder ile göstermek ve liste elemanlarını isteğe bağlı sıralamak istiyorum  bunu nasıl yapabilirim?

**Comment by abdullahkaraboga** [comment]
makale: https://medium.flutterdevs.com/reorderable-listview-in-flutter-731324f0677b

örnek repo : https://github.com/flutter-devs/flutter_reorderable_listview_demo

**Comment by Barismano** [comment]
hocam bu örneklerde lokaldeki veriler kullanılıyor ben veriyi restapiye http.get ile 10 saniyede bir istek atıp alıyorum sonra gelen veriyi future ile gösteriyorum

**Comment by VB10** [comment]
@Barismano ayni sekilde kurgulayalbirsin burada local veya future olmasi gerek yok sadece future builder yapma nromal bir setstate vs il yonet

**Comment by Barismano** [comment]
Tamamdır hocam
