### ISSUE TITLE
Clipboard 

### ISSUE THREAD

**Issue by Adiladil000** [VB10/vboverflow#68]
Veli abi Selam . Panoya metin kopyalamak istiyorum ama sadece metnin bir kısmı kopyalanıyor. Misal: 10 kelimeden oluşan cümlenin sadece 6 tanesi gözüküyor ve üç nokta geliyor. Bence panonun hafızası zayıf.
![kod](https://user-images.githubusercontent.com/88295387/179582396-5ae432c5-a0cb-4c5e-9ddf-428fe8ee3a9a.png)

**Comment by kadirozenn** [comment]
Merhaba, paylaştığınız kodu test ettim herhangi bir bahsettiğiniz problemle karşılaşmadım. 

Bir  method ve Extension yazıp test ettim gine bahsettiğiniz problemle karşılaşmadım. Acaba verileri kontrol ederken gözden kaçırdığınız bir şey olabilir mi ? 

` setClipBoard(BuildContext context, String text) async {
    await text.clipBoard();
    final clipPaste = await Clipboard.getData(Clipboard.kTextPlain);
    ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text("${clipPaste!.text ?? ""} kopyalandı.")));
  }`

`extension ClipBoard on String {
  clipBoard() async {
    await Clipboard.setData(ClipboardData(text: this));
  }
}`

**Comment by VB10** [comment]
bidligim konuda bir problem yok ama tekrar bir yeyit etmek lazim problem devam ediyorsa ilgili flutter core repoya issue acaiblrsin
