### ISSUE TITLE
auto_route rebuild in botttom navigation 

### ISSUE THREAD

**Issue by shahmirzali49** [VB10/vboverflow#69]
auto_route navigasyonda bottom navigation sayfasyi veya widgeti her defasinda rebuild oluyor. senaryo şöyle: bottom navdan bir sayfaya gidiyorsun ve ordanda tamamen farki bir sayfaya gitmemize ragmen rebuild oluyor. birde son olarak auto_route un sundugu AutoTabsRouter veya auto tab scaffold falan kullanmazsak, normal scaffold page view ile bottom nav yaparsak sorun olmuyor. cunki auto_route-un navigation stack-inde olmuyor artik.

example dosyasini asagi birakiyorum video ile birlikte. rebuild kismini debug consoledan takip edebilirsiniz.

dosya: https://mega.nz/folder/GGY2VQxa#rarnevAFuFmgVRAJX3KrKg

video : 

https://user-images.githubusercontent.com/49102327/179681419-ba117910-ad13-4f87-90c9-c19a4d4839da.mov

**Comment by VB10** [comment]
auto route instanceini olsutrugun yere bir bak derim bu tarz issueleri auto_route reposuna atarsan daha iyi sonuclar alabilrisin. 

benim repoda tekrar bir teyit et
