### ISSUE TITLE
Apple Store Yayımlama kriteri

### ISSUE THREAD

**Issue by mehmetsahakar** [VB10/vboverflow#7]
Merhaba Hocam,
  
Sizin deneyimlerinizden yararlanarak sormak istiyorum,
(Genelde sizin videolarda material kullandınız)
Flutter projesinde material ı kullandım (cupertino yu kullanmadım), merak ettiğim durum şu apple store sıkıntı çıkarır mı acaba?
Sıkıntı çıkaracaksa material ı cupertino ya çevirmek çok zor sanki, pratik yöntemi var mıdır?
Çok teşekkür ederim.
 
İyi çalışmalar.

**Comment by VB10** [comment]
Tasarım konusunda apple tarafı sorun çıkartmıyor genel olarak kullandığın pratice senindir ama
- Misal ekran görüntüsü koyarken apple telefon olması
- Misal google signin vvarsa apple signin olmalı gibi konulara takılıyor

Eğer platform spesific çözümler ekleyeyim dersen bu paketti gibi yapabilirsin
https://pub.dev/packages/flutter_platform_widgets
