### ISSUE TITLE
Yeni mezun bilgisayar mühendisi iş arayışında nasıl bir yol izlemeli?

### ISSUE THREAD

**Issue by nagihanarabaci** [VB10/vboverflow#70]
Yeni bilgisayar mezunu ve tecrübesiz kişinin temel seviye veya orta seviyeye yakın Flutter bilgisi ile başvurularında dönüş alamamasına karşın nasıl bir yol izlemesi gerekmektedir ?

**Comment by VB10** [comment]
bir expert ve yillarini vermis birisi olarak ne yazik ki tr flutter ilanina basvurmus geri dahi donulmemis birisiyim ondan dolayi tr matematigi cok farkli calisiyor.
- Burada bir cok sirket native yazdigi icin kurumsalda yer almak istiyorsak biraz fazla calisip java veya swift ile bir kac standart app misal web servisten data parse, local islemler ekran cizimi gibi
- Flutter da is bulmak icin ise en iyi yol freelance camiasi fakat orada biraz ceviklik ve is bilgisi araniyor projerlere daha dusuk fiyatlar verip bir iki proje bitirmek iyi bir olcut olabilir
- Mobilde mimarileri kavrayip feeture setlerini bilmek cok onemli bir nokta.
- Sirketlerde internal olarak yazilan projelerde flutter kullaniliyor oralarda guclu olma adina flutter ve native birlikte goturulebilir
