### ISSUE TITLE
Bilgisayar mühendisliğinde alan seçimi nasıl yapılmalıdır?

### ISSUE THREAD

**Issue by samet-nalbant** [VB10/vboverflow#71]
Merhaba,
Yazılım teknolojilerinde alan seçimi nasıl yapılmalıdır? Kendine bir alan seçmeye çalışan arkadaşlara verebileceğiniz tavsiyeler nelerdir? Mezun olup bir alanda çalışmaya başladıktan sonra farklı alanlara yönelmek mümkün müdür? Bunu yaparken karşılaşılması muhtemel zorluklar nelerdir? Mezun olmadan bir alan seçip ona yönelmek en iyisi midir?

**Comment by erenkulaksiz** [comment]
Selamlar Samet. Ben mühendislik değil 2 yıllık önlisans programı olan bilgisayar programcılığı bölümündeyim. Daha 2. sınıfa yeni geçtim. Aynı zamanda toplam 1.5 yıldır çalışıyorum, yani yazılım alanında belli bir fikir sahibi olduğumu düşünüyorum. Bu arada tavsiyelerim sadece Backend ve Frontend yani web & mobil üzerine olacak. Yazılım teknolojileri çok geniş bir dal. Benim embed sistemlere veya uçak beynine kod yazma gibi deneyimlerim yok. Yaşadığım deneyimlere göre bilgi aktaracağım. Dediklerim umarım fikir verir ve fayda sağlar.

1. Alan seçimini yaparken beni yönlendiren şey zevk alıp almamaktı. İlk başta hobi olarak başladım zaten. Hatta ilk olarak backend ile çalışmaya başladım. O zamanlar motion graphics yapıyordum, yazılımla da ilgiliydim, tasarımdan anlıyordum yani, baktım frontend daha mantıklı çünkü hem motion graphics tarafından gelecek tasarım deneyimimi kullanabileceğim, hem de birtakım yazılım dillerinden öğrendiklerimi bu tasarımlara katabilecektim. Bu yüzden Laravel ile ilerlettiğim php kariyerini yaklaşık 1-2 ay içerisinde bıraktım frontend'e yöneldim. Zaten backendde çok ilerlememiştim.
- Burada vereceğim tavsiye, tabii ki neden zevk alıyorsan oraya yönelmen olabilir. Diğer tavsiyem ise, deneme yanılma yaparak ben bunu yapabilir miyim, kariyerim tamamen bundan oluşsa sıkılır mıyım diye sorman. Kesinlikle sırf para kazanmak için bunu yapmak zorundayım diye kendini zorlamaman (şartlar el veriyor ise).

3. Mezun olup çalışmaya başladıktan sonra farklı alanlara yönelmek mümkündür. Ancak ışığın kırılımı gibi bir kırılım söz konusu olacağını düşünmüyorum. Ben backend'den frontend'e direkt geçiş yapabildim çünkü backend tarafında çok ilerlememiştim. 

4. Mezun olmadan bir alan seçip ona yönelmek şuanki şartlarda yapılabilecek en iyi harekettir diye düşünüyorum. Hem harçlık çıkarma açısından (js sayesinde kendime motor alabildim, harçlık çıkarttım :D) Ben daha yeni 2. sınıf oldum, ama 1.5 yıldır çalışıyorum mesela. 22 yaşında mezun olup yeni çalışmaya başlayacak birisi çalışmaya başladığında ben o zaman neredeyse 3.5 yıl deneyimli olacağım. O yüzden erken başlamak her zaman iyidir. Bazı insanlar erken başlamayın, gençliğinizin tadını çıkarın diyorlar. Onlara da bir şey diyemiyorum, evet gençliğimizin tadını da çıkarmamız gerek ancak benim babam fabrikatör değil. Bizim gelirimiz aşırı ileri seviye değil. İllaki çalışmam gerek. Belki erken öğrenmenin faydası ile startup kurup hayatın keyfini daha fazla çıkarırız kim bilir

**Comment by VB10** [comment]
Selam samet cok onemlı bır nokta belkı buna yazdıklarımız etki yaratacak ama lütfen kim ne yazarsa yazsın ilk unutmayacağımız bir şey kimse altın sepette sana bir şey sunmaz hangi bölümü seçersen seç aynı şey yaşanacak yaşandı.

### Alan
Bu dünyanın belki en zor sorusu ama en aslında basit cevabı olan yer. Birincisi bizim sektörde denemden eğer kulakdan duyma haraket edersen asla kendi yorumunu katamazsın. Bundan ötürü alan dediğin şey üç aslında disiplin hatta iki.
Birisi Backend
Diğer Frontend
[DEV OPPS bu 2020 sonrası]
Birde mobil var ikisinin ortası neden dersen genelde front end web site işlerinde network olmadığında hiçbir şey yapılmaz ama mobilde bu durumda handle edilip musterıye daha iki tarafı da vermiş oluyoruz.

Backend disiplini aslında yazılımın yıllardır olduğu ilk nokta ama önceden bir şekilde yapılan webisteleri database'ler ile ilişki kuruyor bu yüzden backend dediğimiz yani işi yapan asıl abilere ihtiyaç yoktu. Sonradan işler büyüdü web geldi mobil geldi saatler geldi ve dediler ki işi yapan bir yer kuralım bizim hepsine bu haber versin bu konuşsun buda servisler dediğim kavram oldu ve şuan tüm dünyadaki applerin arkasında güçlü olmasını sağlayan backend yapıları var.

Burada database kavramı karşımıza çıkıyor buda aslında yine backendin içindeki bir ayrı dal burada özellikle data temizleme data yapıları kurma çok büyük projelerin en önemli kavramlarını kurma üzerine birde security layer'lerini yazma kısmı oluyor çok komplike işler oluyor ve olmazsa olmaz bir katman.

Dataya gelmişken karşımıza DATA Analyıtcis alanı geldi işte buda yazılım tarafının başka bir disiplini iki şekilde bölünüyor birisi kod yazmadan daha çok hazır toolar power bi benzeri hizmetlerle yapmak diğeri ise data scientest dediğimiz dataları normalizasyonu vs işleri ile uğraşıyor.

Özetle backend bu bunların hepsi bittiğinde karşımıza hadi productiona demeden önce kardeşim bu datalar doğrumu açığımız var mı diye backend Q/A enginer dediğimiz test mühendsilerii çıkıyor buda kendi içinde ikiye ayırlıyor. Selenium gibi fw kullanarak otomasyonalr yazanlar bide daha local kalıp manuel olarak yapanlar var.
[2020 sonrası artık buradan sonra devops geliyor anltıcam]

Front end 

Buda yazılımın backende daha kolay bir alanı ama bir bakıma en zor alanı çünkü bir yazılımın kaliteisni burası belirler fakat bu kalite doğrudan backende bağlanıtlıdır. Sen istediğin kadar iyi bir ekran tasarla backenden cevap 30sn gelrise kimse kullanmaz. Bu alanda kendi için js libraryleri fw olmak üzere bir kaç dala ayrılıyor. 
Özellikle son zamanda react gibi kendini çok popülerleştirmiş libraryler çok popüler burada öğrenilmesi gereken atomic designler, birden çok ekranda çalışma  vs vs. Burası bır tık daha misal 6 ayda bir şeyler çıkartabileceğin ama aslında 6 yılda gerçek sonuca uğraşabileceğin yer insanlar genelde bir iki site yapınca oldum diyor ama iyi bir site ws kodlamak için tp çok onemli. 

Front end kısmında mobil ise son zamanların en popülerlerinden zira herkesde telefon olduğu için çok rahatlıkla insanlara erişebiliyorsunuz burada ise front endin dışında oop diller swift java kotlin dart gibi js rahatlığından ziyade oop gücüyle birleşmiş diller bizi karşılıyor ki bende bunu çok seviyorum oop güclü dillerle olmak değer katıyor. Burada  android ios corss gibi kavramlar var bunların üçü son zamnda aslında hep aynı benzzer kodlarla yazılıyor özellikle swfitui jetpack flutter gibi
bunların birini seçmek için keisnlike deneyip kendine yakın olanı seçmek lazım


Ve 2020 sonrası devops
Artık yazılımlar bir şekilde yazılıyor projeler çıkıyor fakat çok fazla proje çıkan yerlerde büyük takımlarda kimse bu süreçlerle uğraşmak istemiyor açıkcası bu sebepten ötürü insanlar bu işleri yöneten ekipler kurdular development bittikten sonra sunuculara yükleme bu süreçte hataları loglama takım içini süreçleri iyleştirme gibi bu daha da teknik ve teknik ortası bir iş ama teknik okumanın çok yüksek olduğu ve iyi özellikle büyük takımların devops hattlarının olmazsa olduğu bir nokta.


İşin sonu  hemen hemen her biriminde olan birisi olarak yazılım cs gibi bölümler çok çalışma çok emek çok okuma ister bunu yapabilirsen en rahat alabileceğin bölümlerdendir. Tavsiye almak önemli ama ben hep kendi denemelerim sonucunda buralara geldim sende dene ve buna eriş. Başarılar şimdiden
