### ISSUE TITLE
Fazla zaman alan veri çekme işlemleri

### ISSUE THREAD

**Issue by osmancan23** [VB10/vboverflow#73]
Örneğin bir e-ticaret uygulamasında bütün ürünlerin kategorisini çekmek istiyoruz . 1000 tane veri geliyor ve bunu drop down da göstermek istiyoruz bu işlemi göstermek istedigimiz view de çağırmak isteyince kullanıcı uzun bir süre verilerin gelmesini bekliyor. Örneğin uygulamanın home sayfasında çağırmak istersek de bu da eğer kullanıcının kategorilere ihtiyacı yoksa gereksiz yere veri çekme işlemi olmuş olacak . Bu işlemi nasıl yapmak daha performanslı olur ? (Pagination olmadığını varsayarsak :) )

**Comment by daybull** [comment]
Lazyload ile yapmak müşteri bekle süresini azaltır buda pagination a gelir
biraz sonuç olarak pagination değil 😇

20 Tem 2022 Çar 19:03 tarihinde Osmancan Akagündüz ***@***.***>
şunu yazdı:

**Comment by VB10** [comment]
servis tarafinda bir gelistirme olmadan yapabilecek tek bir sey var bu istegi splash gibi bir screende atip adam animasyonu izlerken datalari cachelemek, yeni geldiginde bu datayi tekrar update kotnrolu yaparak olmadigini varsayip ayni listeyi cachden gostermek
