### ISSUE TITLE
İyi bir Flutter geliştiricisi olmak

### ISSUE THREAD

**Issue by vlkan** [VB10/vboverflow#74]
Yakın zamanda yayımladığınız kursun dışında soruyorum, genel olarak Flutter ve Dart için önerdiği iz bir kitap, blog vs vsr mı? Sormamda ki amaç Flutter ı daha doğru nasıl kullanabilirim? Örnek olarak Java için Effective Java kitabı Java dilini en doğru nasıl kullanırız madde madde açıklamakta. Teşekkürler.

**Comment by endmr11** [comment]
Effective Dart icin kendi dokumanlari var 
https://dart.dev/guides/language/effective-dart
https://dart.dev/tools/linter-rules#prefer_collection_literals

**Comment by VB10** [comment]
volkan diger sorularda bunun cevabini verdik kapitilmis cevpalara bakarsin
