### ISSUE TITLE
Swift Öğrenim Süreci

### ISSUE THREAD

**Issue by bartugenccan** [VB10/vboverflow#75]
Veli Bey merhabalar sizi bir süredir takip ediyorum öncelikle videolarınız için teşekkür ederim elinize emeğinize sağlık. Ben şu an Frontend Developer olarak bir şirkette çalışıyorum React.js ve React Native kullanıyorum. Bir dönem Swift deneyimim olmuştu ama geliştirme ortamım çok iyi olmadığından bırakıp daha rahat iş bulabileceğim React tarafına geçmiştim, o dönemde de sizin videolarınızdan çok şey öğrendim. Son zamanlarda oluşan Web3 ve Blockchain furyası herkesin aklını çeliyor insanlar da bunu yatırım olarak kullanmaya başladı ama ben Apple ekosistemi içinde olmaktan çok keyif alıyorum ve bir şekilde bu ekosistemde yer almak istiyorum. Şu anda çalıştığım yerden çok memnunum ve yakın zamanda ayrılma gibi bir düşüncem yok, sizce boş zamanlarımda Swift'i tekrar öğrenip projeler geliştirip Apple Store'a atmam benim için mantıklı mı ? Eğer bir geçiş süreci olacaksa bu süreci uzun vadeye yaymak istiyorum bu şekilde hem React Native üzerinden çalışma tecrübesi hem de Swift tecrübem olacak. Biliyorum biraz uzun oldu ama tavsiyelerinize çok ihtiyacım var müsait bir zamanda okursanız çok memnun olurum şimdiden çok teşekkür ederim 😄

**Comment by VB10** [comment]
Natıve ogrenme her seyden onemlı bır mobile dev için fakat eğer kariyer pathini mobil de olsun diye bakacaksak çok fazla girmeye gerek yok aslında misal backend işte yada bu tarz fw kullandığınızda flutter vs kullanmak çok native girmeye gerek yok ama gerçkten native mobile dev olunacksa cross + native şart.

burada native öğrenirken 
https://github.com/matteocrippa/awesome-swift

**Comment by saitcihaner** [comment]
Veli Abim çok güzel paylaşmış bende nacizane component ve mimarileri kapsayan https://github.com/jrasmusson/ios-starter-kit paylaşıyım.Çok faydasını gördüm yeni başlayanlarda.
VB CANDIR
