### ISSUE TITLE
Image widget List

### ISSUE THREAD

**Issue by Mustyy61** [VB10/vboverflow#76]
Merhabalar.  Bir listem var ve Listemin içinde ımage pathlarım var. Yapmak isteğim şey tüm resimleri aynı anda ekrana bastırmak. Fakat Image widgetine listename[index] veya listname.length komutu verdiğimde hata alıyorum.  Çözümünü çok araştırdım ama bulamadım biraz komik ve basit bir soru olabilir. :)

**Comment by kadirozenn** [comment]
Merhaba,  bu şekilde kullanabilirsiniz. Eğer hala hata alıyorsanız mevcut kodu paylaşır mısınız?

```
ListView buildListPhoto(List<String> photoList) {
    return ListView.builder(
      itemCount: photoList.length,
      itemBuilder: (BuildContext context, int index) {
        return ClipRRect(
          borderRadius: BorderRadius.circular(6.0),
          child: Image.file(
            File((photoList[index])),
            height: 100.0,
            width: 100.0,
            fit: BoxFit.fill,
          ),
        );
      },
    );
  }

```

**Comment by Mustyy61** [comment]
Cevabın için çok teşekkür ederim. Evet bu şekilde ekrana tamanını alabiliyorum listemdeki verilerin ama hepsinin farklı pozisyonlarda olması gerekıyor. Positioned widgeti ile sarmaladım ama yinede hareket ettiremıyorum.

**Comment by Mustyy61** [comment]
![Screenshot_1658514499](https://user-images.githubusercontent.com/102856524/180501535-efacfe7f-779f-4b01-8e38-bad83ebe2ecf.png)
Haritanın üzerinde ki gri ile boyalı yerlerin üzerine gelmesi lazım listeden gelen parçaların ama yapamadım

**Comment by kadirozenn** [comment]
Aşağıdaki kodla sorunu çözebilir fakat responsive olmaz.

 _buildWidget()  methodun içindeki widgetList ilk endeksine attığınız resimdeki widgetleri ekleyin daha sonra fotoğrafları

```
Stack(
          children: _buildWidget(),
        )

 List<Widget> _buildWidget() {
    var widgetList = <Widget>[];
    widgetList.add(allWidgetler());
    for (var i = 0; i < photoList.length ; i++) {
      widgetList.add(Positioned(
        left: i * 10,
        child: setImage(photoList[i]),
      ));
    }

    return widgetList;
  }
```

**Comment by VB10** [comment]
bu ıster ıstemez ozel bir duruma giriyor @kadirozenn söylediği yöntemler mantıklı ama burada stack ve o elamanları oturma üzerine özel bir draw mantığı çizilmeli bana kalırsa 
https://pub.dev/packages/flutter_staggered_grid_view 
buna bakabilirsin

**Comment by Mustyy61** [comment]
Değerli vaktinizden ayırıp cevap verdiğiniz için çok  teşekkür ederim
