### ISSUE TITLE
flutter & react native  vs native 

### ISSUE THREAD

**Issue by alissorucu** [VB10/vboverflow#77]
twitterda notionun mobil uygulamasının react nativeden native'e geçirildiğiyle ilgili bir postla karşılaştım. Geçiş sonucunda ciddi bir hız farkından bahsedilmekte. Flutterda da bu derece performans kayıpları oluyor mu ? bu konudaki flutterın güncel gücü nedir, ? "native experience" bu videodaki kadar güçlü mü ? 
https://twitter.com/NotionHQ/status/1549787378633412614?s=20&t=IPbGvrxTk9G8Z-ZFsUt_gg

**Comment by abdullahkaraboga** [comment]
Bu konuda sayısal karşılaştırmaların yapıldığı ayrıntılı bir [makale ](https://medium.com/swlh/flutter-vs-react-native-vs-native-deep-performance-comparison-990b90c11433) ve [akademik bir çalışma ](https://tez.yok.gov.tr/UlusalTezMerkezi/TezGoster?key=tqUiYt63sTQLTpozMJ92QmkD0Ztj83ypZ-eRG4YutLxQ3-3Ey3_OyNdeFFm4ayZ1) mevcut. İnceleyip sorunuz hakkında bilgi sahibi olabilirsiniz.

**Comment by VB10** [comment]
selamlar bu karsılastırmaları ben açıkcası çok doğru bulmuyorum gerçek hayatta her şey çok farklı paremetreler ile sürüyor tabiki elinde işin mutfağını bilen aşçın varsa bununla ekip kurmak her zaman iyidir ki bir çok cross platform da aslında nativi ezmekten hiç bahsetmyior etseydi native bridge yapılarını ve rahatlıkla native yazabileceklerini öne çıkartırdı
* birde karşılaştırma yaparken hangi code
* hangi ortam yazan kim
*gerçekten 1-1 aynı kafa ilemi yazıldı çok paramatre var bunlara çok bakmadan karşılaştırma ne yazıkki doğru sonuçları vermyior.
iki tarafı yazan birisi olarak elbette native componen yazmak daha güçlü ama elinde böyle bir cross platformda flutter gibide güç varsa bunu kullanmamak işine yerine göre bu dönemde çok anlamsız geliyor bana.
