### ISSUE TITLE
Flutter Mobx de store'lar arası iletişim nasıl sağlanır

### ISSUE THREAD

**Issue by kasapiniz** [VB10/vboverflow#79]
Merhabalar, kolay gelsin.
Mobx de store'lar arası iletişim nasıl sağlanır. farklı sayfalarda aynı değerler toplu şekilde update etmek mümkün mü?
Genel olarak data çekme, gösterme, update etmek de sıkıntı yok ama birden fazla mobx store da aynı değeri update etme mantığını kavrıyamadım ve bulamadım. bunun için get_it yada provider mı kullanılmalı. Mantık olarak bir dönüş sağlarsanız sevinirim.

**Comment by VB10** [comment]
Bu tarz isler icin provider gibi ust bir katman kurmak lazim misal birden fazla store yonecekse core bir manager yapip bu vm leri oradan turetip referanslari dinleyip degistreiblrsiniz. buradaki amac rootda bir yapi olusturabilmek bunu paketle veya elle yapaiblrisin
