### ISSUE TITLE
IOS Simülatörde problemsiz çalışan uygulamanın canlıda çalışmaması

### ISSUE THREAD

**Issue by aea91** [VB10/vboverflow#8]
Uygulama debug halinde IOS Simülatörde sorunsuz çalışıyor.
iPhone 6s Plus ta problem çıkarıyor view ler iç içe girmiş halde gözüküyor.
Firebase Crashlytics the bir sorun gelmiş değil.
Sorunun kaynağını nası bulabilirim?
Teşekkürler

**Comment by VB10** [comment]
6s plus emulatoru indirip uygulamayi test edebilirsin bunun icin xcode uzerinden  daha dusuk bir model ios 13 vs indirip kurarsan o emulator gelecektir.

View patlama sorunu ise genel olarak kullanilan paketler vs ile dogru orantili olabilir bu debugu device uzerinde yapip anlayabilirsin veya https://pub.dev/packages/device_preview ile uygulamanin sizelerine bakabilirisn
<img width="942" alt="image" src="https://user-images.githubusercontent.com/17102578/173388756-09eeb03a-cf61-4a35-aaba-c734bdefeedf.png">

**Comment by aea91** [comment]
Teşekkür ederim.
