### ISSUE TITLE
FutureBuilder'ın sürekli rebuild olması

### ISSUE THREAD

**Issue by faithtnuc** [VB10/vboverflow#80]
Selamlar, kafama oturmayan bir konu var size sormak istedim. Ben state management için Provider kullanıyorum. Birkaç hocanın anlatımına göre de state management olayını StatefulWidget kullanımından kaçınmak için yapıyoruz ki tüm widget ağacı gereksiz rebuild olmasın. Bu mantığa göre de ben hep view dosyalarında StatelessWidget ile sadece görsel kodları tutup, metotları, değişkenleri vs provider ile viewmodel dosyalarında hallediyorum. Bunda sıkıntı yok ama şöyle bir problem var, FutureBuilder ile gösterdiğim apiden gelen veriler, TextFormField'a tıkladığımda ve klavyeyi kapattığımda iki kez rebuild oluyor. Bunu araştırarak çözümü şu şekilde bulmuştum:

StatefulWidget kullanıp future metodu initstate içinde ayrı bi değişkene alıp FutureBuilder'a öyle vermek. Bu şekilde yapınca çözülüyor ama bu sefer de her sayfada yine StatefulWidget kullanmak zorunda kalıyorum:

```dart

var _initClientsData;
List<Client> _allClientsList = [];

initState() {
    super.initState();
    _initClientsData = initClients();
}

```
```dart

Future<void> initClients() async {
final _clientViewModel = Provider.of<ClientViewModel>(context, listen: false);

final clients = await _clientViewModel.getAllClients();
    _allClientsList = clients;
}

```

```dart

FutureBuilder(
            future: _initClientsData,

```

StatefulWidget kullanımından kaçınabildiğim başka bir çözüm ise viewmodel içerisinde veriyi bir değişkene alıp o şekilde return etmek ve FutureBuilder içinde bu değişkeni kontrol etmek. Şu şekilde:

```dart

return FutureBuilder(
    future: createProfileViewModel.genres == null
          ? createProfileViewModel.fetchGenres()
          : null,

```

Bu yaklaşımlar doğru mudur? İkisi de değilse FutureBuilder yerine başka bir şey ile mi çözmem gerekiyor? Aslında iki yöntemle de sorunsuz çalışıyor ama içimde sanki yanlış bir şeyler var hissi bir türlü kaybolmadı. Acaba Provider mı bu konularda yetersiz kalıyor? Beni bi aydınlatırsanız çok sevinirim :)

**Comment by VB10** [comment]
yetersizlik konusu asla soz konusu degil sadece ney neden dogru dusunmek lazim future builder bir widget ve tree tetiklendiginde tkerar tekrar calsiiyor burada cok basitce soyl yapabilrisin
Future x 
initstate{  x = getAll}

Futurebuilder( x)
dersen o bir daha tetiklemez.

**Comment by faithtnuc** [comment]
Hocam teşekkürler cevabınız için. Ben de o yöntemi kullanıyordum içim rahatladı şimdi. Bu yöntem için StatefulWidget kullanmam gerekiyor bu da performansı kötü etkiler diye bir şey duymuştum bir yerden o beni sıkıntıya sokuyordu ama öyle bir şey yokmuş sanırım. Tüm widget treeyi güncellemedikten sonra StatefulWidget kullanmakta bi sakınca yokmuş anladığım kadarıyla.
