### ISSUE TITLE
SingleChildScrollView ile sarmalanmış Row veya Column 

### ISSUE THREAD

**Issue by basarteknoloji** [VB10/vboverflow#81]
Selamlar hocalarım. Örnek olarak paylaştığım satırlarda Row SingleChildScrollView ile sarıyorum. Row yada Column widgetleri ne zaman SingleChildScrollView ile sarsam "mainAxisAlignment" özellikleri çalışmıyor. Hizalama yapamıyorum. Bu kullanımdaki sorun nedir acaba ?

SingleChildScrollView(
                  scrollDirection: Axis.horizontal,
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.end,
                    children: [
                     Text('test1'),
                     Text('test2'),
                    ],
                  ),
                ),

**Comment by hakanpeksen** [comment]
Selamlar   @basarteknoloji
    
    /// Row  hizalama	
	return Scaffold(
        body: Center(
            child: SingleChildScrollView(
      child: Row(mainAxisAlignment: MainAxisAlignment.end, children: const [
        Text('test1'),
        Text('test2'),
      ]),
    )));
		

    /// Column hizalama 
     return Scaffold(
       body: Center(
             child: SingleChildScrollView(
      child: Column(children: const [
        Text('test1'),
        Text('test2'),
      ]),
   )));
   
   ///  Column  hizalama düzenlendi

      return Scaffold(
      appBar: AppBar(),
      body: SingleChildScrollView(
        child: SizedBox(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height * 0.3,
          child: Column(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: const [
            Text('test1'),
            Text('test2'),
          ]),
        ),
      )),

**Comment by abdullahkaraboga** [comment]
Ek olarak SingleChildScrollView yerine Listview de kullanabilirsiniz. Kullanacağınız widgetlerı liste içinde sıralayayıp direction da verebilirsiniz.  Ek olarak controller da kullanabilirsiniz. Listview kullanırsanız daha esnek arayüz tasarlama imkanı olur diye düşünüyorum.

**Comment by basarteknoloji** [comment]
Selamlar. Öncelikle değerli cevap ve yorumlarınız için çok teşekkür ederim . Hakan bey gönderdiğiniz kod bloğunu denediğimde hizalamanın doğru çalışmadığını görüyorum. [https://www.basarteknoloji.com/hakanpeksen.JPG](url)

Center ile sarmalamasam da basit bir kod bloğunda hizalamayı örnekteki kodlar ile yapamamış oluyorum. Buradaki sorun nedir ?
[https://www.basarteknoloji.com/singleChildScrollView.JPG](url)

Linkler üzerinden örneklere bakabilirseniz çok mutlu olurum

**Comment by okmsbun** [comment]
Merhaba scrollDirection `horizontal` olduğu için `Row` un `mainAxisAlignment`'ını kullanamassınız. Aynı şekilde scrollDirection `vertical` olsaydı `Column` için `mainAxisAlignment`'ı kullanamayacaktınız. Çünkü ilgili yönde sonsuza kadar item eklenebilir ve bunun bir sınırı yok. 

Çözüm için `Row `'u `SizedBox`(vb.) ile sarıp ona bir uzunluk verilebilir. Örneğin cihazın genişliği.
```
SingleChildScrollView(
        scrollDirection: Axis.horizontal,
        child: SizedBox(
          width: Get.width, //cihazın genişliği
          child: Row(
            mainAxisAlignment: MainAxisAlignment.end,
            children: const [
              Text('test1'),
              Text('test2'),
            ],
          ),
        ),
      )
```

Yada `ListView` `reverse` property sini `true`yapabilirsiniz. Verdiğiniz örnek için çalışıyor.
```
ListView(
        scrollDirection: Axis.horizontal,
        reverse: true,
        children: [
          Row(
            children: const [
              Text('test1'),
              Text('test2'),
            ],
          )
        ],
      ),
    );
```
**NOT**:`SingleChildScrollView` 'ın `reverse` property si var ama çalışmadı nedenini bilmiyorum.

**Comment by hakanpeksen** [comment]
> Selamlar. Öncelikle değerli cevap ve yorumlarınız için çok teşekkür ederim . Hakan bey gönderdiğiniz kod bloğunu denediğimde hizalamanın doğru çalışmadığını görüyorum. [https://www.basarteknoloji.com/hakanpeksen.JPG](url)
> 
> Center ile sarmalamasam da basit bir kod bloğunda hizalamayı örnekteki kodlar ile yapamamış oluyorum. Buradaki sorun nedir ? [https://www.basarteknoloji.com/singleChildScrollView.JPG](url)
> 
> Linkler üzerinden örneklere bakabilirseniz çok mutlu olurum

/// Column hizalama  düzenlendi
  return Scaffold(
  appBar: AppBar(),
  body: SingleChildScrollView(
    child: SizedBox(
      width: MediaQuery.of(context).size.width,
      height: MediaQuery.of(context).size.height * 0.3,
      child: Column(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: const [
        Text('test1'),
        Text('test2'),
      ]),
    ),
  )),

**Comment by basarteknoloji** [comment]
Sanırım aradığım çözümlerden biri "sizedbox" ile sarmalamak. Bünyamin beyin nezdinde yorum ve çözümleriniz için  teşekkür ederim.
Konuları soruyu soran kişimi kapatıyor yoksa yönetici olarak Veli hocam mı bilmiyorum bilgi bırakabilirseniz sevinirim.
Saygılarımla.

**Comment by VB10** [comment]
elinize sağlık
