### ISSUE TITLE
Getx mi block yapısı mı ? Nasıl karar vermeliyiz?

### ISSUE THREAD

**Issue by Mustafaseyhanhh** [VB10/vboverflow#82]
Merhabalar. Öncelikle içeriğiniz, videolarınız ve en çok da bizlere zaman ayırdığınız için çok teşekkür ederim. Yaklaşık 1 aydır Flutter çalışıyorum. Öncesinde birçok eğitim alıp izleyip anlamaya çalıştım ancak hiçbirisi sizin içeriğiniz kadar etkili ve anlaşılır değildi. Tekrar çok teşekkür ediyorum.

 Size bir sorum olacak. State management, navigation vb işlemler için getx çatısını kullanmak hakkındaki düşünceniz nedir. Kullanımı bloc yapısına göre daha pratik gibi ancak tabi ki sizden bir görüş almak projelerde kullanmak için oldukça önemli.

**Comment by abdullahkaraboga** [comment]
Merhaba, "bence" state management yapısına ilk giriş için getx yeterli olur. Observable çalışma mantığını öğrendikten sonra "getx'in kolaylık olarak nitelendirdiği (sizin de bahsettiğiniz navigation, snackbar, dialog vb)" olayların context bağımlılığı ile nasıl yapıldığını öğrenirseniz daha iyi olur. Sonra da diğer state management yapılarına bakabilirsiniz.

**Comment by VB10** [comment]
getx kullanmak evet projeler icin avantajli gozukuyor ancak buyuk proje buyuk takimlarda bunun yapilarinin parca parca ypailma taraftariyim/ cunku yazilim teknik tabilerini ogrenem adina cok onemli. Takim buyuklugu varsa bunlar goze alinlmali. he bazen projeler 1 aylik deadline sikisiyor ve bitmesi gerekiyor o sartlarda getx ile gidebilir. ama getx dahi olsa abstactionu bol bol yapmak lazim.
auto route
bloc
vs.
