### ISSUE TITLE
Change ThemeData with provider read

### ISSUE THREAD

**Issue by skyturkish** [VB10/vboverflow#83]
https://stackoverflow.com/questions/73145602/change-themedata-with-provider-read

Change theme yapıyorum ama aklıma bir şey takıldı, biz zaten bunu tetikleyerek değiştiriyoruz, bu zamana bağlı bir şey veya o tip bir şey değil, biz bunu neden watch ile izliyoruz. read ile okumamız gerekmiyor muydu

**Comment by hakanpeksen** [comment]
selamlar  @skyturkish
   context.read<T>()  // _currentTheme i değiştiriyor, fakat widget ağacını yeniden oluşturmuyor(dinleme yapmıyor)
   
   
    context.read<T>()    // Provider.of<T>(context, listen: false) 
    context.watch<T>()    // Provider.of<T>(context)
