### ISSUE TITLE
Mail'e gönderilen link üzerinden Flutter uygulamasını açma

### ISSUE THREAD

**Issue by safauludogan** [VB10/vboverflow#84]
Veli hocam merhaba,
Yapmış olduğum projede mail adresine gönderilen linke tıklandığı durumda Flutter uygulamamın açılmasını istiyorum. Bu konuda hangi dökümanı araştırmalıyım veya sizin böyle bir projeniz var mı? Yardımcı olabilir misiniz. Teşekkürler şimdiden

**Comment by abdullahkaraboga** [comment]
Merhaba, [burada](https://stackoverflow.com/questions/53770563/how-to-open-flutter-application-from-url) benzer bir soru sorulmuş.  [Şu paketi ](https://pub.dev/packages/app_links) de inceleyebilirsiniz.

**Comment by safauludogan** [comment]
Benim bahsettiğim uygulama içinden link açılması değil tam tersi link üzerinden uygulamanın açılması

**Comment by VB10** [comment]
bu konu iki sekilde incelenmel ibirincisi dynamic link ikincisi universal. universal link app icinde navigation yapar dynamic link google play vs indirmelrde ise yarar bu basliklar ile flutter tarafinda bulaiblirsin cozumleri.

**Comment by endmr11** [comment]
https://pub.dev/packages/firebase_dynamic_links direkt sorunun cevabi
