### ISSUE TITLE
Flutter FirebaseFirestore'dan veri çekerek kullanıcı profili oluşturma.

### ISSUE THREAD

**Issue by mdizman** [VB10/vboverflow#85]
Merhabalar. Flutter alanında üzerinde uğraştığım bir projem var.
return GestureDetector(
                                      onTap: (){
                                        Navigator.push(context, MaterialPageRoute(builder: (_)=> Anasayfa())); 
                                      },
                                      child: Card(
                                        elevation: 0,
                                        color: Color.fromARGB(255, 110, 110, 110),
                                        child: ListTile(
                                          title: Text('${listOfDocumentSnapshot[index]['b_adsoyad']}',
                                                      style: TextStyle(fontSize: 24),
                                                      
                                                      ),
                                          subtitle: Text('${listOfDocumentSnapshot[index]['a_brans']}',
                                                      style: TextStyle(fontSize: 16)),
                                        ),
                                      ),
                                    );
Bu kısımda FirebaseFirestore kısmından kullanıcı bilgilerimin 2 datasını ListTile alanında listeliyorum. Aynı zamanda Tüm kullanıcılarım bir Card içinde ve bu Cardlara tıklanılabilir özelliği verdim. Tıkladığımda yeni form a geçiş yapıyorum. Sıkıntı yaşadığım kısım tıkladığım Card'a (Örneğin id olarak ben "b_adsoyad" parametresini kullanıyorum.) girdiğimde firebase den o id ye ait tüm verileri ekranda göstermek. Çözüm fikirlerinize açığım.

**Comment by sinanhaci** [comment]
Selam, uzun süredir firebase kullanmıyorum ancak şu şekilde halledebiliyor olman gerekli,
Firestore.instance.collection('collection_adi').where("b_adsoyad", isEqualTo: "gönderilecek_parametre").get();

**Comment by mdizman** [comment]
> 

Sinan bey öncelikle çok teşekkür ederim deneyeceğim şu an. Gönderilecek parametre kısmına ne yazmam lazım acaba biraz takıldım o konuda.

**Comment by sinanhaci** [comment]
> > 
> 
> Sinan bey öncelikle çok teşekkür ederim deneyeceğim şu an. Gönderilecek parametre kısmına ne yazmam lazım acaba biraz takıldım o konuda.

kodunuzdan anladığım kadarıyla bu kısmı göndermelisiniz: listOfDocumentSnapshot[index]['b_adsoyad']

**Comment by mdizman** [comment]
Merhabalar. Benim gibi böyle bir çözüme ihtiyaç duyan arkadaş var ise kendi çözümümü paylaşmak istedim. 
-Öncelikle geçiş yapmak istediğimiz sayfanın StatefulWidget kısmına bir bir string tanımlayın. Bu string in amacı veri almak istediğimiz sayfa ile aracı olmak.

class Anasayfa extends StatefulWidget {
  //Anasayfa({Key? key}) : super(key: key);
  String kullaniciAdSoyad;
  Anasayfa({this.kullaniciAdSoyad=""});
  @override
  _AnasayfaState createState() => _AnasayfaState();
}

- Ardından hangi formdan veri çekmek istiyorsak o form a gidip Navigator.push içine yollamak istediğimiz değişkeni tanımalyınız.

Navigator.push(context, MaterialPageRoute(builder: (_)=> Anasayfa(kullaniciAdSoyad:listOfDocumentSnapshot[index]['b_adsoyad'])));

**Comment by sinanhaci** [comment]
> Merhabalar. Benim gibi böyle bir çözüme ihtiyaç duyan arkadaş var ise kendi çözümümü paylaşmak istedim. -Öncelikle geçiş yapmak istediğimiz sayfanın StatefulWidget kısmına bir bir string tanımlayın. Bu string in amacı veri almak istediğimiz sayfa ile aracı olmak.
> 
> class Anasayfa extends StatefulWidget { //Anasayfa({Key? key}) : super(key: key); String kullaniciAdSoyad; Anasayfa({this.kullaniciAdSoyad=""}); @OverRide _AnasayfaState createState() => _AnasayfaState(); }
> 
> * Ardından hangi formdan veri çekmek istiyorsak o form a gidip Navigator.push içine yollamak istediğimiz değişkeni tanımalyınız.
> 
> Navigator.push(context, MaterialPageRoute(builder: (_)=> Anasayfa(kullaniciAdSoyad:listOfDocumentSnapshot[index]['b_adsoyad'])));

Ben senin sorununu:  "Firebase'den sorgu ile data çekmek" diye anlamıştım. Şuan senin yaptığın işlem constructor ile farklı sayfaya data taşımak. Sanırım en başta anlaşamadık :)

**Comment by mdizman** [comment]
Aslında amacım o şekilde sorgu ile çekmekti doğru anladınız. Ama Navigator.push ile data taşındığını yeni öğrenince o şekilde yapabilirim diye düşündüm. Çok teşekkür ederim.

**Comment by VB10** [comment]
elınzıe salgık
