### ISSUE TITLE
Notification İşlemleri Hakkında

### ISSUE THREAD

**Issue by sinapsis793** [VB10/vboverflow#86]
Merhabalar,

Notification işlemleri hakkında, özellikle uygulama kapalıyken alınan bildirime tıklandığında sayfalara yönlendirme yapmak gibi, bir örnek video hazırlamanız mümkün olur mu?

Kolaylıklar dilerim.

**Comment by sinanhaci** [comment]
Selam, eğer bildirimler için Firebase kullanmayı düşünüyorsan, https://firebase.flutter.dev/docs/messaging/usage adresindeki döküman gayet açık. Tüm durumlar için nasıl kontrol sağlamanız gerektiğini kolay bir şekilde örnekleyerek anlatıyor. Göz atmanı tavsiye ederim.

**Comment by sinapsis793** [comment]
Selamlar,

Dönüşünüz için çok teşekkür ederim. Bildirim atma konusunda problem yaşamıyorum aslında ama bildirim atıldıktan sonra tıklama esnasında alınan datalara göre uygulama içerisinde iç sayfalara erişim konusunda problem yaşıyorum. Kodlama anlamında da örnek olması açısından güzel bir anlatım yapılabilir diye düşündüğüm için sormuştum.

**Comment by abdullahkaraboga** [comment]
Merhaba, [şöyle ](https://www.youtube.com/watch?v=l1OZFl45p3c)bir anlatım işinize yarayabilir.

**Comment by sinanhaci** [comment]
> Selamlar,
> 
> Dönüşünüz için çok teşekkür ederim. Bildirim atma konusunda problem yaşamıyorum aslında ama bildirim atıldıktan sonra tıklama esnasında alınan datalara göre uygulama içerisinde iç sayfalara erişim konusunda problem yaşıyorum. Kodlama anlamında da örnek olması açısından güzel bir anlatım yapılabilir diye düşündüğüm için sormuştum.

Benim attığım bağlantıda bu söylediklerinizin hepsini gösteriyor zaten.

**Comment by mehmetshakar** [comment]
> Merhabalar,
> 
> Notification işlemleri hakkında, özellikle uygulama kapalıyken alınan bildirime tıklandığında sayfalara yönlendirme yapmak gibi, bir örnek video hazırlamanız mümkün olur mu?
> 
> Kolaylıklar dilerim.

Merhaba, Sormuş olduğunuz sorunu düzeltiniz mi? ben de aynı sorunu yaşıyorum da... çözdüyseniz nasıl çözdüğünüzü anlatabilir misiniz? 


teşekkürler.
