### ISSUE TITLE
Store a atılcak uygulama için güzel fotoğraflar

### ISSUE THREAD

**Issue by aekaba** [VB10/vboverflow#88]
Merhabalar. Kendi CV mi bir uygulama haline getirdim ufak çaplı. Bunun için diğer uygulamalar gibi telefonun içinde uygulamayı gösteren insan eli flan olan fotoğrafları nasıl yapabileceğimi sormak istedim. Emulatörün ss ini almak biraz kötü duruyor birazdaha iyi birşey arıyorum. Birde öğrenciyim free olursa sevinirim. Evet hem professiyonel hemde bedava birşey arıyorum zor ama nasıl yapılcağı hakkında yardımcı olabilecek varsa sevinirim. Teşekkürler şimdiden.

**Comment by abdullahkaraboga** [comment]
[Şuradaki](https://hotpot.ai/app-store-screenshot-generator) picture generator sanıyorum işinizi görür.

**Comment by aekaba** [comment]
Teşekkürler

**Comment by VB10** [comment]
elinize sağlık
