### ISSUE TITLE
[Flutter] Reduce shader compilation jank

### ISSUE THREAD

**Issue by shahmirzali49** [VB10/vboverflow#9]
Flutter'ın ilk yüklenmede takılmalara böyle bir  çözüm sunmuş. -> **https://docs.flutter.dev/perf/shader** 

benim sorum bu addımları yaptıktan sonra **IOS**  tarafda markete atma kismi.

 docta `flutter build ios --bundle-sksl-path flutter_01.sksl.json` boyle bir komut calistirmamizi istiyor. calistirdiktan sonra Runner.app diye bir sey olusturuyor. runner.app la da birsey yapamiyoruz. simdi sorum bu komutu calistirdiktan sonra normal markete nasil uygulamani yukluyorsak oyle devammi etmemiz gerek yoksa runner.app la birsey yapmamiz gerekiyor mu?  cunki normal devam etdigimde cache bir etki etmiyor :/ . 

 sizde ios icin bu jank cache json kismi ile markete nasil yukluyorsaniz kismini paylassaniz guzel olur 👍

**Comment by VB10** [comment]
aslinda jank kismi son flutter 3 ile iyice cozuldu ozellikle bunu yapmadan flutter app'ini xcode uzerinden vs deploy edebilirsin store'lara. jank ozelinde bildigim upload ederken ozel bir detay yapmadan publish edeiblrsin

**Comment by shahmirzali49** [comment]
@VB10 malesef navigasyon kismi duzelmemis. ilk acildiginda halen takiliyor.

**Comment by VB10** [comment]
@Shahmirzali-Huseynov 
https://github.com/flutter/flutter/issues/13065

**Comment by VB10** [comment]
@Shahmirzali-Huseynov buradan bakip bir daha dener misin metal olmadna build alip atmayi

**Comment by shahmirzali49** [comment]
@VB10 teşekkür ederim deneyip buraya geri bildirim olarak yazacagim. en azindan bu runner.app la ne yapmam gerektigini gordum ya o bile yeter )) 😅

**Comment by shahmirzali49** [comment]
sonuc olarak buradaki (https://github.com/flutter/flutter/issues/13065) islemleri yapabildim. sanirim sorun cozulmus gibi. tekrar tesekkurler @VB10
