### ISSUE TITLE
BottomNavigationBar'ı Tüm Sayfalarda Görüntüleme -GetX

### ISSUE THREAD

**Issue by abdullahtas0** [VB10/vboverflow#90]
GetX kullanıyorum ve oluşturduğum bottomnavigationbarı tüm sayfalarda kullanmak istiyorum. Bunun için denemediğim yol kalmadı herhalde. CupertioneTab'dan keepalive kadar bütün yolları denedim ancak nafile. En son paket kullandım persistentnavbar ancak onunla da başarılı olamadım. 
Özetlemek gerekirse ana sayfaların olduğu kısımda bottomnavbarı görüntüleyip sayfalar arasında gezebiliyorum ancak sorun şu ki; Bu ana sayfaların altında olan sayfalarda navbarı görüntüleyemiyorum.
Örneğin; Ayarlar sayfası, ana sayfa  ancak onun içerisinde bulunan dil seçenekleri bir alt sayfa. İşte bu alt sayfada navbarı görüntülemek istiyorum. 

İlgili kodlarımı bırakıyorum;

BOTTOMNAVBAR_VIEW
```
class BottomNavbarView extends BaseView<BottomNavbarController> {
  @override
  Widget vBuilder() => Scaffold(
      bottomNavigationBar: SizedBox(
        width: Get.width,
        height: 60.h,
        child: BottomNavigationBar(
            onTap: (index) {
              controller.tabChange(index);
              if (index == 5) {
                Get.toNamed('profile');
              }
            },
            unselectedLabelStyle: TextStyle(fontSize: 0),
            unselectedFontSize: 0,
            unselectedIconTheme: IconThemeData(
              size: Get.width > 390 ? 24.sp : 24.sp,
            ),
            selectedFontSize: 0,
            selectedIconTheme: IconThemeData(
              size: Get.width > 390 ? 24.sm : 24.sm,
            ),
            selectedLabelStyle: TextStyle(fontSize: 0),
            type: BottomNavigationBarType.fixed,
            landscapeLayout: BottomNavigationBarLandscapeLayout.spread,
            unselectedItemColor: Colors.black,
            selectedItemColor: Colors.orange,
            showSelectedLabels: false,
            showUnselectedLabels: false,
            currentIndex: controller.tabIndex.value,
            items: [
              _bottomNavbarItem(AppAssets.card_icon, ''),
              _bottomNavbarItem(AppAssets.key_icon, ''),
              _bottomNavbarItem(AppAssets.home_icon, ''),
              _bottomNavbarItem(AppAssets.doc_icon, ''),
              _bottomNavbarItem(AppAssets.menu_icon, ''),
            ]),
      ),
      body: IndexedStack(
        index: controller.tabIndex.value,
        children: [
          DashBoardView(),
          BlankView(),
          HomeView(),
          BlankView(),
          MenuView(),
        ],
      ));
}

_bottomNavbarItem(String assetName, String label) {
  return BottomNavigationBarItem(
    icon: Image.asset(
      assetName,
      width: 24.w,
      height: 24.h,
      fit: BoxFit.contain,
    ),
    activeIcon: Container(
      height: 24.h,
      width: 24.w,
      decoration: BoxDecoration(
        border: Border(
          bottom: BorderSide(width: 2, color: Colors.orange),
        ),
      ),
      child: Image.asset(assetName),
    ),
    label: label,
  );
}
```
CONTROLLER
```
class BottomNavbarController extends BaseController {
  int current = 2;
  var tabIndex = 2.obs;

  GlobalKey<NavigatorState> navigatorKey = GlobalKey<NavigatorState>();

  PageController pageController = PageController();
  var selectedPage;

  List<Widget> pages = [
    DashBoardView(),
    BlankView(),
    HomeView(),
    BlankView(),
    MenuView(),
  ];

  tabChange(int index) {
    tabIndex.value = index;
    print(tabIndex.value);
    update();
  }

  @override
  void onInit() {
    super.onInit();
  }
}
```

**Comment by okmsbun** [comment]
Yanlış anlamadıysam sorunun GetX ile bir ilgisi yok gibi. Eğer öyle değil ise lütfen beni düzelt.

En basit şekilde bir tane base widget yazıp, sadece navigation bar'ın görünmesini istediğin sayfaları bu `BaseWidget` ile sarmalayabilirsin. 

Tavsiyem oluşturduğun tüm sayfaları `BaseWidget` ile sarıp, navigation barı gösterip göstermediğini parametre olarak göndermek. Çünkü ileride tüm sayfalarında başka bir işlem yapacaksan çok işine yarayacaktır. Örneğin geri tuşuna çift tıklandığında uygulamayı kapatmak isteyebilirsin, genel padding verip ayarları değişebilrisin, arkaplan rengi vb. hepsini tek bir yerden kontrol etmiş olursun. 

```dart
class BaseWidget extends StatelessWidget {
  const BaseWidget({
    Key? key,
    required this.child,
    this.navBarHide = false,
  }) : super(key: key);

  final Widget child;
  final bool navBarHide;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: child,
      bottomNavigationBar: !navBarHide ? const MyBottomNavigationBar() : null,
    );
  }
}
``` 
_../pro_offer_page.dart_
```dart
class ProOfferPage extends StatelessWidget {
  const ProOfferPage({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BaseWidget(
      // navBarHide: true
      child: Column(
        children: const [
          ...
        ],
      ),
    );
  }
}
```

**Comment by abdullahtas0** [comment]
> 

Öncelikle kıymetli yanıtınız için teşekkür ediyorum. Bir base oluşturmuştum ancak bu yapınızı bu base yapısına nasıl uyarlayacağımı bilemedim. Bu konuda yardımcı olabilirseniz sevinirim. 

BASE_VIEW

```
abstract class BaseView<T extends BaseController> extends StatelessWidget {
  BaseView({
    Key? key,
  }) : super(key: key);

  final String? tag = null;
  final AppTextStyle appTextStyle = AppTextStyle();
  final FormValidationHelper formValidationHelper = FormValidationHelper();

  T get controller => GetInstance().find<T>(tag: tag);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<T>(
      builder: (controller) {
        return vBuilder();
      },
    );
  }

  Widget vBuilder();
}
```

NASIL KULLANDIĞIMA DAİR ÖRNEK

```
/// [Example]
///
/// class HomeView extends BaseView<HomeController> {
///
///   @override
///   Widget vBuilder() => Scaffold(
///     appBar: AppBar(
///       title: Text("Title"),
///     ),
///     body: Container(
///       child: Center(
///         child: Text("Hello, world",
///           style: AppThemes().textTheme.bodyText1,
///         ),
///       ),
///     ),
///   );
///
/// }
```

**Comment by okmsbun** [comment]
Umarım bu yardımcı olur.

**BaseView**
```dart
abstract class BaseView<T extends BaseController> extends StatelessWidget {
  const BaseView({
    Key? key,
    this.navBarHide = false,
    this.appBarTitle = 'Title',
  }) : super(key: key);

  final bool navBarHide;
  final String appBarTitle;
  final String? tag = null;
  // final AppTextStyle appTextStyle = AppTextStyle();
  // final FormValidationHelper formValidationHelper = FormValidationHelper();

  T get controller => GetInstance().find<T>(tag: tag);

  @override
  Widget build(BuildContext context) {
    return GetBuilder<T>(
      builder: (controller) {
        return Scaffold(
          appBar: AppBar(title: Text(appBarTitle)),
          body: vBuilder(),
          bottomNavigationBar:
              !navBarHide ? const MyBottomNavigationBar() : null,
        );
      },
    );
  }

  Widget vBuilder();
}
```
**HomeView** 
```dart
class HomeView extends BaseView<HomeController> {
  const HomeView({Key? key})
      : super(
          key: key,
          appBarTitle: 'abc', // Title
          navBarHide: true, // false
        );

  @override
  Widget vBuilder() => const Center(child: Text('Hello, world'));
}
```

**Comment by abdullahtas0** [comment]
Çok teşekkür yardımınız için,size çok sağolun Allah razı olsun

**Comment by abdullahtas0** [comment]
Hocam çok özür diliyorum sizden önccelikle. Kusuruma bakmayın lütfen. Ben sayfa değiştirmek için scaffoldun body'de indexed stack kullanıyordum. Burada ontap ile itemleri sseçebiliyorum ancak sayfa değişmiyor. Bunun için nasıl bir yol izlemeliyim acaba? Ontap içinde switch case ile indexe göre yönlendirme mi yapmam gerekir?

**Comment by okmsbun** [comment]
Hiç sorun değil fakat bu sorduğunuz çok kapsamlı ve karışık bir konu ve bu issue' nin konusu değil :)
`GetX ` ile `State Management` için birden fazla yol bulunuyor. Bu yolu seçerken tüm yollara göz atmanız gerekli ve kendi ihtiyacınızı en iyi şekilde yarayan yolu siz seçmelisiniz.  Öncelikle aşağıdaki kaynaklara bakabilir ve çok daha fazla kaynak bulup onlara bakabilirsiniz.

> [GetX PubDev State Management](https://pub.dev/packages/get#state-management)
> [GetX blog.logrocket State Management](https://blog.logrocket.com/ultimate-guide-getx-state-management-flutter/)

Senin problemine ise çok basit bir şekilde örnek verecek olursam şöyle yapabilirsin;
Ben getx de State Management için `Obx` ve `Rx` kullanmayı tercih ediyorum.
Obx Widget inin içine Rx tipinde değişkenler koyduğunda Obx orayı dinliyor Rx tipinde değişkenin verisi değişirse Obx widget'ini tekrardan boyuyor. IndexedStack Widgetini Obx ile sarıp `index`'e RxInt tipinden değişkenin value 'sunu atıyorum. rxIndex değiştiğinde Obx tekrardan boyanıyor. Kolay gelsin.
```dart
class MyWidget extends StatelessWidget {
  const MyWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    // Bu değişkeni Controller class'larından çağırabilirsin.
    final Rx<int> rxIndex = 0.obs;

    const List<Widget> list = [
      Text('sayfa 1'),
      Text('sayfa 2'),
      Text('sayfa 3'),
      Text('sayfa 4'),
    ];

    return Scaffold(
      body: Column(
        children: [
          Obx(
            () {
              // Obx in içinde Rx tipinde en az bir veri kullanmak zorundasın.
              // Controller dan çağırabilirsin. || int get index => rxIndex.value;
              final int index = rxIndex.value;
              return IndexedStack(
                index: index,
                children: list,
              );
            },
          ),
          ElevatedButton(
            onPressed: () {
              if (rxIndex.value < list.length - 1) {
                // burada değer değiştiği için obx tekrardan boyuyor.
                rxIndex.value++;
              }
            },
            child: const Text('sonraki sayfa'),
          ),
          ElevatedButton(
            onPressed: () {
              if (rxIndex.value > 0) {
                // burada değer değiştiği için obx tekrardan boyuyor.
                rxIndex.value--;
              }
            },
            child: const Text('önceki sayfa'),
          ),
        ],
      ),
    );
  }
}
```

**Comment by abdullahtas0** [comment]
Hocam yanıt için teşekkür ederim benim kast ettğim şey baseview ile alakalı. Yani base bottomda bu işlemi nasıl gerçekleştireceğim bunu soruyordum. Bu işlemi ben bottomview içerisinde yapıyordum. Ancak bottom bir base haline gelince bunu base üzerinde nasıl yapacağımı sormak istedim aslında. Mesela geçici olarak şöyle bir şey yaptım;

```
onTap: (index) {
                    tabChange(index);
                    controller.update();
                    if (index == 0) {
                      Get.offAndToNamed('dashboard');
                    }
                    if (index == 1) {
                      Get.offAndToNamed('blank');
                    }
                    if (index == 2) {
                      Get.offAndToNamed('home');
                    }
                    if (index == 3) {
                      Get.offAndToNamed('blank');
                    }
                    if (index == 4) {
                      Get.offAndToNamed('menu');
                    }
                  },
```

**Comment by okmsbun** [comment]
Bottom bar'ı `BaseView` dan `extends`  yapmaman lazım. Çünkü BaseView bir ekranda bir tane olmalı ve ilgili ekranın Widget ağacının en üstlerinde bir yerlerde olmalı. Kendine Başka Base Widget lar yapabilirsin tabi. Ama cevabını verdiğim BaseView sadece bir sayfada bir tane olmalı çünkü bir `Scaffold` dönüyor. Bunu sardığın tüm widgetlar `ekran` gibi davranacaktır.

Bu yüzden eğer ihtiyacın var ise BottomBar widgetini hatta diğer tüm widget ların için başka bir base widget yapabilirsin.

`onTap` methodunda ise `tabChange` fonsiyonu ile zaten index değerini değiştirdiğini düşünüyorum. Yani tekrardan bir route yapmaman lazım. İndex değerinin değişip değişmediğini kontrol edip; eğer değişti ise ekranı tekrar boyamada problem olabilir ve State Management yanlış yapılmış olabilir.

**Comment by abdullahtas0** [comment]
> Bottom bar'ı `BaseView` dan `extends` yapmaman lazım. Çünkü BaseView bir ekranda bir tane olmalı ve ilgili ekranın Widget ağacının en üstlerinde bir yerlerde olmalı. Kendine Başka Base Widget lar yapabilirsin tabi. Ama cevabını verdiğim BaseView sadece bir sayfada bir tane olmalı çünkü bir `Scaffold` dönüyor. Bunu sardığın tüm widgetlar `ekran` gibi davranacaktır.
> 
> Bu yüzden eğer ihtiyacın var ise BottomBar widgetini hatta diğer tüm widget ların için başka bir base widget yapabilirsin.
> 
> `onTap` methodunda ise `tabChange` fonsiyonu ile zaten index değerini değiştirdiğini düşünüyorum. Yani tekrardan bir route yapmaman lazım. İndex değerinin değişip değişmediğini kontrol edip; eğer değişti ise ekranı tekrar boyamada problem olabilir ve State Management yanlış yapılmış olabilir.

Öncelikle geç yanıt için kusura bakmayın lütfen. Ancak bu çözümde ilk attığım koddan farkı ne onu anlayamadım. Yukarıda sizin vermiş olduğunuz kodlarda bir sorun yok ancak şuanda sorun; Sayfalar değiştiğinde ki onTap fonksiyonuna yazdığım if'lere yönlendirme yapıp geçiyorum- Sayfa değişince navbar seçili olan index değerini aktif olarak görmüyor. Yani aktif icon buton rengi kırmızı ise sayfa değişince benim seçtiğim ikonu değil varsayılan ikonu aktif sayıyor. Evet sayfa değişiyor hiç bir problem yok ancak navbarda ki  aktif ikon default ikon olarak kalıyor. Şu an için sorunum bu.

**Comment by okmsbun** [comment]
Hocam özür dilerim ben sizin 2. sorunuzu sürekli yanlış anlıyorum. Size tavsiyem eğer 1.sorunun cevabı yeterli ise bu issue yu kapatıp, bu issuyu referans göstererek yeni bir issue açmanız. Eminim yardımcı olacaklardır. Tekrardan kusura bakmayın iyi çalışmalar :)

**Comment by abdullahtas0** [comment]
Çok teşekkür ederim her şey için çok sağolun!

**Comment by okmsbun** [comment]
rica ederim iyi çalışmalar
