### ISSUE TITLE
Flutter Otomasyon Testi 

### ISSUE THREAD

**Issue by Hamittrpn** [VB10/vboverflow#91]
Herkese merhaba,

Flutter ile geliştirmeye başlayacağımız uygulamanın test tarafında tester arkadaşların otomasyon testlerini yazıp işletebileceği platform ve entegrasyon tavsiyeleriniz neler olur? Araştırmalarımda **TestingBot** ve **Appium** ile bir otomasyon testi entegrasyonu olabileceğini gördüm. Fakat TestingBot dökümantasyonunda sanırım deprecate olmuş olan **flutter_driver** paketini kullanıyor.

_bknz : https://testingbot.com/support/mobile/flutter.html#start_

Ücretli/ücretsiz platformlar ve entegrasyonlar ile ilgili deneyimlerinizi benimle paylaşırsanız çok memnun olurum.

Şimdiden Teşekkürler.

**Comment by VB10** [comment]
kanalda otomasyon uzerine cekmis oldugum bir videom var ona bakaiblrisin @Hamittrpn kolay gelsin
https://www.youtube.com/watch?v=km5m-Bv825c
