### ISSUE TITLE
Fluttter xml convert model

### ISSUE THREAD

**Issue by kadirozenn** [VB10/vboverflow#93]
Merhaba, Xml verilerini  modellere dönüştürüp ve bu verileri modellere aktarabileciğim kütüphane vs bir yolu var mı ?  ( json verilerini modellere dönüştürüp parse işlemi gibi kolay)

**Comment by abdullahkaraboga** [comment]
Sanırım [böyle](https://jsonformatter.org/xml-to-dart#Sample) bir tool işinize yarar.

**Comment by kadirozenn** [comment]
Attığınız tool daha öncedim tüm veri tiplerini String olarak algılıyor

**Comment by VB10** [comment]
bildigim yok bu konuyda stack over flow da aramani oneririm
