### ISSUE TITLE
Widget'ın child'ında hangi tipte bir Widget olduğunu nasıl bulurum

### ISSUE THREAD

**Issue by okmsbun** [VB10/vboverflow#94]
Birbirinden farklı `Widget` ların bulunduğu bir `liste`ye `extension` yazıyorum. Bu extension listedeki tüm widget ları `Padding` ile sarıp tekrar liste olarak döndürüyor. Ve tüm widget arasına boşluk vermiş oluyorum.

Fakat listedeki widgetların birinde en üstte, widget ağacının en tepesinde `Expanded` Widgeti bulunuyor. Bu yüzden yazdığım extension, Expanded widgetini Padding ile sarıyor. Expanded widgeti `Colum` yada `Row` içinde kullanılmadığı için `hata` dönüyor.

Bu yüzden listedeki Widget ların `ilk` çocuğunda expanded var mı yok mu bunu öğrenmek istiyorum. Yani bir widgeti child widgetinin hangi tipte olduğunu nasıl anlarım.
#### extension
Burada element 'in ilk çocuğu Expanded mı dğilmi kontrol etmem lazım.
```dart
extension WidgetList on List<Widget> {
  List<Widget> space({
    EdgeInsetsGeometry? padding,
    EdgeInsetsGeometry? margin,
  }) {
    return map((element) {
      // if (element.firstChild.runtimeType == Expanded || Flexible){} gibi bir kontrol ?
      return Container(
        padding: padding,
        margin: margin,
        child: element,
      );
    }).toList();
  }
}
```
#### örnek
`_Exercises` Widgeti `Expanded` dönüyor, onu `Padding` ile sarınca doğal olarak hata alıyorum.
```dart
  Widget build(BuildContext context) {
    return Column(
      children: const [
        _Time(),
        _MidTitle(),
        _Exercises(), // İlk child'ı Expanded
      ].space(padding: EdgeInsets.symmetric(vertical: 10.sp)),
    );
  }
```
#### _Exercises
```dart
class _Exercises extends StatelessWidget {
  const _Exercises({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Expanded( -> !!! //controll ?
      child: SingleChildScrollView(
        child: Column(
          children: const [
            _VideoCard(),
            ...
          ],
        ),
      ),
    );
  }
}
```

> [https://stackoverflow.com/questions/73241083/how-do-i-find-what-type-of-widget-is-in-the-widgets-child](https://stackoverflow.com/questions/73241083/how-do-i-find-what-type-of-widget-is-in-the-widgets-child)

**Comment by kadirozenn** [comment]
Merhaba, is anahtar  kelimesiyle widgetların hangi türden olduğunu bulabilirsin.

```
extension WidgetList on List<Widget> {
  List<Widget> paddingg({
    EdgeInsetsGeometry? padding,
    EdgeInsetsGeometry? margin,
  }) {
    final List<Widget> list = this;
    final List<Widget> listFinal = [];

    for (final Widget element in list) {
      if (element is Expanded) {
        listFinal.add(element);
      } else {
        listFinal.add(
          Container(
            padding: padding,
            margin: margin,
            child: element,
          ),
        );
      }
    }

    return listFinal;
  }
}

```

**Comment by okmsbun** [comment]
Cevabın için teşekkür ederim. Fakat elementin kendi tipine değil `ilk child`'ının tipine bakmak istiyorum.

**Comment by abdullahkaraboga** [comment]
Flutter inspector'den Widget Tree'ye bakmayı denediniz mi ?

**Comment by okmsbun** [comment]
Flutter inspector'u dart tarafında kullanabilir miyim? nasıl kullanırım?

**Comment by kadirozenn** [comment]
Hocam belki bu işinizi görebilir

```
extension WidgetList on List<Widget> {
  List<Widget> padding() {
    final List<Widget> list = this;
    final List<Widget> listFinal = [];

    for (Widget element in list) {
      if (element is Container) {
        if (element.child is Expanded) {
          
        }
      } else if (element is Center) {
        if (element.child is Expanded) {

        }
      } else {
        listFinal.add(
          Container(
            child: element,
          ),
        );
      }
    }

    return listFinal;
  }
}

```

**Comment by okmsbun** [comment]
Hocam  öncelikle çabanız için çok teşekkür ederim. 
Ama bu şekilde olmaz çünkü element widget'i `StatelessWidget` yada `StatefulWidget` ise çalışmaz. StatelessWidget yada StatefulWidget dan extends edilen widgetin child property sine zaten ulaşılamıyor. Yani `is Container` yada `is Center` her zaman `false` dönecek ve hiçbir zaman `child` ' a ulaşamayız.

Sizin gösterdiğiniz örnekte `is Container` `true` ise, o koşul sağlanmışsa o bloğa giriyor ve artık element widgeti Container gibi davrandığı için `child` property sine ulaşabiliyoruz. Ama benim verdiğim örnek te kendi widgetlarımın hepsi StatelessWidget yada StatefulWidget tır. Yani o bloğa hiçbir zaman girmeyecek, hep false gelecek. Bu yüzden child 'ına ulaşılamaz.

**Örnekte gösterdiğim _Exercises widgeti**
```dart
class _Exercises extends StatelessWidget {
  const _Exercises({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Expanded( -> !!! //controll ?
      child: SingleChildScrollView(
        child: Column(
          children: const [
            _VideoCard(),
            ...
          ],
        ),
      ),
    );
  }
}
```

**Comment by VB10** [comment]
bu tarz bir extensıon her wıdgetı anlamak yerine yapacağın extensionda iki tane ayrım yaparsın bunu kullanıcı karar verir is expanded gibi gibi flutter html paketine bakabilrisn orada misal listview column olarak tipe vereibliyoruz
