### ISSUE TITLE
Flutter uygulama güncelleme ve remote?

### ISSUE THREAD

**Issue by SonerBscfc** [VB10/vboverflow#96]
Yapmış olduğumuz Flutter projelerini canlıda nasıl tutabiliriz? Şu an sürekli yeni apk alarak uygulamayı güncelliyorum. Fakat bunun daha kolay bir yolu var mıdır? Mesela Remote bir şekilde yapabileceğim? Neleri, hangi kavramları öğrenmem-araştırmam gerek?

**Comment by VB10** [comment]
remote config kavramını öğrenmen yeterli olacaktır. firebase vya kendi custom servisin. bu flutter değil genel bir config managment olarak geçer
