### ISSUE TITLE
Provider ile theme değiştirmeye çalışıyorum ama tema hiçbir şekilde değişmiyor. Eksik veya hatalı kısım nerede acaba

### ISSUE THREAD

**Issue by nuriulgen** [VB10/vboverflow#97]
<img src="https://user-images.githubusercontent.com/45700377/183255633-319a9479-8df3-44db-80c8-659fec3beabb.png"  width="500" height="350" />

<img src="https://user-images.githubusercontent.com/45700377/183255667-e01cd078-e2f2-4187-840d-439efecb6a0f.png"  width="500" height="350" />

<img src="https://user-images.githubusercontent.com/45700377/183255777-92a19bb4-6ce0-46ac-a2c5-ad96eefc0be9.png"  width="500" height="350" />

**Comment by hakanpeksen** [comment]
Selamlar,  main.dart da  ChangeNotifierProvider ı oluşturduğun için,  ThemeChangeState sayfanda  bir daha  ChangeNotifierProvider ı  oluşturman  gerekmiyor,  
kodların doğru çalışması lazım

**Comment by VB10** [comment]
bu tarz soruları öncelik stackoverflow üzerinde açmak teknik olarak gelişim ve o rayı anlama adına kodsal bir sorun yok gibi duruyor
