### ISSUE TITLE
Yüklü uygulamanın iconunu değiştirme

### ISSUE THREAD

**Issue by sinanhaci** [VB10/vboverflow#99]
Selamlar,

Bazı uygulamalarda doğum günlerinde filan uygulamanın iconu değişiyor, yada normal account sahibiyken premiuma geçince uygulamanın simgesi değişiyor. Bu olayı flutter ile yapmak mümkün müdür? Böyle bir deneyimi olan var mı daha önce? 

Teşekkürler

**Comment by aydemiromer** [comment]
Fikir olması adına söyülüyorum firebase remote config ile uygulama içi değişiklikler yönetilebiliyordu uzaktan belki icon tarafıda o şekilde sağlanabilir (Sadece fikir)

**Comment by abdullahkaraboga** [comment]
Kullanıcının doğum gününü ya da kullanıcı tipini localde DateTime olarak saklamanız daha mantıklı bence. 

İcon değiştirme olayını manuel olarak yapmak isterseniz icon değişimi için ayrı build almak gerekiyor mu yoksa runtime'da mı icon atanıyor öğrenmeniz gerekiyor.

[Şu paketi](https://pub.dev/packages/flutter_dynamic_icon/versions/2.0.0) inceleyin isterseniz. Sorunuza çözüm olabilir sanırım.

**Comment by abdullahkaraboga** [comment]
Kullanıcının doğum gününü localde DateTime olarak saklamanız daha mantıklı bence. Aynı şekilde kullanıcı tipini de int olarak saklayabilirsiniz.

İcon değiştirme olayını kendiniz yazmak isterseniz icon değişimi için ayrı build almak gerekiyor mu yoksa runtime'da mı icon atanıyor öğrenmeniz gerekiyor.

[Şu paketi](https://pub.dev/packages/flutter_dynamic_icon/versions/2.0.0) inceleyin isterseniz. Sorunuza çözüm olabilir sanırım.

**Comment by sinanhaci** [comment]
> Kullanıcının doğum gününü localde DateTime olarak saklamanız daha mantıklı bence. Aynı şekilde kullanıcı tipini de int olarak saklayabilirsiniz.
> 
> İcon değiştirme olayını kendiniz yazmak isterseniz icon değişimi için ayrı build almak gerekiyor mu yoksa runtime'da mı icon atanıyor öğrenmeniz gerekiyor.
> 
> [Şu paketi](https://pub.dev/packages/flutter_dynamic_icon/versions/2.0.0) inceleyin isterseniz. Sorunuza çözüm olabilir sanırım.

Evet tam olarak aradığım şey bu aslında ancak bu kütüphane de android desteği yok. Biraz daha araştırayım. Teşekkürler
